import type { DocRegistry } from '@/features/doc-panel/types';

const dnaWritingStyleDocs: DocRegistry = {
  _default: {
    title: 'DNA Writing Style',
    description: 'Overview of the DNA Writing Style feature.',
    content:
      "DNA Writing Style profiles capture a doctor's personal tone, formality, sentence structure, and vocabulary. " +
      'Profiles are generated by analyzing text samples and are applied automatically when generating clinical summaries. ' +
      'Each report is versioned so you can track style evolution over time.',
  },
  'dna-header': {
    title: 'Generate Style Profile',
    description: 'Start generating a new DNA writing style report.',
    content:
      'Click "Generate Style" to open the generation form. ' +
      "Provide sample clinical notes written in the target doctor's voice. " +
      'The AI analyzes tone, sentence length, medical term usage, formality, and abbreviation patterns to build the style profile.',
  },
  'dna-reports-list': {
    title: 'Reports List',
    description: 'Browse all DNA writing style reports for this doctor.',
    content:
      'Each row represents one generated writing style report. Active reports are used by the Summarization features. ' +
      'Archived reports are retained for reference. Select a report to view its full detail or open the version history.',
  },
  'dna-report-detail': {
    title: 'Active Writing Style',
    description: 'Quick view of the current active DNA writing style.',
    content:
      'This card shows the derived style characteristics of the current active report: tone, formality, sentence length, medical term usage, ' +
      'abbreviation style, vocabulary, and structural preferences. ' +
      'Generate a new report or update the existing one to keep the profile accurate.',
  },
  'dna-generate-form': {
    title: 'Generation Form',
    description: 'Provide text samples to generate a new writing style.',
    content:
      'Paste 2–5 clinical notes authored by the doctor. More samples yield a more accurate style profile. ' +
      'In debug mode you can impersonate a different doctor to generate their profile. ' +
      'Choose SSE streaming for a real-time generation view, or polling to check completion in the background.',
  },
  'dna-streaming-view': {
    title: 'Streaming Report View',
    description: 'Live view of report content being generated via SSE.',
    content:
      'When SSE streaming is used, report text appears progressively as the model generates it. ' +
      'You can cancel mid-generation. Once complete the report is automatically saved and appears in the reports list.',
  },
  'dna-edit-form': {
    title: 'Edit Writing Style',
    description: 'Manually adjust the generated writing style report.',
    content:
      'Refine individual attributes such as tone, formality, sentence length, medical term usage, ' +
      'abbreviation style, vocabulary, and structural preferences. ' +
      'A change reason is required for audit traceability. Saving creates a new version of the report.',
  },
  'dna-impersonation': {
    title: 'Impersonation Mode',
    description: 'Manage writing styles on behalf of a doctor.',
    content:
      'Admin users can impersonate a doctor to view or generate writing style profiles on their behalf. ' +
      'When impersonation is active a banner indicates whose profile you are managing. ' +
      "Changes are attributed to the impersonated doctor's account.",
  },
};

export default dnaWritingStyleDocs;
