/**
 * Pure helpers for the `hope-models` MinIO bucket layout — see
 * `infrastructure/docker/minio/README.md` §5 for the full convention.
 *
 * `<version>` is content-addressed: `<quant-token>-<first 12 hex chars of
 * sha256(SHA256SUMS)>` (e.g. `q4-0-451faffb5a16`, `q4-k-m-1af04917c451` —
 * the two live bucket keys the orchestrator gave as ground truth for
 * TASK-855 lane L3). `SHA256SUMS` is generated by the downloader itself —
 * one `<sha256>  <path>` line per downloaded object, the same shape
 * `shasum -a 256 ./*` produces — never read from the source repo.
 *
 * No network / filesystem I/O in this module — everything here is a pure
 * function over bytes/strings so the version-derivation logic can be unit
 * tested without a real HuggingFace or MinIO endpoint.
 */
import { createHash } from 'node:crypto';

/**
 * Matches common GGUF quantization tokens: Q4_0, Q4_K_M, Q5_K_S, Q8_0, IQ4_XS, ...
 * Bounded by `-`/`_`/start on the left and `-`/`_`/`.`/end on the right rather
 * than `\b`, because the token is routinely glued to the rest of the filename
 * with an underscore (`..._q4_0-it.gguf`) — a `\b` between two word
 * characters never matches.
 */
const QUANT_TOKEN_RE = /(?:^|[-_])(I?Q\d(?:_\d)?(?:_[A-Z0-9]+)*)(?=[-_.]|$)/i;

/** Known non-weight companion files a served model needs alongside its weights. */
const RELEVANT_BASENAMES = new Set([
  'config.json',
  'tokenizer.json',
  'tokenizer_config.json',
  'vocab.json',
  'merges.txt',
  'special_tokens_map.json',
  'generation_config.json',
]);

/**
 * Lowercase + hyphenate a raw quant string: `Q4_0` -> `q4-0`, `Q4_K_M` -> `q4-k-m`.
 * Matches the live bucket's key-safe quant-token spelling.
 */
export function normalizeQuantToken(raw: string): string {
  return raw
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Best-effort quant-token extraction from a list of candidate strings (repo
 * name, then downloaded filenames, in the order the caller supplies them).
 * Returns the FIRST match, normalized, or `null` when nothing looks like a
 * GGUF quant token — callers must fall back to the bare content hash in that
 * case (see `deriveModelVersion`) rather than fabricate one.
 */
export function deriveQuantTokenFromFilenames(candidates: string[]): string | null {
  for (const candidate of candidates) {
    const match = candidate.match(QUANT_TOKEN_RE);
    if (match) return normalizeQuantToken(match[1]);
  }
  return null;
}

/**
 * Whether `path` is one of the file kinds the `hope-models` publish step
 * cares about: GGUF weights/projector shards, or a small fixed set of
 * tokenizer/config companions. Everything else (README, LICENSE, git
 * metadata, alternate export formats) is deliberately left behind so a
 * download never silently pulls unrelated bytes out of a source repo.
 */
export function isRelevantModelSourceFile(path: string): boolean {
  const base = (path.split('/').pop() ?? path).toLowerCase();
  if (base.endsWith('.gguf')) return true;
  return RELEVANT_BASENAMES.has(base);
}

/**
 * Render the `SHA256SUMS` object exactly as `shasum -a 256 ./*` would: one
 * `<sha256>  <path>` line per file (two spaces, matching `shasum`/`mc`
 * interop), newline-terminated.
 */
export function buildSha256SumsContent(files: ReadonlyArray<{ path: string; sha256: string }>): string {
  return files.map((f) => `${f.sha256}  ${f.path}`).join('\n') + '\n';
}

/** SHA256 hex digest of a `Buffer` or utf8 `string`. */
export function sha256Hex(data: Buffer | string): string {
  return createHash('sha256').update(data).digest('hex');
}

/**
 * `<version>` = `<quant>-<sha256sums-hash-12>`, or the bare 12-char hash when
 * no quant token could be derived (single-artifact / non-GGUF sources).
 */
export function deriveModelVersion(quant: string | null, sha256SumsContent: string): string {
  const hash12 = sha256Hex(sha256SumsContent).slice(0, 12);
  return quant ? `${quant}-${hash12}` : hash12;
}
