/**
 * Pure helpers for the `hope-models` MinIO bucket layout — see
 * `infrastructure/docker/minio/README.md` for the full convention.
 *
 * `<version>` is content-addressed: `<quant-token>-<first 12 hex chars of
 * sha256(SHA256SUMS)>` (e.g. `q4-0-451faffb5a16`, `q4-k-m-1af04917c451` —
 * the two live bucket keys the orchestrator gave as ground truth for
 * lane L3). `SHA256SUMS` is generated by the downloader itself
 * one `<sha256> <path>` line per downloaded object, the same shape
 * `shasum -a 256 ./*` produces — never read from the source repo.
 *
 * No network / filesystem I/O in this module — everything here is a pure
 * function over bytes/strings so the version-derivation logic can be unit
 * tested without a real HuggingFace or MinIO endpoint.
 */
import { createHash } from 'node:crypto';

/**
 * Matches common GGUF quantization tokens: Q4_0, Q4_K_M, Q5_K_S, Q8_0, IQ4_XS, ...
 * Bounded by `-`/`_`/start on the left and `-`/`_`/`.`/end on the right rather
 * than `\b`, because the token is routinely glued to the rest of the filename
 * with an underscore (`..._q4_0-it.gguf`) — a `\b` between two word
 * characters never matches.
 */
const QUANT_TOKEN_RE = /(?:^|[-_])(I?Q\d(?:_\d)?(?:_[A-Z0-9]+)*)(?=[-_.]|$)/i;

/**
 * Weight-file extensions this platform can actually serve.
 *
 * `.gguf` alone was not enough, and the omission was silent — a
 * repo with no matching file simply published nothing rather than failing.
 * Measured against the three models the owner nominated for validation:
 *
 * | Repo | Weight file | Fetched before |
 * |---|---|---|
 * | `unsloth/Qwen3-0.6B-GGUF` | `*.gguf` | yes |
 * | `blaze999/Medical-NER` | `model.safetensors` | **no** |
 * | `taphuynh/whisper-…-gguf` | `ggml-…-q5_0.bin` | **no** |
 *
 * Two of three fetched ZERO weights; the whisper repo fetched nothing at all,
 * because a whisper.cpp `ggml-*.bin` is not a `.gguf` despite the repo name.
 */
const WEIGHT_EXTENSIONS = [
  '.gguf', // llama.cpp / LM Studio
  '.safetensors', // transformers (nlp, tts, whisper fp16)
  '.bin', // whisper.cpp ggml, legacy pytorch_model.bin
  '.onnx', // silero-vad, ONNX exports
  '.nemo', // NVIDIA NeMo ASR
  '.pt', // torch checkpoints (kokoro voices)
  '.pth',
  '.model', // sentencepiece (spm.model)
] as const;

/**
 * `.bin` is load-bearing for whisper.cpp AND the extension HuggingFace uses for
 * training bookkeeping, so it needs a denylist rather than a blanket accept.
 * These are trainer state, never inference weights — pulling them wastes
 * bandwidth and bloats the published prefix.
 */
const NON_WEIGHT_BASENAMES = new Set([
  'training_args.bin',
  'optimizer.bin',
  'optimizer.pt',
  'scheduler.bin',
  'scheduler.pt',
  'rng_state.bin',
  'trainer_state.json',
]);

/** Known non-weight companion files a served model needs alongside its weights. */
const RELEVANT_BASENAMES = new Set([
  'config.json',
  'tokenizer.json',
  'tokenizer_config.json',
  'vocab.json',
  'merges.txt',
  'special_tokens_map.json',
  'generation_config.json',
  // additions, each required by a model in the live catalogue:
  'added_tokens.json', // blaze999/Medical-NER
  'preprocessor_config.json', // whisper / feature-extractor models
  'model.safetensors.index.json', // sharded safetensors manifest
  'pytorch_model.bin.index.json', // sharded legacy manifest
]);

/**
 * Lowercase + hyphenate a raw quant string: `Q4_0` -> `q4-0`, `Q4_K_M` -> `q4-k-m`.
 * Matches the live bucket's key-safe quant-token spelling.
 */
export function normalizeQuantToken(raw: string): string {
  return raw
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Best-effort quant-token extraction from a list of candidate strings (repo
 * name, then downloaded filenames, in the order the caller supplies them).
 * Returns the FIRST match, normalized, or `null` when nothing looks like a
 * GGUF quant token — callers must fall back to the bare content hash in that
 * case (see `deriveModelVersion`) rather than fabricate one.
 */
export function deriveQuantTokenFromFilenames(candidates: string[]): string | null {
  for (const candidate of candidates) {
    const match = candidate.match(QUANT_TOKEN_RE);
    if (match) return normalizeQuantToken(match[1]);
  }
  return null;
}

/**
 * Whether `path` is one of the file kinds the `hope-models` publish step
 * cares about: GGUF weights/projector shards, or a small fixed set of
 * tokenizer/config companions. Everything else (README, LICENSE, git
 * metadata, alternate export formats) is deliberately left behind so a
 * download never silently pulls unrelated bytes out of a source repo.
 */
export function isRelevantModelSourceFile(path: string): boolean {
  const base = (path.split('/').pop() ?? path).toLowerCase();
  // Trainer bookkeeping first: it shares `.bin`/`.pt` with real weights.
  if (NON_WEIGHT_BASENAMES.has(base)) return false;
  if (WEIGHT_EXTENSIONS.some((ext) => base.endsWith(ext))) return true;
  return RELEVANT_BASENAMES.has(base);
}

/**
 * Render the `SHA256SUMS` object exactly as `shasum -a 256 ./*` would: one
 * `<sha256> <path>` line per file (two spaces, matching `shasum`/`mc`
 * interop), newline-terminated.
 */
export function buildSha256SumsContent(files: ReadonlyArray<{ path: string; sha256: string }>): string {
  return files.map((f) => `${f.sha256}  ${f.path}`).join('\n') + '\n';
}

/** SHA256 hex digest of a `Buffer` or utf8 `string`. */
export function sha256Hex(data: Buffer | string): string {
  return createHash('sha256').update(data).digest('hex');
}

/**
 * `<version>` = `<quant>-<sha256sums-hash-12>`, or the bare 12-char hash when
 * no quant token could be derived (single-artifact / non-GGUF sources).
 */
export function deriveModelVersion(quant: string | null, sha256SumsContent: string): string {
  const hash12 = sha256Hex(sha256SumsContent).slice(0, 12);
  return quant ? `${quant}-${hash12}` : hash12;
}
