/**
 * lane B — CONTRACT CONFORMANCE.
 *
 * The other suite asserts the SDK calls the paths it means to. This one asserts
 * those paths are the ones the GATEWAY actually ships, by reading
 * `apps/api/route-manifest.json` — the authorization oracle
 * (`.claude/rules/05-nestjs-api.md` §API Test Standard) — off disk.
 *
 * Without this, an SDK is only ever self-consistent: every path assertion in
 * the sibling suite would keep passing after lane A renamed a route. Here a
 * rename is a red test.
 *
 * The manifest is read, never regenerated: regenerating it is lane A's job and
 * a diff here is a REPORT, not a fix.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { RESERVED_RUN_IDENTITY_KEYS } from '../../core/run-identity';
import { WORKFLOW_PLANE_ROUTES } from '../workflows';

interface ManifestRoute {
  method: string;
  path: string;
  isPublic: boolean;
  requiredPermissions: string[][] | null;
  apiKeyForbidden: boolean;
  apiKeyScopes: string[] | null;
  svcScopes: string[] | null;
}

/**
 * Located by ASCENDING from `process.cwd()` to the workspace marker, not by a
 * fixed number of `..` hops: this suite runs under two different roots —
 * `packages/vox-node` for `pnpm --filter @arcaai/vox-node test`, and the repo
 * root for the workspace-wide `pnpm test:unit`. A hop count is correct for
 * exactly one of them and silently ENOENTs on the other.
 *
 * Derived from `process.cwd()` rather than `import.meta.url` because this
 * package's tsconfig emits CommonJS, where `import.meta` is a hard type error.
 */
function findRepoRoot(): string {
  let dir = process.cwd();
  for (;;) {
    if (existsSync(join(dir, 'pnpm-workspace.yaml'))) return dir;
    const parent = resolve(dir, '..');
    if (parent === dir) throw new Error('could not locate the repo root (no pnpm-workspace.yaml above ' + process.cwd() + ')');
    dir = parent;
  }
}

const REPO_ROOT = findRepoRoot();

function loadManifest(): ManifestRoute[] {
  const raw = JSON.parse(readFileSync(join(REPO_ROOT, 'apps', 'api', 'route-manifest.json'), 'utf8')) as unknown;
  const rows = Array.isArray(raw) ? raw : ((raw as { routes?: unknown }).routes as unknown);
  if (!Array.isArray(rows)) throw new Error('route-manifest.json: unrecognized shape');
  return rows as ManifestRoute[];
}

const MANIFEST = loadManifest();

function find(method: string, path: string): ManifestRoute | undefined {
  return MANIFEST.find((r) => r.method === method && r.path === path);
}

/**
 * TASK-890's two human-review routes shipped with wave 1 and the orchestrator
 * regenerated `route-manifest.json` at the merge (rule 05 §Definition of Done).
 * The partition that skipped them while the artifact lagged is GONE: every
 * route this SDK calls — the review pair included — is asserted unconditionally.
 * Do not reintroduce a pending list without a route that is genuinely in flight.
 */
const REVIEW_ROUTES = WORKFLOW_PLANE_ROUTES.filter((r) => r.path.includes('/reviews/'));

/** The two planes have different credential contracts since TASK-930 — see below. */
const CONSULTATION_ROUTES = WORKFLOW_PLANE_ROUTES.filter((r) => r.path.includes('/consultations/'));
const UNBOUND_ROUTES = WORKFLOW_PLANE_ROUTES.filter((r) => !r.path.includes('/consultations/'));

/**
 * Routes this SDK calls that the SHIPPED manifest does not carry yet.
 *
 * `POST …/runs/{runId}/stream-ticket` is TASK-930 §4, landing in the gateway lane of the same
 * wave; the manifest is regenerated by the orchestrator at integration (rule 05 §Definition of
 * Done), never here. This entry MUST be emptied in that regeneration commit — a pending list
 * that outlives the route it was waiting for is how a missing route stops being noticed.
 */
const PENDING_GATEWAY_ROUTES: ReadonlySet<string> = new Set([]); // TASK-930: the stream-ticket route landed with lane N

/**
 * `true` while the manifest on disk predates TASK-930's service-account scopes.
 *
 * Detected, not configured: the wave declares `svc:workflow:run:write` on the unbound plane, so
 * its ABSENCE from every row is the manifest saying "I am the old one". Once the orchestrator
 * regenerates, this flips to `false` and the assertions below become real, unconditional gates.
 */
const MANIFEST_PREDATES_TASK930 = !MANIFEST.some((route) => (route.svcScopes ?? []).includes('svc:workflow:run:write'));

describe('every route this SDK calls exists in the shipped route manifest', () => {
  it.each(WORKFLOW_PLANE_ROUTES)('$method $path', ({ method, path }) => {
    if (PENDING_GATEWAY_ROUTES.has(`${method} ${path}`)) {
      expect(find(method, path), `${method} ${path} is listed as a pending gateway route`).toBeUndefined();
      return;
    }
    expect(find(method, path)).toBeDefined();
  });
});

describe('the TASK-890 human-review routes', () => {
  it('covers both of them', () => {
    expect(REVIEW_ROUTES).toHaveLength(2);
  });

  it.each(REVIEW_ROUTES)('$method $path is the business plane with a run scope', ({ method, path }) => {
    const route = find(method, path)!;
    expect(route.isPublic).toBe(false);
    expect(route.apiKeyForbidden).toBe(false);
    expect(route.apiKeyScopes).toEqual([method === 'GET' ? 'workflow:run:read' : 'workflow:run:write']);
  });
});

describe('the credential class the SDK assumes is the one the gateway enforces', () => {
  it.each(WORKFLOW_PLANE_ROUTES.filter((r) => !PENDING_GATEWAY_ROUTES.has(`${r.method} ${r.path}`)))(
    '$method $path is API-key reachable — this is the business plane',
    ({ method, path }) => {
      const route = find(method, path)!;
      expect(route.apiKeyForbidden).toBe(false);
      expect(route.apiKeyScopes?.length ?? 0).toBeGreaterThan(0);
    },
  );

  /**
   * AMENDED TASK-931, then SUPERSEDED by TASK-933. The TASK-931 text asserted `svcScopes: []`
   * here — TASK-930 §3 had split the two planes, giving the unbound one service-account scopes
   * and withholding them from the consultation-bound one, on the reasoning that running a
   * workflow which writes into a clinical record is not a machine-identity power.
   *
   * The owner reversed that on 2026-09-09 (TASK-933 OQ-2, "all permissions for vox-node to
   * handle realtime consultation"): `CONSULTATION_REALTIME_SCOPE_SOURCES` declares
   * `svc:workflows:execute` on this plane, and the SDK's `ConsultationWorkflowsResource`
   * overrode its `assertCredentialClass()` to a no-op to match. So the assertion is INVERTED,
   * not deleted: the grant is now the thing that must not regress silently.
   *
   * The scope stays outside the `svc:workflow:` prefix for the same reason its API-key twin
   * does — a credential holding the unbound run scopes must not inherit the clinical plane.
   */
  it.each(CONSULTATION_ROUTES)('$method $path is service-account-REACHABLE', ({ method, path }) => {
    expect(find(method, path)!.svcScopes ?? []).toEqual(['svc:workflows:execute']);
  });

  it.each(UNBOUND_ROUTES.filter((r) => !PENDING_GATEWAY_ROUTES.has(`${r.method} ${r.path}`)))(
    '$method $path declares a service-account scope',
    ({ method, path }) => {
      if (MANIFEST_PREDATES_TASK930) {
        expect(find(method, path)!.svcScopes ?? []).toEqual([]);
        return;
      }
      expect(find(method, path)!.svcScopes?.length ?? 0).toBeGreaterThan(0);
    },
  );

  it('pins the scope each plane requires', () => {
    expect(find('POST', '/api/v1/workflows/{slug}/runs')!.apiKeyScopes).toEqual(['workflow:run:write']);
    expect(find('GET', '/api/v1/workflows')!.apiKeyScopes).toEqual(['workflow:definition:read']);
    // TASK-890: `schema()` reads the DEFINITION, so it takes the definition-read scope — not a
    // run scope. A key that may start runs is not thereby entitled to read what a graph declares.
    expect(find('GET', '/api/v1/workflows/{slug}/schema')!.apiKeyScopes).toEqual(['workflow:definition:read']);
    expect(find('GET', '/api/v1/workflows/{slug}/runs/{runId}/stream')!.apiKeyScopes).toEqual(['workflow:run:read']);
    // The consultation plane's scope is deliberately OUTSIDE the `workflow:` prefix,
    // so a key holding bare `workflow` cannot inherit the clinical-write plane.
    expect(find('POST', '/api/v1/consultations/{consultationId}/workflows/{slug}/runs')!.apiKeyScopes).toEqual(['workflows:execute']);
    expect(find('GET', '/api/v1/consultations/{consultationId}/workflows')!.apiKeyScopes).toEqual(['workflows:execute']);
  });

  it('pins the ability each plane requires — "may run" and "may run against a consultation" are different powers', () => {
    expect(find('POST', '/api/v1/workflows/{slug}/runs')!.requiredPermissions).toEqual([['create', 'WorkflowRun']]);
    expect(find('POST', '/api/v1/consultations/{consultationId}/workflows/{slug}/runs')!.requiredPermissions).toEqual([
      ['execute', 'ConsultationWorkflow'],
    ]);
  });

  it('none of these routes is public — the SDK always sends a credential', () => {
    for (const { method, path } of WORKFLOW_PLANE_ROUTES) {
      if (PENDING_GATEWAY_ROUTES.has(`${method} ${path}`)) continue;
      expect(find(method, path)!.isPublic).toBe(false);
    }
  });
});

describe("the SDK's reserved-key list is the gateway's list", () => {
  it('matches exposure-palette-policy.ts verbatim', () => {
    const source = readFileSync(
      join(REPO_ROOT, 'packages', 'applications', 'src', 'services', 'workflow-exposure', 'exposure-palette-policy.ts'),
      'utf8',
    );
    const match = /RESERVED_RUN_IDENTITY_KEYS: readonly string\[\] = Object\.freeze\(\[([^\]]*)\]\)/.exec(source);
    expect(match, 'RESERVED_RUN_IDENTITY_KEYS not found in exposure-palette-policy.ts').toBeTruthy();
    const gatewayKeys = [...match![1]!.matchAll(/'([^']+)'/g)].map((m) => m[1]);
    expect([...RESERVED_RUN_IDENTITY_KEYS]).toEqual(gatewayKeys);
  });
});
