/**
 * AUTO-GENERATED by @arcaai/vox-codegen — DO NOT EDIT BY HAND.
 *
 * Tenant: 50000000-0000-0000-0000-000000000001
 * Schema: arcaai_consultation_scribe v3 (01a0ab13-8d38-7b4e-86e6-4a0a15e0dd66)
 * Generated: 2026-09-16T16:37:06.731Z
 *
 * This file is a BUILD-TIME CONVENIENCE, never a replacement for runtime
 * discovery. `useConsultationSchema()` (`@arcaai/vox`) remains the wire
 * contract: a tenant can publish a new kind, or change an existing one,
 * between two runs of this generator, and this file will not know until
 * regenerated. Never gate application logic on these types alone —
 * validate against the live discovery bundle at the boundary where a
 * payload is actually submitted (`useArcaSession().addContext()` already
 * does this).
 *
 * Regenerate: npx @arcaai/vox-codegen --tenant <tenantId> [--watch]
 */

// ---- Context kinds ----

// `audio_stream` — primitive "STREAM_AUDIO", no structured payload to type.

// `work_note` — primitive "TEXT", no structured payload to type.

// `case_note` — primitive "TEXT", no structured payload to type.

// `attachment` — primitive "DOCUMENT", no structured payload to type.

/** `encounter` — Encounter */
export type EncounterPayload = { /** @role externalRef — an external system's own identifier for this encounter, persisted on the consultation's metadata (TASK-951). */ event_id: string; /** @identity — the clinician's staff identifier; a service-account caller's `open()` resolves or provisions the HOPE user from it (TASK-950). */ doctor_id: string; /** @role visitType — matched through the platform's visit-type catalogue and recorded on the consultation, taking precedence over the parent-consultation-derived signal (TASK-951). */ visit_type: ("new-visit" | "revisit"); chief_complaint?: string; /** @role department (by code) — selects the consultation's department, resolved against the tenant's own departments (TASK-951). */ department_code: string; department_name?: string; };

/** `vitals` — Vitals */
export type VitalsPayload = { bmi?: number; notes?: string; heightCm?: number; weightKg?: number; heartRate?: number; painScore?: number; recordedAt?: string; temperature?: number; bloodGlucose?: number; bloodPressure?: string; respiratoryRate?: number; oxygenSaturation?: number; };

/**
 * `previous_case_notes` — Previous Case Notes
 * @materializeAs CASE_NOTE — every array entry of this payload is ALSO written as one CASE_NOTE context item at open() (TASK-951).
 */
export type PreviousCaseNotesPayload = { notes: ({ date?: string; text: string; title?: string; doctor?: string; department?: string; })[]; };

/** `context` — Consultation Prompt Context */
export type ContextPayload = { language: string; safe_age: string; safe_dob: string; visit_type: ("new-visit" | "revisit"); attachments?: string; safe_gender: string; safe_vitals?: string; ner_entities?: string; language_name?: string; dna_style_text?: string; chief_complaint?: string; clinician_notes?: string; formatted_vitals: string; pre_summary_text?: string; doctor_highlights?: string; current_department: string; prior_visit_summary?: string; conversation_language?: string; formatted_test_results?: string; formatted_previous_visits: string; style_DNA_doctor_department_surgery?: string; style_DNA_doctor_department_medicine?: string; style_DNA_doctor_department_dietetics?: string; style_DNA_doctor_department_neurology?: string; style_DNA_doctor_department_hematology?: string; style_DNA_doctor_department_nephrology?: string; style_DNA_doctor_department_dermatology?: string; style_DNA_doctor_department_orthopedics?: string; style_DNA_doctor_department_rheumatology?: string; style_DNA_doctor_department_breast_endocrine?: string; style_DNA_doctor_department_surgical_oncology?: string; };

/** `referral` — Referral */
export type ReferralPayload = { reason: string; referred_by?: string; };

export interface ConsultationContextKindMap {
  encounter: EncounterPayload;
  vitals: VitalsPayload;
  previous_case_notes: PreviousCaseNotesPayload;
  context: ContextPayload;
  referral: ReferralPayload;
}
export type ConsultationContextKindKey = keyof ConsultationContextKindMap;

// ---- Outputs ----

// `case_note` — primitive "TEXT", no structured payload to type.

// `soap_note` — primitive "TEXT", no structured payload to type.

export type ConsultationContextOutputMap = Record<string, never>;
export type ConsultationContextOutputKey = keyof ConsultationContextOutputMap;
