apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: hope-v2/api
    newName: registry.taphuynh.dev/arca/hope-v2/api
  - name: hope-v2/admin-console
    newName: registry.taphuynh.dev/arca/hope-v2/admin-console
  - name: hope-v2/smr
    newName: registry.taphuynh.dev/arca/hope-v2/smr
  - name: hope-v2/stt-v2-ml-runtime
    newName: registry.taphuynh.dev/arca/hope-v2/stt-v2-ml-runtime
  - name: hope-v2/stt-v2-worker
    newName: registry.taphuynh.dev/arca/hope-v2/stt-v2-worker
  - name: hope-v2/database
    newName: registry.taphuynh.dev/arca/hope-v2/database

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: hope-registry-creds
  - target:
      kind: Job
    patch: |
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: hope-registry-creds
