-- Institutional-RAG knowledge document audit resource type (TASK-728).
--
-- Additive only: no existing table or column is touched. KnowledgeDocument /
-- KnowledgeChunk already exist (TASK-330 phase 3); this only registers the
-- head row as an audited ResourceType so KnowledgeDocumentService's upgraded
-- sys-event broadcasts (create/approve/archive/delete/viewed) can persist an
-- AuditLog row instead of throwing on INSERT
-- (resourceType.enum-parity.test.ts is the guard). Safe inside the migration
-- transaction (PostgreSQL >= 12 allows ADD VALUE in a transaction block
-- provided the new value is not USED in the same transaction — nothing below
-- writes it).
ALTER TYPE "core"."ResourceType" ADD VALUE IF NOT EXISTS 'KnowledgeDocument';
