/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminListOptions, AdminListQuery, AdminRequestOptions, PaginatedPage } from './admin-resource';
import type { AgentPromotionResponse, PromoteAgentRequest } from './schemas';

/**
 * `hope.admin.agentPromotion` — the `svc:admin:agent-promotion:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:agent-promotion:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller AgentPromotionController
 * (3 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminAgentPromotionResource extends AdminResource {
  readonly svcScope = 'svc:admin:agent-promotion:manage';

  /**
   * List promotions INTO the working tenant
   *
   * The target tenant’s own agent lineage. Each row reports `drifted` — whether the target agent has been edited since it was promoted into.
   *
   * `GET /api/v1/admin/agent-promotions` — `AgentPromotionController.list`.
   *
   * Returns ONE page. `page` is 0-based and both `page` and `limit` are always sent explicitly — the gateway echoes RAW query values back, so the response's own `page`/`limit` are not usable as loop state. Use {@link listIterate} to walk every page.
   */
  list(options: AdminListOptions & { query?: AdminListQuery & { targetAgentId?: string } } = {}): Promise<PaginatedPage<AgentPromotionResponse>> {
    return this.listPage<AgentPromotionResponse>('admin/agent-promotions', options);
  }

  /**
   * List promotions INTO the working tenant
   *
   * The target tenant’s own agent lineage. Each row reports `drifted` — whether the target agent has been edited since it was promoted into.
   *
   * `GET /api/v1/admin/agent-promotions` — `AgentPromotionController.list`.
   *
   * Walks every page, yielding rows: `for await (const row of …)`. Pagination is driven from the REQUEST side; a failure on page N propagates after page N-1's rows, so "the list ended" and "the list broke" never look alike.
   */
  listIterate(
    options: AdminListOptions & { query?: AdminListQuery & { targetAgentId?: string } } = {},
  ): AsyncGenerator<AgentPromotionResponse, void, undefined> {
    return this.listAll<AgentPromotionResponse>('admin/agent-promotions', options);
  }

  /**
   * Promote an agent configuration version from one tenant to another
   *
   * Copies the exact immutable DepartmentAgentVersion of a source-tenant agent into the target tenant, creating the target agent or advancing an existing one with the same slug. Requires manage rights on BOTH tenants and an elevated tenant-less context. Bound prompt templates are deep-copied into the target; the golden set is NOT — the eval re-runs at the target against the target’s own corpus, and no GoldenCase (nor the pointer to one) crosses a tenant boundary. Blocked when the target department does not declare a context kind the promoted agent subscribes to. Live consultations on the target are reported as a warning, never a block.
   *
   * `POST /api/v1/admin/agent-promotions` — `AgentPromotionController.promote`.
   */
  promote(body: PromoteAgentRequest, options: AdminRequestOptions = {}): Promise<AgentPromotionResponse> {
    return this.request<AgentPromotionResponse>({
      method: 'POST',
      path: 'admin/agent-promotions',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get one promotion record
   *
   * `GET /api/v1/admin/agent-promotions/{id}` — `AgentPromotionController.getById`.
   */
  getById(id: string, options: AdminRequestOptions = {}): Promise<AgentPromotionResponse> {
    return this.request<AgentPromotionResponse>({
      method: 'GET',
      path: `admin/agent-promotions/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
