/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import type { QueryValue } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions } from './admin-resource';
import type { AgenticInstructionsResponse } from './schemas';

/**
 * `hope.admin.agentic` — the `svc:admin:agentic:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:agentic:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller AgenticAdminController
 * (1 route). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminAgenticResource extends AdminResource {
  readonly svcScope = 'svc:admin:agentic:manage';

  /**
   * The effective agentic instruction set for a tenant (prompt tier, judge pin, thresholds, safety criteria)
   *
   * Read-only aggregate over the effective harness policy (sensor thresholds + safety), the prompt-resolution cascade (tier), and the vendored PDSQI judge-prompt pin (version/hash only — non-editable by license/science). Tenant admins are pinned to their own tenant; a foreign `?tenantId=` is 404.
   *
   * `GET /api/v1/admin/agentic/instructions` — `AgenticAdminController.getInstructions`.
   */
  getInstructions(
    options: AdminRequestOptions & {
      query?: { departmentId?: QueryValue; promptType?: 'pre-summary' | 'new-patient' | 'revisit'; tenantId?: QueryValue };
    } = {},
  ): Promise<AgenticInstructionsResponse> {
    return this.request<AgenticInstructionsResponse>({
      method: 'GET',
      path: 'admin/agentic/instructions',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
