/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions, IfMatchPrecondition } from './admin-resource';
import type {
  CreateModelRequest,
  DiscoveryResponse,
  ModelCatalogueResponse,
  ModelDownloadStatusResponse,
  ModelInventoryReport,
  ModelResponse,
  PaginatedModelResponse,
  PaginatedResponse,
  RegisterDiscoveredModelRequest,
  SetPlatformDefaultRequest,
  TriggerModelDownloadResponse,
  UpdateModelRequest,
} from './schemas';

/**
 * `hope.admin.aiModel` — the `svc:admin:ai-model:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:ai-model:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * 1 of its route ALSO accepts `svc:admin:ai-model:read`, so a read-only grant reaches
 * it and nothing else here. Those methods name their own accepted scopes in a 403;
 * the scope above is the one that reaches EVERY route.
 *
 * Backed by controllers AiModelAdminController, AiModelCatalogueController, AiModelDiscoveryController
 * (14 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminAiModelResource extends AdminResource {
  readonly svcScope = 'svc:admin:ai-model:manage';

  /**
   * Retrieving multiple ModelResponses
   *
   * `GET /api/v1/admin/ai-models` — `AiModelAdminController.fetchAll`.
   */
  fetchAll(options: AdminRequestOptions = {}): Promise<PaginatedResponse & { data?: ModelResponse[] }> {
    return this.request<PaginatedResponse & { data?: ModelResponse[] }>({
      method: 'GET',
      path: 'admin/ai-models',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Creating a ModelResponse
   *
   * `POST /api/v1/admin/ai-models` — `AiModelAdminController.create`.
   */
  create(body: CreateModelRequest, options: AdminRequestOptions = {}): Promise<ModelResponse> {
    return this.request<ModelResponse>({
      method: 'POST',
      path: 'admin/ai-models',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Deleting a ModelResponse by id
   *
   * `DELETE /api/v1/admin/ai-models/{id}` — `AiModelAdminController.delete`.
   */
  delete(id: string, options: AdminRequestOptions = {}): Promise<ModelResponse> {
    return this.request<ModelResponse>({
      method: 'DELETE',
      path: `admin/ai-models/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single ModelResponse by id
   *
   * `GET /api/v1/admin/ai-models/{id}` — `AiModelAdminController.fetchById`.
   */
  fetchById(id: string, options: AdminRequestOptions = {}): Promise<ModelResponse> {
    return this.request<ModelResponse>({
      method: 'GET',
      path: `admin/ai-models/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Updating a ModelResponse by id
   *
   * Updates one AiModel row. Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED, and the server runs a Compare-And-Set against the row's `_version` column. When the header is present, its value overrides the body-field `expectedVersion`. On version drift the response is `412 Precondition Failed`; a missing header is `428 Precondition Required`.
   *
   * `PATCH /api/v1/admin/ai-models/{id}` — `AiModelAdminController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  update(id: string, body: UpdateModelRequest, options: AdminRequestOptions & { ifMatch: IfMatchPrecondition }): Promise<ModelResponse> {
    return this.requestWithPrecondition<ModelResponse>({
      method: 'PATCH',
      path: `admin/ai-models/${encodePathSegment(String(id))}`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Poll the status of the most recent download job for this model.
   *
   * `GET /api/v1/admin/ai-models/{id}/download` — `AiModelAdminController.getDownloadStatus`.
   */
  getDownloadStatus(id: string, options: AdminRequestOptions = {}): Promise<ModelDownloadStatusResponse> {
    return this.request<ModelDownloadStatusResponse>({
      method: 'GET',
      path: `admin/ai-models/${encodePathSegment(String(id))}/download`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Publish this model's weights into the hope-models bucket (async).
   *
   * Fetches the weights from `sourceUri` (Hub or s3://), verifies + content-addresses them, publishes them under `<slug>/<version>/` (or as a verbatim HF cache for the transformers family), and writes `bucketPrefix` / `manifestDigest` / `availability` back to the row. The route path keeps its frozen `download` name; the action is the registry's single publisher (TASK-860 D-1).
   *
   * `POST /api/v1/admin/ai-models/{id}/download` — `AiModelAdminController.triggerDownload`.
   */
  triggerDownload(id: string, options: AdminRequestOptions = {}): Promise<TriggerModelDownloadResponse> {
    return this.request<TriggerModelDownloadResponse>({
      method: 'POST',
      path: `admin/ai-models/${encodePathSegment(String(id))}/download`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Elect this row as the platform default for one or more tasks
   *
   * Replaces the row's `isPlatformDefaultFor` with `tasks` and clears each of those tasks from whichever ENABLED row held it, so a task never has two platform defaults. An empty list withdraws the row from every election. Only writes the registry column and emits a sys-event; the SYSTEM routing-policy election it seeds is TASK-862.
   *
   * `PATCH /api/v1/admin/ai-models/{id}/platform-default` — `AiModelAdminController.setPlatformDefault`.
   */
  setPlatformDefault(id: string, body: SetPlatformDefaultRequest, options: AdminRequestOptions = {}): Promise<ModelResponse> {
    return this.request<ModelResponse>({
      method: 'PATCH',
      path: `admin/ai-models/${encodePathSegment(String(id))}/platform-default`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * The model catalogue this tenant may bind, in picker order
   *
   * Two groups: the tenant’s OWN provider connections first (`byo:<service>:<provider>`), then exactly one "Hope provider" entry standing for everything the platform serves. Each model carries a `usable` verdict with a machine-readable reason (an unusable model is listed WITH its reason rather than hidden) and the last OBSERVED `readiness` — a stored snapshot, never a probe: reading this route never causes a vendor call. Plan entitlements BOUND the Hope group; they never add or substitute a model. Rows naming no servable provider are hidden, and counted in `unassignedProviderCount` for a super admin.
   *
   * `GET /api/v1/admin/ai-models/catalogue` — `AiModelCatalogueController.catalogue`.
   *
   * Reachable with ANY ONE of `svc:admin:ai-model:manage`, `svc:admin:ai-model:read` — the gateway matches required scopes with OR, so the area's `svc:admin:ai-model:manage` still reaches this route and a read-only grant now does too.
   */
  catalogue(
    options: AdminRequestOptions & {
      query?: {
        providerGroup?: 'byo' | 'hope';
        taskType?:
          | 'IMAGE_TEXT_TO_TEXT'
          | 'VISUAL_QUESTION_ANSWERING'
          | 'DOCUMENT_QUESTION_ANSWERING'
          | 'VIDEO_TEXT_TO_TEXT'
          | 'ANY_TO_ANY'
          | 'DEPTH_ESTIMATION'
          | 'IMAGE_CLASSIFICATION'
          | 'OBJECT_DETECTION'
          | 'IMAGE_SEGMENTATION'
          | 'TEXT_TO_IMAGE'
          | 'IMAGE_TO_TEXT'
          | 'IMAGE_TO_IMAGE'
          | 'IMAGE_TO_VIDEO'
          | 'UNCONDITIONAL_IMAGE_GENERATION'
          | 'VIDEO_CLASSIFICATION'
          | 'TEXT_TO_VIDEO'
          | 'ZERO_SHOT_IMAGE_CLASSIFICATION'
          | 'MASK_GENERATION'
          | 'ZERO_SHOT_OBJECT_DETECTION'
          | 'TEXT_TO_3D'
          | 'IMAGE_TO_3D'
          | 'IMAGE_FEATURE_EXTRACTION'
          | 'KEYPOINT_DETECTION'
          | 'TEXT_CLASSIFICATION'
          | 'TOKEN_CLASSIFICATION'
          | 'TABLE_QUESTION_ANSWERING'
          | 'QUESTION_ANSWERING'
          | 'ZERO_SHOT_CLASSIFICATION'
          | 'TRANSLATION'
          | 'SUMMARIZATION'
          | 'FEATURE_EXTRACTION'
          | 'TEXT_GENERATION'
          | 'TEXT2TEXT_GENERATION'
          | 'FILL_MASK'
          | 'SENTENCE_SIMILARITY'
          | 'GUARDRAIL'
          | 'TEXT_TO_SPEECH'
          | 'TEXT_TO_AUDIO'
          | 'AUTOMATIC_SPEECH_RECOGNITION'
          | 'AUDIO_TO_AUDIO'
          | 'AUDIO_CLASSIFICATION'
          | 'VOICE_ACTIVITY_DETECTION'
          | 'SPEAKER_DIARIZATION'
          | 'SPEAKER_EMBEDDING'
          | 'TABULAR_CLASSIFICATION'
          | 'TABULAR_REGRESSION'
          | 'TIME_SERIES_FORECASTING'
          | 'UNKNOWN';
        usableOnly?: boolean;
      };
    } = {},
  ): Promise<ModelCatalogueResponse> {
    return this.request<ModelCatalogueResponse>({
      method: 'GET',
      path: 'admin/ai-models/catalogue',
      query: options.query,
      svcScopes: ['svc:admin:ai-model:manage', 'svc:admin:ai-model:read'],
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Merge the AI model registry with the live engine listings
   *
   * Returns every server-managed model known to either side, each tagged `registered`, `discovered` or `registered-missing-on-server`, plus per-provider probe outcomes and the probe timestamp. A provider whose probe did not succeed degrades its registry rows to `registered`/`unknown` — never to a false "missing".
   *
   * `GET /api/v1/admin/ai-models/discovery` — `AiModelDiscoveryController.discover`.
   */
  discover(options: AdminRequestOptions & { query?: { provider?: string } } = {}): Promise<DiscoveryResponse> {
    return this.request<DiscoveryResponse>({
      method: 'GET',
      path: 'admin/ai-models/discovery',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * DEPRECATED (TASK-860, removed in R3) — register a discovered model
   *
   * Refuses with `410 Gone`. Discovery is read-only since TASK-860; register a model through `POST admin/ai-models` (the inventory report lists prefixes already in the bucket, which register with their `bucketPrefix`).
   *
   * `POST /api/v1/admin/ai-models/discovery/register` — `AiModelDiscoveryController.register`.
   */
  register(body: RegisterDiscoveredModelRequest, options: AdminRequestOptions = {}): Promise<unknown> {
    return this.request<unknown>({
      method: 'POST',
      path: 'admin/ai-models/discovery/register',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Run the model-bucket inventory
   *
   * Verifies every registry row's `bucketPrefix` + `manifestDigest` + manifest objects against `s3://hope-models`, writes the measured `availability` (AVAILABLE / MISSING / PARTIAL / NOT_APPLICABLE) back, and lists the prefixes in the bucket that no row references ("In bucket, not registered → Register"). The same sweep runs hourly when `modelRegistry.inventory.enabled` is on.
   *
   * `POST /api/v1/admin/ai-models/inventory` — `AiModelAdminController.runInventory`.
   */
  runInventory(options: AdminRequestOptions = {}): Promise<ModelInventoryReport> {
    return this.request<ModelInventoryReport>({
      method: 'POST',
      path: 'admin/ai-models/inventory',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single PaginatedModelResponse
   *
   * `GET /api/v1/admin/ai-models/list` — `AiModelAdminController.list`.
   */
  list(options: AdminRequestOptions & { query?: { limit?: number; page?: number } } = {}): Promise<PaginatedModelResponse> {
    return this.request<PaginatedModelResponse>({
      method: 'GET',
      path: 'admin/ai-models/list',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single ModelResponse by slug
   *
   * `GET /api/v1/admin/ai-models/slug/{slug}` — `AiModelAdminController.fetchBySlug`.
   */
  fetchBySlug(slug: string, options: AdminRequestOptions = {}): Promise<ModelResponse> {
    return this.request<ModelResponse>({
      method: 'GET',
      path: `admin/ai-models/slug/${encodePathSegment(String(slug))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
