/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions, IfMatchPrecondition } from './admin-resource';
import type {
  CreateModelRequest,
  DiscoveryResponse,
  ModelDownloadStatusResponse,
  ModelResponse,
  PaginatedModelResponse,
  PaginatedResponse,
  RegisterDiscoveredModelRequest,
  TriggerModelDownloadResponse,
  UpdateModelRequest,
} from './schemas';

/**
 * `hope.admin.aiModel` — the `svc:admin:ai-model:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:ai-model:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controllers AiModelAdminController, AiModelDiscoveryController
 * (11 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminAiModelResource extends AdminResource {
  readonly svcScope = 'svc:admin:ai-model:manage';

  /**
   * Retrieving multiple ModelResponses
   *
   * `GET /api/v1/admin/ai-models` — `AiModelAdminController.fetchAll`.
   */
  fetchAll(options: AdminRequestOptions = {}): Promise<PaginatedResponse & { data?: ModelResponse[] }> {
    return this.request<PaginatedResponse & { data?: ModelResponse[] }>({
      method: 'GET',
      path: 'admin/ai-models',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Creating a ModelResponse
   *
   * `POST /api/v1/admin/ai-models` — `AiModelAdminController.create`.
   */
  create(body: CreateModelRequest, options: AdminRequestOptions = {}): Promise<ModelResponse> {
    return this.request<ModelResponse>({
      method: 'POST',
      path: 'admin/ai-models',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Deleting a ModelResponse by id
   *
   * `DELETE /api/v1/admin/ai-models/{id}` — `AiModelAdminController.delete`.
   */
  delete(id: string, options: AdminRequestOptions = {}): Promise<ModelResponse> {
    return this.request<ModelResponse>({
      method: 'DELETE',
      path: `admin/ai-models/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single ModelResponse by id
   *
   * `GET /api/v1/admin/ai-models/{id}` — `AiModelAdminController.fetchById`.
   */
  fetchById(id: string, options: AdminRequestOptions = {}): Promise<ModelResponse> {
    return this.request<ModelResponse>({
      method: 'GET',
      path: `admin/ai-models/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Updating a ModelResponse by id
   *
   * Updates one AiModel row. Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED, and the server runs a Compare-And-Set against the row's `_version` column. When the header is present, its value overrides the body-field `expectedVersion`. On version drift the response is `412 Precondition Failed`; a missing header is `428 Precondition Required`.
   *
   * `PATCH /api/v1/admin/ai-models/{id}` — `AiModelAdminController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  update(id: string, body: UpdateModelRequest, options: AdminRequestOptions & { ifMatch: IfMatchPrecondition }): Promise<ModelResponse> {
    return this.requestWithPrecondition<ModelResponse>({
      method: 'PATCH',
      path: `admin/ai-models/${encodePathSegment(String(id))}`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Poll the status of the most recent download job for this model.
   *
   * `GET /api/v1/admin/ai-models/{id}/download` — `AiModelAdminController.getDownloadStatus`.
   */
  getDownloadStatus(id: string, options: AdminRequestOptions = {}): Promise<ModelDownloadStatusResponse> {
    return this.request<ModelDownloadStatusResponse>({
      method: 'GET',
      path: `admin/ai-models/${encodePathSegment(String(id))}/download`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Trigger an async download of this model's weights into the hope-models bucket.
   *
   * `POST /api/v1/admin/ai-models/{id}/download` — `AiModelAdminController.triggerDownload`.
   */
  triggerDownload(id: string, options: AdminRequestOptions = {}): Promise<TriggerModelDownloadResponse> {
    return this.request<TriggerModelDownloadResponse>({
      method: 'POST',
      path: `admin/ai-models/${encodePathSegment(String(id))}/download`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Merge the AI model registry with the live engine listings
   *
   * Returns every server-managed model known to either side, each tagged `registered`, `discovered` or `registered-missing-on-server`, plus per-provider probe outcomes and the probe timestamp. A provider whose probe did not succeed degrades its registry rows to `registered`/`unknown` — never to a false "missing".
   *
   * `GET /api/v1/admin/ai-models/discovery` — `AiModelDiscoveryController.discover`.
   */
  discover(options: AdminRequestOptions & { query?: { provider?: string } } = {}): Promise<DiscoveryResponse> {
    return this.request<DiscoveryResponse>({
      method: 'GET',
      path: 'admin/ai-models/discovery',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Register a discovered model into the AI model registry
   *
   * Creates one `AiModel` row from a discovered entry (slug derived from the engine-reported model name). Delegates to the existing create path, so the factory, the `ResourceCreated` sys-event and the slug-uniqueness check all apply. On a slug collision the response is 400 asking for an explicit `slug` — there is no silent suffixing.
   *
   * `POST /api/v1/admin/ai-models/discovery/register` — `AiModelDiscoveryController.register`.
   */
  register(body: RegisterDiscoveredModelRequest, options: AdminRequestOptions = {}): Promise<ModelResponse> {
    return this.request<ModelResponse>({
      method: 'POST',
      path: 'admin/ai-models/discovery/register',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single PaginatedModelResponse
   *
   * `GET /api/v1/admin/ai-models/list` — `AiModelAdminController.list`.
   */
  list(options: AdminRequestOptions & { query?: { limit?: number; page?: number } } = {}): Promise<PaginatedModelResponse> {
    return this.request<PaginatedModelResponse>({
      method: 'GET',
      path: 'admin/ai-models/list',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single ModelResponse by slug
   *
   * `GET /api/v1/admin/ai-models/slug/{slug}` — `AiModelAdminController.fetchBySlug`.
   */
  fetchBySlug(slug: string, options: AdminRequestOptions = {}): Promise<ModelResponse> {
    return this.request<ModelResponse>({
      method: 'GET',
      path: `admin/ai-models/slug/${encodePathSegment(String(slug))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
