/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions, IfMatchPrecondition } from './admin-resource';
import type {
  AiProviderConnectionResponse,
  TestProviderConnectionRequest,
  TestProviderConnectionResponse,
  UpsertAiProviderConnectionRequest,
} from './schemas';

/**
 * `hope.admin.aiProvider` — the `svc:admin:ai-provider:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:ai-provider:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller ProviderConnectionController
 * (5 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminAiProviderResource extends AdminResource {
  readonly svcScope = 'svc:admin:ai-provider:manage';

  /**
   * List provider connections for one service and the scoped tenant (keys never returned).
   *
   * `GET /api/v1/admin/providers/{service}` — `ProviderConnectionController.list`.
   */
  list(service: string, options: AdminRequestOptions & { query?: { tenantId?: string } } = {}): Promise<AiProviderConnectionResponse[]> {
    return this.request<AiProviderConnectionResponse[]>({
      method: 'GET',
      path: `admin/providers/${encodePathSegment(String(service))}`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Soft-delete one provider connection.
   *
   * Deleting returns this (service, provider) to "no opinion", so the platform-provided credential may serve it again (subject to the platform-default entitlement). To BLOCK the provider instead — including the platform-provided key — keep the row and set `enabled: false`, which is a veto.
   *
   * `DELETE /api/v1/admin/providers/{service}/{provider}` — `ProviderConnectionController.remove`.
   */
  remove(service: string, provider: string, options: AdminRequestOptions & { query?: { tenantId?: string } } = {}): Promise<unknown> {
    return this.request<unknown>({
      method: 'DELETE',
      path: `admin/providers/${encodePathSegment(String(service))}/${encodePathSegment(String(provider))}`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Read one provider connection (key never returned; placeholder when absent).
   *
   * `GET /api/v1/admin/providers/{service}/{provider}` — `ProviderConnectionController.getOne`.
   */
  getOne(
    service: string,
    provider: string,
    options: AdminRequestOptions & { query?: { tenantId?: string } } = {},
  ): Promise<AiProviderConnectionResponse> {
    return this.request<AiProviderConnectionResponse>({
      method: 'GET',
      path: `admin/providers/${encodePathSegment(String(service))}/${encodePathSegment(String(provider))}`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Create or update one provider connection.
   *
   * Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED and the server runs a Compare-And-Set against the row's `_version`. When present the header overrides the body-field `expectedVersion`. Version drift → `412`; missing header → `428`. Use `expectedVersion: 0` to create. A supplied `apiKey` is Vault-Transit encrypted and never returned; omitting it leaves the stored key intact. **`enabled` is three-state.** Three states, per (service, provider): NO ROW = no opinion, so the platform-provided credential may serve this provider (subject to the tenant holding the platform-default entitlement). ENABLED with a key = your own credential serves it. DISABLED = a VETO: this provider is blocked for your tenant entirely, INCLUDING the platform-provided key, and the call fails rather than falling through to another provider. Disabling is how a tenant refuses a shared vendor account; deleting the row instead returns it to "no opinion".
   *
   * `PUT /api/v1/admin/providers/{service}/{provider}` — `ProviderConnectionController.upsert`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  upsert(
    service: string,
    provider: string,
    body: UpsertAiProviderConnectionRequest,
    options: AdminRequestOptions & { query?: { tenantId?: string } } & { ifMatch: IfMatchPrecondition },
  ): Promise<AiProviderConnectionResponse> {
    return this.requestWithPrecondition<AiProviderConnectionResponse>({
      method: 'PUT',
      path: `admin/providers/${encodePathSegment(String(service))}/${encodePathSegment(String(provider))}`,
      query: options.query,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Test a provider connection against the live vendor (ephemeral — never persisted).
   *
   * Probes the credential/endpoint BEFORE (or independent of) saving it. Every body field is optional: an omitted field falls back to the STORED row (the tenant row, else the SYSTEM platform default), so a saved write-only key can be re-tested without re-entering it. A real auth-only call where the vendor exposes one (`probe: "auth"`), a reachability smoke test otherwise (`probe: "reachability"`). No Vault write, no OCC, the key is never logged. Tenant-supplied URLs must be https and public.
   *
   * `POST /api/v1/admin/providers/{service}/{provider}/test` — `ProviderConnectionController.testConnection`.
   */
  testConnection(
    service: string,
    provider: string,
    body: TestProviderConnectionRequest,
    options: AdminRequestOptions & { query?: { tenantId?: string } } = {},
  ): Promise<TestProviderConnectionResponse> {
    return this.request<TestProviderConnectionResponse>({
      method: 'POST',
      path: `admin/providers/${encodePathSegment(String(service))}/${encodePathSegment(String(provider))}/test`,
      query: options.query,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
