/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { AdminResource } from './admin-resource';
import type { AdminRequestOptions, IfMatchPrecondition } from './admin-resource';
import type { AiRuntimeProfileResponse, UpsertAiRuntimeProfileRequest } from './schemas';

/**
 * `hope.admin.aiRuntimeProfile` — the `svc:admin:ai-runtime-profile:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:ai-runtime-profile:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller AiRuntimeProfileController
 * (5 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminAiRuntimeProfileResource extends AdminResource {
  readonly svcScope = 'svc:admin:ai-runtime-profile:manage';

  /**
   * List every platform runtime profile.
   *
   * `GET /api/v1/admin/ai-runtime-profiles` — `AiRuntimeProfileController.list`.
   */
  list(options: AdminRequestOptions = {}): Promise<AiRuntimeProfileResponse[]> {
    return this.request<AiRuntimeProfileResponse[]>({
      method: 'GET',
      path: 'admin/ai-runtime-profiles',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Resolve the effective runtime profile for a (provider, modelSlug).
   *
   * Shows the per-field merge of the model-scoped row over the provider-level default — exactly what the gateway would inject. `isEmpty: true` means nothing is injected and the consuming service keeps its own env/pydantic defaults.
   *
   * `GET /api/v1/admin/ai-runtime-profiles/resolve` — `AiRuntimeProfileController.resolve`.
   */
  resolve(options: AdminRequestOptions & { query?: { modelSlug?: string; provider: string } } = {}): Promise<unknown> {
    return this.request<unknown>({
      method: 'GET',
      path: 'admin/ai-runtime-profiles/resolve',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Soft-delete one runtime profile row.
   *
   * `DELETE /api/v1/admin/ai-runtime-profiles/row` — `AiRuntimeProfileController.remove`.
   */
  remove(options: AdminRequestOptions & { query?: { modelSlug?: string; provider: string } } = {}): Promise<unknown> {
    return this.request<unknown>({
      method: 'DELETE',
      path: 'admin/ai-runtime-profiles/row',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Read one runtime profile row (placeholder when absent).
   *
   * `GET /api/v1/admin/ai-runtime-profiles/row` — `AiRuntimeProfileController.getRow`.
   */
  getRow(options: AdminRequestOptions & { query?: { modelSlug?: string; provider: string } } = {}): Promise<AiRuntimeProfileResponse> {
    return this.request<AiRuntimeProfileResponse>({
      method: 'GET',
      path: 'admin/ai-runtime-profiles/row',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Create or update one runtime profile row.
   *
   * Optimistic concurrency is enforced: `If-Match` (RFC 7232) is REQUIRED and the server runs a Compare-And-Set against the row's `_version`. The header overrides the body-field `expectedVersion`. Drift → `412`; missing header → `428`. Use `expectedVersion: 0` to create. Every knob is optional — omitting one leaves it unchanged, sending `null` clears it back to "no opinion" so the cascade falls through.
   *
   * `PUT /api/v1/admin/ai-runtime-profiles/row` — `AiRuntimeProfileController.upsert`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  upsert(
    body: UpsertAiRuntimeProfileRequest,
    options: AdminRequestOptions & { query?: { modelSlug?: string; provider: string } } & { ifMatch: IfMatchPrecondition },
  ): Promise<AiRuntimeProfileResponse> {
    return this.requestWithPrecondition<AiRuntimeProfileResponse>({
      method: 'PUT',
      path: 'admin/ai-runtime-profiles/row',
      query: options.query,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
