/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { AdminResource } from './admin-resource';
import type { AdminRequestOptions } from './admin-resource';
import type { InferenceReadinessResponse, MlflowStatusResponse } from './schemas';

/**
 * `hope.admin.aiService` — the `svc:admin:ai-service:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:ai-service:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller AiServiceAdminController
 * (9 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminAiServiceResource extends AdminResource {
  readonly svcScope = 'svc:admin:ai-service:manage';

  /**
   * Guardrail read-only configuration: medical-validation engine settings + supported analysis types.
   *
   * `GET /api/v1/admin/ai-services/guardrail/config` — `AiServiceAdminController.guardrailConfig`.
   */
  guardrailConfig(options: AdminRequestOptions = {}): Promise<unknown> {
    return this.request<unknown>({
      method: 'GET',
      path: 'admin/ai-services/guardrail/config',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Guardrail service health (proxied /api/health): LLM engine, GLiNER, and Redis component checks.
   *
   * `GET /api/v1/admin/ai-services/guardrail/status` — `AiServiceAdminController.guardrailStatus`.
   */
  guardrailStatus(options: AdminRequestOptions = {}): Promise<unknown> {
    return this.request<unknown>({
      method: 'GET',
      path: 'admin/ai-services/guardrail/status',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Search MLflow experiments
   *
   * Proxies MLflow’s own `GET /api/2.0/mlflow/experiments/search`. Response shape is UPSTREAM-OWNED and passed through verbatim.
   *
   * `GET /api/v1/admin/ai-services/mlflow/experiments` — `AiServiceAdminController.mlflowExperiments`.
   */
  mlflowExperiments(
    options: AdminRequestOptions & { query?: { filter?: string; maxResults?: number; orderBy?: string; pageToken?: string } } = {},
  ): Promise<unknown> {
    return this.request<unknown>({
      method: 'GET',
      path: 'admin/ai-services/mlflow/experiments',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Search MLflow model versions
   *
   * Proxies `GET /api/2.0/mlflow/model-versions/search`. Aliases (not stages) are the promotion mechanism — see the registry conventions.
   *
   * `GET /api/v1/admin/ai-services/mlflow/model-versions` — `AiServiceAdminController.mlflowModelVersions`.
   */
  mlflowModelVersions(
    options: AdminRequestOptions & { query?: { filter?: string; maxResults?: number; orderBy?: string; pageToken?: string } } = {},
  ): Promise<unknown> {
    return this.request<unknown>({
      method: 'GET',
      path: 'admin/ai-services/mlflow/model-versions',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Search the MLflow model registry
   *
   * Proxies `GET /api/2.0/mlflow/registered-models/search`. MLflow holds metadata and lineage; served weights live in the `hope-models` bucket.
   *
   * `GET /api/v1/admin/ai-services/mlflow/registered-models` — `AiServiceAdminController.mlflowRegisteredModels`.
   */
  mlflowRegisteredModels(
    options: AdminRequestOptions & { query?: { filter?: string; maxResults?: number; orderBy?: string; pageToken?: string } } = {},
  ): Promise<unknown> {
    return this.request<unknown>({
      method: 'GET',
      path: 'admin/ai-services/mlflow/registered-models',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * MLflow tracking-server reachability, version and framing posture
   *
   * Probes the tracking server’s host-validation-exempt `/health` (and `/version` best-effort) and reports the `X-Frame-Options` header OBSERVED on that response, so the console can decide whether the MLflow UI may be embedded rather than assuming. Never fails: an unreachable server is a status document with `reachable: false`, because MLflow ships without an Ingress and being unreachable from the console is its normal state.
   *
   * `GET /api/v1/admin/ai-services/mlflow/status` — `AiServiceAdminController.mlflowStatus`.
   */
  mlflowStatus(options: AdminRequestOptions = {}): Promise<MlflowStatusResponse> {
    return this.request<MlflowStatusResponse>({
      method: 'GET',
      path: 'admin/ai-services/mlflow/status',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * NLP service health (proxied /api/v1/health): per-model component checks with load status.
   *
   * `GET /api/v1/admin/ai-services/nlp/status` — `AiServiceAdminController.nlpStatus`.
   */
  nlpStatus(options: AdminRequestOptions = {}): Promise<unknown> {
    return this.request<unknown>({
      method: 'GET',
      path: 'admin/ai-services/nlp/status',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Inference readiness — the platform’s last observation of every engine, service and model
   *
   * The stored snapshot taken by the readiness sweep: per engine (LM Studio, Ollama, vLLM, llama.cpp) its probe status, latency and loaded/listed counts; per HOPE service its heartbeat; per registry model a readiness state (`ready` / `loadable` / `engine_down` / `weights_missing` / `credential_missing` / `unknown`). READS NOTHING LIVE — it serves what the sweep last saw, and `checkedAt` says when that was, so an operator is never shown a stale answer dressed as a current one. Before the first sweep (or with the sweep switched off) this is an EMPTY document with `checkedAt: null`, not a 404: "nothing has been observed" is a state of the platform, not a missing resource. Use `POST readiness/refresh` to take an observation now.
   *
   * `GET /api/v1/admin/ai-services/readiness` — `AiServiceAdminController.readiness`.
   */
  readiness(options: AdminRequestOptions = {}): Promise<InferenceReadinessResponse> {
    return this.request<InferenceReadinessResponse>({
      method: 'GET',
      path: 'admin/ai-services/readiness',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Take one readiness observation now
   *
   * Runs a single sweep immediately, ignoring the configured interval, and returns its result. Rate-limited to 6 per minute because each run sends a probe to the text service, which is the single aggregator in front of the engines. Never fails on an unreachable engine — an engine that does not answer IS the observation.
   *
   * `POST /api/v1/admin/ai-services/readiness/refresh` — `AiServiceAdminController.refreshReadiness`.
   */
  refreshReadiness(options: AdminRequestOptions = {}): Promise<InferenceReadinessResponse> {
    return this.request<InferenceReadinessResponse>({
      method: 'POST',
      path: 'admin/ai-services/readiness/refresh',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
