/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { AdminResource } from './admin-resource';
import type { AdminRequestOptions, IfMatchPrecondition } from './admin-resource';
import type { AiTaskDefaultResponse, ModelResponse, UpsertAiTaskDefaultRequest } from './schemas';

/**
 * `hope.admin.aiTaskDefault` — the `svc:admin:ai-task-default:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:ai-task-default:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller AiTaskDefaultAdminController
 * (4 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminAiTaskDefaultResource extends AdminResource {
  readonly svcScope = 'svc:admin:ai-task-default:manage';

  /**
   * Resolve the effective default model for one AI task key — or ALL keys when taskKey is omitted
   *
   * Cascade: tenant row → SYSTEM platform row → null (the consuming service falls back to its env bootstrap default). Valid task keys: guardrail.validate, guardrail.safety, guardrail.groundedness, guardrail.pii, guardrail.pii.spans, nlp.ner, nlp.classification, nlp.diagnosis, nlp.sentiment, nlp.toxicity, text.live, text.finalize, text.live.fallback, text.finalize.fallback, text.test, harness.judge, vlm.extract. Omit taskKey to receive an array covering every key.
   *
   * `GET /api/v1/admin/ai-task-defaults` — `AiTaskDefaultAdminController.getEffective`.
   */
  getEffective(
    options: AdminRequestOptions & {
      query?: {
        taskKey?:
          | 'guardrail.validate'
          | 'guardrail.safety'
          | 'guardrail.groundedness'
          | 'guardrail.pii'
          | 'guardrail.pii.spans'
          | 'nlp.ner'
          | 'nlp.classification'
          | 'nlp.diagnosis'
          | 'nlp.sentiment'
          | 'nlp.toxicity'
          | 'text.live'
          | 'text.finalize'
          | 'text.live.fallback'
          | 'text.finalize.fallback'
          | 'text.test'
          | 'harness.judge'
          | 'vlm.extract';
        tenantId?: string;
      };
    } = {},
  ): Promise<unknown> {
    return this.request<unknown>({
      method: 'GET',
      path: 'admin/ai-task-defaults',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List the registry models selectable as the default for one AI task key
   *
   * ENABLED AiModel rows whose taskType is compatible with the key (guardrail.validate → GUARDRAIL, nlp.ner → TOKEN_CLASSIFICATION, nlp.classification → TEXT_CLASSIFICATION). Read via the SHARED-READ registry query (r2605 Finding E): visibility is [caller tenant, SYSTEM] de-duplicated by slug (tenant clone wins), so tenant admins get their picker options here — including the SYSTEM catalog — without needing the super-admin-only /admin/ai-models surface.
   *
   * `GET /api/v1/admin/ai-task-defaults/options` — `AiTaskDefaultAdminController.getOptions`.
   */
  getOptions(
    options: AdminRequestOptions & {
      query?: {
        taskKey:
          | 'guardrail.validate'
          | 'guardrail.safety'
          | 'guardrail.groundedness'
          | 'guardrail.pii'
          | 'guardrail.pii.spans'
          | 'nlp.ner'
          | 'nlp.classification'
          | 'nlp.diagnosis'
          | 'nlp.sentiment'
          | 'nlp.toxicity'
          | 'text.live'
          | 'text.finalize'
          | 'text.live.fallback'
          | 'text.finalize.fallback'
          | 'text.test'
          | 'harness.judge'
          | 'vlm.extract';
      };
    } = {},
  ): Promise<ModelResponse[]> {
    return this.request<ModelResponse[]>({
      method: 'GET',
      path: 'admin/ai-task-defaults/options',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get the raw, editable AiTaskDefault row for a (tenant, taskKey)
   *
   * Returns the tenant row, or a `version:0` placeholder when none exists yet. The `version` drives the `If-Match` OCC token for the matching `PUT` (create with `expectedVersion: 0`; the global ETagInterceptor stamps `ETag` from it).
   *
   * `GET /api/v1/admin/ai-task-defaults/row` — `AiTaskDefaultAdminController.getRow`.
   */
  getRow(
    options: AdminRequestOptions & {
      query?: {
        taskKey:
          | 'guardrail.validate'
          | 'guardrail.safety'
          | 'guardrail.groundedness'
          | 'guardrail.pii'
          | 'guardrail.pii.spans'
          | 'nlp.ner'
          | 'nlp.classification'
          | 'nlp.diagnosis'
          | 'nlp.sentiment'
          | 'nlp.toxicity'
          | 'text.live'
          | 'text.finalize'
          | 'text.live.fallback'
          | 'text.finalize.fallback'
          | 'text.test'
          | 'harness.judge'
          | 'vlm.extract';
        tenantId?: string;
      };
    } = {},
  ): Promise<AiTaskDefaultResponse> {
    return this.request<AiTaskDefaultResponse>({
      method: 'GET',
      path: 'admin/ai-task-defaults/row',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Create or update the (tenant, taskKey) default-model row under optimistic concurrency
   *
   * `modelSlug` must resolve to an ENABLED AiModel in [tenant, SYSTEM] with a taskType compatible with the key. `If-Match` (RFC 7232) carries the version read from the prior GET — `"0"` creates the row, an existing version CASes against `_version` (drift → 412, missing → 428). `nlp.*`/`harness.*` keys are SUPER_ADMIN-ONLY (403 for tenant admins). `guardrail.*` is tenant-admin configurable, but the slug must resolve to a SYSTEM-tenant AiModel row (the platform-approved list) — also 403 otherwise.
   *
   * `PUT /api/v1/admin/ai-task-defaults/row` — `AiTaskDefaultAdminController.upsertRow`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  upsertRow(
    body: UpsertAiTaskDefaultRequest,
    options: AdminRequestOptions & {
      query?: {
        taskKey:
          | 'guardrail.validate'
          | 'guardrail.safety'
          | 'guardrail.groundedness'
          | 'guardrail.pii'
          | 'guardrail.pii.spans'
          | 'nlp.ner'
          | 'nlp.classification'
          | 'nlp.diagnosis'
          | 'nlp.sentiment'
          | 'nlp.toxicity'
          | 'text.live'
          | 'text.finalize'
          | 'text.live.fallback'
          | 'text.finalize.fallback'
          | 'text.test'
          | 'harness.judge'
          | 'vlm.extract';
        tenantId?: string;
      };
    } & { ifMatch: IfMatchPrecondition },
  ): Promise<AiTaskDefaultResponse> {
    return this.requestWithPrecondition<AiTaskDefaultResponse>({
      method: 'PUT',
      path: 'admin/ai-task-defaults/row',
      query: options.query,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
