/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions, IfMatchPrecondition } from './admin-resource';
import type {
  AllowedOriginEnforcementPostureResponse,
  CreateTenantAllowedOriginRequest,
  TenantAllowedOriginResponse,
  UpdateTenantAllowedOriginRequest,
} from './schemas';

/**
 * `hope.admin.allowedOrigin` — the `svc:admin:allowed-origin:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:allowed-origin:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller TenantAllowedOriginController
 * (6 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminAllowedOriginResource extends AdminResource {
  readonly svcScope = 'svc:admin:allowed-origin:manage';

  /**
   * List the caller tenant's allowed-origin rows
   *
   * `GET /api/v1/admin/allowed-origins` — `TenantAllowedOriginController.getAll`.
   */
  getAll(options: AdminRequestOptions = {}): Promise<TenantAllowedOriginResponse[]> {
    return this.request<TenantAllowedOriginResponse[]>({
      method: 'GET',
      path: 'admin/allowed-origins',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Register a new allowed origin
   *
   * The raw `origin` is normalized server-side (`normalizeOrigin()`) before persistence and uniqueness checking — the normalized form, not the raw input, is what gets stored. A wildcard/pattern origin, or a write to a SYSTEM-tenant row, is refused with 403 unless the caller is a super administrator (enforced in `TenantAllowedOriginService`, not here — see the class AUTH-NOTE).
   *
   * `POST /api/v1/admin/allowed-origins` — `TenantAllowedOriginController.create`.
   */
  create(body: CreateTenantAllowedOriginRequest, options: AdminRequestOptions = {}): Promise<TenantAllowedOriginResponse> {
    return this.request<TenantAllowedOriginResponse>({
      method: 'POST',
      path: 'admin/allowed-origins',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Soft-delete an allowed-origin row
   *
   * `DELETE /api/v1/admin/allowed-origins/{id}` — `TenantAllowedOriginController.deleteById`.
   */
  deleteById(id: string, options: AdminRequestOptions = {}): Promise<TenantAllowedOriginResponse> {
    return this.request<TenantAllowedOriginResponse>({
      method: 'DELETE',
      path: `admin/allowed-origins/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get one allowed-origin row by id
   *
   * `GET /api/v1/admin/allowed-origins/{id}` — `TenantAllowedOriginController.getById`.
   */
  getById(id: string, options: AdminRequestOptions = {}): Promise<TenantAllowedOriginResponse> {
    return this.request<TenantAllowedOriginResponse>({
      method: 'GET',
      path: `admin/allowed-origins/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Update an allowed-origin row under optimistic concurrency
   *
   * Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED, and the server runs a Compare-And-Set against the row's `_version`. When the header is present, its value overrides the body-field `expectedVersion`. On version drift the response is `412 Precondition Failed`; a missing header is `428 Precondition Required`. `origin` (when present in the body) is re-normalized; escalating an exact row's `origin` into a wildcard/pattern is refused with 403 unless the caller is a global administrator (enforced in `TenantAllowedOriginService`, not here — see the class AUTH-NOTE).
   *
   * `PATCH /api/v1/admin/allowed-origins/{id}` — `TenantAllowedOriginController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  update(
    id: string,
    body: UpdateTenantAllowedOriginRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<TenantAllowedOriginResponse> {
    return this.requestWithPrecondition<TenantAllowedOriginResponse>({
      method: 'PATCH',
      path: `admin/allowed-origins/${encodePathSegment(String(id))}`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Report whether origin enforcement is currently ON, platform-wide (FR-4).
   *
   * `GET /api/v1/admin/allowed-origins/posture` — `TenantAllowedOriginController.getPosture`.
   */
  getPosture(options: AdminRequestOptions = {}): Promise<AllowedOriginEnforcementPostureResponse> {
    return this.request<AllowedOriginEnforcementPostureResponse>({
      method: 'GET',
      path: 'admin/allowed-origins/posture',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
