/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions } from './admin-resource';
import type { ApiKeyResponse, ApiKeyScopesCatalogResponse, CreateApiKeyRequest, PaginatedResponse, UpdateApiKeyRequest } from './schemas';

/**
 * `hope.admin.apikey` — the `svc:admin:apikey:write` administration area.
 *
 * **Required service-account scope: `svc:admin:apikey:write`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * 4 of its routes ALSO accept `svc:admin:apikey:read`, so a read-only grant reaches
 * them and nothing else here. Those methods name their own accepted scopes in a 403;
 * the scope above is the one that reaches EVERY route.
 *
 * Backed by controller ApiKeyController
 * (9 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminApikeyResource extends AdminResource {
  readonly svcScope = 'svc:admin:apikey:write';

  /**
   * Retrieving multiple ApiKeyResponses
   *
   * `GET /api/v1/admin/api-keys` — `ApiKeyController.fetchAll`.
   *
   * Reachable with ANY ONE of `svc:admin:apikey:read`, `svc:admin:apikey:write` — the gateway matches required scopes with OR, so the area's `svc:admin:apikey:write` still reaches this route and a read-only grant now does too.
   */
  fetchAll(
    options: AdminRequestOptions & {
      query?: { filters?: string; limit?: number; page?: number; pageSize?: number; search?: string; searchFields?: string; sort?: string };
    } = {},
  ): Promise<PaginatedResponse & { data?: ApiKeyResponse[] }> {
    return this.request<PaginatedResponse & { data?: ApiKeyResponse[] }>({
      method: 'GET',
      path: 'admin/api-keys',
      query: options.query,
      svcScopes: ['svc:admin:apikey:read', 'svc:admin:apikey:write'],
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * AUTH-NOTE: `@CanCreate('ApiKey')` UNDERSTATES the real gate. `ApiKeyService` additionally enforces a privilege CEILING on the requested `scopes` (`assertScopeCeiling`): every scope's implied CASL ability must be one the CALLING principal already holds, so a tenant admin cannot mint a key carrying `admin:*` or the bare `'*'`. It fails CLOSED when the caller's compiled ability is unavailable — notably on the API-key-authenticated minting path, where `UnifiedAuthGuard` deliberately never publishes the ability to CLS. A refusal is a 403 (privilege boundary), NOT the cross-tenant 404-over-403 posture this controller's by-id routes use.
   *
   * `POST /api/v1/admin/api-keys` — `ApiKeyController.create`.
   */
  create(body: CreateApiKeyRequest, options: AdminRequestOptions = {}): Promise<ApiKeyResponse> {
    return this.request<ApiKeyResponse>({
      method: 'POST',
      path: 'admin/api-keys',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Deleting a ApiKeyResponse by id
   *
   * `DELETE /api/v1/admin/api-keys/{id}` — `ApiKeyController.delete`.
   */
  delete(id: string, options: AdminRequestOptions = {}): Promise<ApiKeyResponse> {
    return this.request<ApiKeyResponse>({
      method: 'DELETE',
      path: `admin/api-keys/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single ApiKeyResponse by id
   *
   * `GET /api/v1/admin/api-keys/{id}` — `ApiKeyController.fetchById`.
   *
   * Reachable with ANY ONE of `svc:admin:apikey:read`, `svc:admin:apikey:write` — the gateway matches required scopes with OR, so the area's `svc:admin:apikey:write` still reaches this route and a read-only grant now does too.
   */
  fetchById(id: string, options: AdminRequestOptions = {}): Promise<ApiKeyResponse> {
    return this.request<ApiKeyResponse>({
      method: 'GET',
      path: `admin/api-keys/${encodePathSegment(String(id))}`,
      svcScopes: ['svc:admin:apikey:read', 'svc:admin:apikey:write'],
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * AUTH-NOTE: `@CanUpdate('ApiKey')` UNDERSTATES the real gate — the same scope ceiling as `create` above, applied to the WIDENING DELTA only. A PATCH is refused (403) when it ADDS a scope whose implied ability the caller does not hold; renames and narrowing PATCHes are not gated, and a PATCH that omits `scopes` is not checked at all.
   *
   * `PATCH /api/v1/admin/api-keys/{id}` — `ApiKeyController.update`.
   */
  update(id: string, body: UpdateApiKeyRequest, options: AdminRequestOptions = {}): Promise<ApiKeyResponse> {
    return this.request<ApiKeyResponse>({
      method: 'PATCH',
      path: `admin/api-keys/${encodePathSegment(String(id))}`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Creating a ApiKeyResponse by id
   *
   * `POST /api/v1/admin/api-keys/{id}/revoke` — `ApiKeyController.revoke`.
   */
  revoke(id: string, options: AdminRequestOptions = {}): Promise<ApiKeyResponse> {
    return this.request<ApiKeyResponse>({
      method: 'POST',
      path: `admin/api-keys/${encodePathSegment(String(id))}/revoke`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Creating a ApiKeyResponse by id
   *
   * `POST /api/v1/admin/api-keys/{id}/rotate` — `ApiKeyController.rotate`.
   */
  rotate(id: string, options: AdminRequestOptions = {}): Promise<ApiKeyResponse> {
    return this.request<ApiKeyResponse>({
      method: 'POST',
      path: `admin/api-keys/${encodePathSegment(String(id))}/rotate`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single ApiKeyResponse by id
   *
   * `GET /api/v1/admin/api-keys/{id}/usage` — `ApiKeyController.getUsage`.
   *
   * Reachable with ANY ONE of `svc:admin:apikey:read`, `svc:admin:apikey:write` — the gateway matches required scopes with OR, so the area's `svc:admin:apikey:write` still reaches this route and a read-only grant now does too.
   */
  getUsage(id: string, options: AdminRequestOptions = {}): Promise<ApiKeyResponse> {
    return this.request<ApiKeyResponse>({
      method: 'GET',
      path: `admin/api-keys/${encodePathSegment(String(id))}/usage`,
      svcScopes: ['svc:admin:apikey:read', 'svc:admin:apikey:write'],
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List available API key scopes
   *
   * Returns the grantable scope catalogue, grouped by category, plus the three scope presets the create-key dialog offers.
   *
   * `GET /api/v1/admin/api-keys/scopes` — `ApiKeyController.getAvailableScopes`.
   *
   * Reachable with ANY ONE of `svc:admin:apikey:read`, `svc:admin:apikey:write` — the gateway matches required scopes with OR, so the area's `svc:admin:apikey:write` still reaches this route and a read-only grant now does too.
   */
  getAvailableScopes(options: AdminRequestOptions = {}): Promise<ApiKeyScopesCatalogResponse> {
    return this.request<ApiKeyScopesCatalogResponse>({
      method: 'GET',
      path: 'admin/api-keys/scopes',
      svcScopes: ['svc:admin:apikey:read', 'svc:admin:apikey:write'],
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
