/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions } from './admin-resource';
import type { AuditLogResponse, CursorPaginatedAuditLogResponse, PaginatedResponse } from './schemas';

/**
 * `hope.admin.audit` — the `svc:admin:audit:read` administration area.
 *
 * **Required service-account scope: `svc:admin:audit:read`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller AuditLogController
 * (6 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminAuditResource extends AdminResource {
  readonly svcScope = 'svc:admin:audit:read';

  /**
   * Fetch all audit logs
   *
   * Returns a paginated list of audit logs. Supports filters (from/to date range, action, resourceType, userId) pushed to the database, and enriches each row with the resolved responsible user.
   *
   * `GET /api/v1/admin/audit-logs` — `AuditLogController.fetchAll`.
   */
  fetchAll(
    options: AdminRequestOptions & {
      query?: {
        action?: 'CREATE' | 'READ' | 'UPDATE' | 'DELETE' | 'ARCHIVE' | 'LOGIN' | 'LOGOUT' | 'IMPERSONATED_ACTION';
        filters?: string;
        format?: 'csv' | 'xlsx' | 'pdf';
        from?: string;
        limit?: number;
        page?: number;
        pageSize?: number;
        resourceType?:
          | 'AuditLog'
          | 'ApiKey'
          | 'Department'
          | 'GlobalSetting'
          | 'IntegrationPackage'
          | 'IntegrationItem'
          | 'Media'
          | 'Notification'
          | 'ResourceSubscription'
          | 'Role'
          | 'Permission'
          | 'RolePermission'
          | 'Tag'
          | 'Tenant'
          | 'UserRoleAssignment'
          | 'User'
          | 'UserSettings'
          | 'UserProfile'
          | 'UserMedia'
          | 'Webhook'
          | 'WebhookRunHistory'
          | 'Consultation'
          | 'ContextItem'
          | 'ContextItemVersion'
          | 'AudioRecording'
          | 'SummaryMeta'
          | 'NamedEntity'
          | 'AsrPipeline'
          | 'AiModel'
          | 'TranscriptionJob'
          | 'PromptTemplate'
          | 'DnaWritingStyleReport'
          | 'TenantBucket'
          | 'StorageAccessKey'
          | 'TenantStorageConfig'
          | 'Highlight'
          | 'AsrPipelineVersion'
          | 'UserVoiceProfile'
          | 'UserDepartment'
          | 'TenantFrontendConfig'
          | 'TenantTtsConfig'
          | 'TenantIdentityProvider'
          | 'FederatedIdentity'
          | 'AiTaskDefault'
          | 'McpServer'
          | 'AiProviderConnection'
          | 'AiRuntimeProfile'
          | 'GateEditExemplar'
          | 'DepartmentAgent'
          | 'EvalRun'
          | 'TenantSttConfig'
          | 'TenantSttProviderCredential'
          | 'TenantAllowedOrigin'
          | 'AiPriceBook'
          | 'BillingInvoice'
          | 'BillingAdjustment'
          | 'ServiceRelease'
          | 'ServiceInstance'
          | 'ChangelogEntry'
          | 'UserChangelogAcknowledgement'
          | 'ConsultationContextSchema'
          | 'AgentPromotion'
          | 'WorkflowDefinition'
          | 'ConsentGrant'
          | 'WorkflowTestFixture'
          | 'TenantNlpTaskInstructions'
          | 'KnowledgeDocument'
          | 'ServiceAccount'
          | 'WorkflowAssignment'
          | 'WorkflowInvariantRule'
          | 'RateLimitRule';
        search?: string;
        searchFields?: string;
        sort?: string;
        to?: string;
        userId?: string;
      };
    } = {},
  ): Promise<PaginatedResponse & { data?: AuditLogResponse[] }> {
    return this.request<PaginatedResponse & { data?: AuditLogResponse[] }>({
      method: 'GET',
      path: 'admin/audit-logs',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Fetch audit log by ID
   *
   * Returns a single audit log entry by its unique identifier.
   *
   * `GET /api/v1/admin/audit-logs/{id}` — `AuditLogController.fetchById`.
   */
  fetchById(id: string, options: AdminRequestOptions = {}): Promise<AuditLogResponse> {
    return this.request<AuditLogResponse>({
      method: 'GET',
      path: `admin/audit-logs/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Fetch audit logs (cursor pagination)
   *
   * Returns a keyset (cursor) page of audit logs ordered by (createdAt, id) DESC. Pass the previous response's `nextCursor` to page forward; `hasMore` signals more pages. Supports the same filters (from/to/action/resourceType/userId) as the offset list.
   *
   * `GET /api/v1/admin/audit-logs/cursor` — `AuditLogController.fetchByCursor`.
   */
  fetchByCursor(
    options: AdminRequestOptions & {
      query?: {
        action?: 'CREATE' | 'READ' | 'UPDATE' | 'DELETE' | 'ARCHIVE' | 'LOGIN' | 'LOGOUT' | 'IMPERSONATED_ACTION';
        cursor?: string;
        filters?: string;
        from?: string;
        limit?: number;
        resourceType?:
          | 'AuditLog'
          | 'ApiKey'
          | 'Department'
          | 'GlobalSetting'
          | 'IntegrationPackage'
          | 'IntegrationItem'
          | 'Media'
          | 'Notification'
          | 'ResourceSubscription'
          | 'Role'
          | 'Permission'
          | 'RolePermission'
          | 'Tag'
          | 'Tenant'
          | 'UserRoleAssignment'
          | 'User'
          | 'UserSettings'
          | 'UserProfile'
          | 'UserMedia'
          | 'Webhook'
          | 'WebhookRunHistory'
          | 'Consultation'
          | 'ContextItem'
          | 'ContextItemVersion'
          | 'AudioRecording'
          | 'SummaryMeta'
          | 'NamedEntity'
          | 'AsrPipeline'
          | 'AiModel'
          | 'TranscriptionJob'
          | 'PromptTemplate'
          | 'DnaWritingStyleReport'
          | 'TenantBucket'
          | 'StorageAccessKey'
          | 'TenantStorageConfig'
          | 'Highlight'
          | 'AsrPipelineVersion'
          | 'UserVoiceProfile'
          | 'UserDepartment'
          | 'TenantFrontendConfig'
          | 'TenantTtsConfig'
          | 'TenantIdentityProvider'
          | 'FederatedIdentity'
          | 'AiTaskDefault'
          | 'McpServer'
          | 'AiProviderConnection'
          | 'AiRuntimeProfile'
          | 'GateEditExemplar'
          | 'DepartmentAgent'
          | 'EvalRun'
          | 'TenantSttConfig'
          | 'TenantSttProviderCredential'
          | 'TenantAllowedOrigin'
          | 'AiPriceBook'
          | 'BillingInvoice'
          | 'BillingAdjustment'
          | 'ServiceRelease'
          | 'ServiceInstance'
          | 'ChangelogEntry'
          | 'UserChangelogAcknowledgement'
          | 'ConsultationContextSchema'
          | 'AgentPromotion'
          | 'WorkflowDefinition'
          | 'ConsentGrant'
          | 'WorkflowTestFixture'
          | 'TenantNlpTaskInstructions'
          | 'KnowledgeDocument'
          | 'ServiceAccount'
          | 'WorkflowAssignment'
          | 'WorkflowInvariantRule'
          | 'RateLimitRule';
        to?: string;
        userId?: string;
      };
    } = {},
  ): Promise<CursorPaginatedAuditLogResponse> {
    return this.request<CursorPaginatedAuditLogResponse>({
      method: 'GET',
      path: 'admin/audit-logs/cursor',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Export audit logs (csv | xlsx | pdf)
   *
   * Streams the filtered, tenant-scoped audit logs as a csv/xlsx/pdf file attachment.
   *
   * `GET /api/v1/admin/audit-logs/export` — `AuditLogController.exportCsv`.
   */
  exportCsv(
    options: AdminRequestOptions & {
      query?: {
        action?: 'CREATE' | 'READ' | 'UPDATE' | 'DELETE' | 'ARCHIVE' | 'LOGIN' | 'LOGOUT' | 'IMPERSONATED_ACTION';
        filters?: string;
        format?: 'csv' | 'xlsx' | 'pdf';
        from?: string;
        limit?: number;
        page?: number;
        resourceType?:
          | 'AuditLog'
          | 'ApiKey'
          | 'Department'
          | 'GlobalSetting'
          | 'IntegrationPackage'
          | 'IntegrationItem'
          | 'Media'
          | 'Notification'
          | 'ResourceSubscription'
          | 'Role'
          | 'Permission'
          | 'RolePermission'
          | 'Tag'
          | 'Tenant'
          | 'UserRoleAssignment'
          | 'User'
          | 'UserSettings'
          | 'UserProfile'
          | 'UserMedia'
          | 'Webhook'
          | 'WebhookRunHistory'
          | 'Consultation'
          | 'ContextItem'
          | 'ContextItemVersion'
          | 'AudioRecording'
          | 'SummaryMeta'
          | 'NamedEntity'
          | 'AsrPipeline'
          | 'AiModel'
          | 'TranscriptionJob'
          | 'PromptTemplate'
          | 'DnaWritingStyleReport'
          | 'TenantBucket'
          | 'StorageAccessKey'
          | 'TenantStorageConfig'
          | 'Highlight'
          | 'AsrPipelineVersion'
          | 'UserVoiceProfile'
          | 'UserDepartment'
          | 'TenantFrontendConfig'
          | 'TenantTtsConfig'
          | 'TenantIdentityProvider'
          | 'FederatedIdentity'
          | 'AiTaskDefault'
          | 'McpServer'
          | 'AiProviderConnection'
          | 'AiRuntimeProfile'
          | 'GateEditExemplar'
          | 'DepartmentAgent'
          | 'EvalRun'
          | 'TenantSttConfig'
          | 'TenantSttProviderCredential'
          | 'TenantAllowedOrigin'
          | 'AiPriceBook'
          | 'BillingInvoice'
          | 'BillingAdjustment'
          | 'ServiceRelease'
          | 'ServiceInstance'
          | 'ChangelogEntry'
          | 'UserChangelogAcknowledgement'
          | 'ConsultationContextSchema'
          | 'AgentPromotion'
          | 'WorkflowDefinition'
          | 'ConsentGrant'
          | 'WorkflowTestFixture'
          | 'TenantNlpTaskInstructions'
          | 'KnowledgeDocument'
          | 'ServiceAccount'
          | 'WorkflowAssignment'
          | 'WorkflowInvariantRule'
          | 'RateLimitRule';
        search?: string;
        searchFields?: string;
        sort?: string;
        to?: string;
        userId?: string;
      };
    } = {},
  ): Promise<unknown> {
    return this.request<unknown>({
      method: 'GET',
      path: 'admin/audit-logs/export',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Fetch audit logs by resource
   *
   * Returns all audit logs related to a specific resource type and ID.
   *
   * `GET /api/v1/admin/audit-logs/resource/{resourceType}/{resourceId}` — `AuditLogController.fetchByResource`.
   */
  fetchByResource(
    resourceType: string,
    resourceId: string,
    options: AdminRequestOptions & {
      query?: { filters?: string; limit?: number; page?: number; search?: string; searchFields?: string; sort?: string };
    } = {},
  ): Promise<PaginatedResponse & { data?: AuditLogResponse[] }> {
    return this.request<PaginatedResponse & { data?: AuditLogResponse[] }>({
      method: 'GET',
      path: `admin/audit-logs/resource/${encodePathSegment(String(resourceType))}/${encodePathSegment(String(resourceId))}`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Fetch audit logs by user
   *
   * Returns all audit logs created by a specific user (responsibleUserId).
   *
   * `GET /api/v1/admin/audit-logs/user/{userId}` — `AuditLogController.fetchByUser`.
   */
  fetchByUser(
    userId: string,
    options: AdminRequestOptions & {
      query?: { filters?: string; limit?: number; page?: number; search?: string; searchFields?: string; sort?: string };
    } = {},
  ): Promise<PaginatedResponse & { data?: AuditLogResponse[] }> {
    return this.request<PaginatedResponse & { data?: AuditLogResponse[] }>({
      method: 'GET',
      path: `admin/audit-logs/user/${encodePathSegment(String(userId))}`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
