/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions, IfMatchPrecondition } from './admin-resource';
import type {
  AssignTenantRequest,
  AssignTenantResponse,
  ClonePipelineRequest,
  CreatePipelineRequest,
  PaginatedPipelineResponse,
  PaginatedResponse,
  PipelineResponse,
  PipelineVersionResponse,
  TogglePipelineRequest,
  UpdatePipelineRequest,
  ValidateYamlRequest,
} from './schemas';

/**
 * `hope.admin.audioPipeline` — the `svc:admin:audio-pipeline:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:audio-pipeline:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller AudioPipelineController
 * (14 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminAudioPipelineResource extends AdminResource {
  readonly svcScope = 'svc:admin:audio-pipeline:manage';

  /**
   * Retrieving multiple PipelineResponses
   *
   * `GET /api/v1/admin/audio/pipelines` — `AudioPipelineController.fetchAll`.
   */
  fetchAll(options: AdminRequestOptions = {}): Promise<PaginatedResponse & { data?: PipelineResponse[] }> {
    return this.request<PaginatedResponse & { data?: PipelineResponse[] }>({
      method: 'GET',
      path: 'admin/audio/pipelines',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Creating a PipelineResponse
   *
   * DEPRECATED (TASK-861 — removed in R4; use /api/v1/admin/agents (task SPEECH_TO_TEXT, TASK-863)).
   *
   * `POST /api/v1/admin/audio/pipelines` — `AudioPipelineController.create`.
   */
  create(body: CreatePipelineRequest, options: AdminRequestOptions = {}): Promise<PipelineResponse> {
    return this.request<PipelineResponse>({
      method: 'POST',
      path: 'admin/audio/pipelines',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Deleting a PipelineResponse by id
   *
   * DEPRECATED (TASK-861 — removed in R4; use /api/v1/admin/agents (task SPEECH_TO_TEXT, TASK-863)).
   *
   * `DELETE /api/v1/admin/audio/pipelines/{id}` — `AudioPipelineController.delete`.
   */
  delete(id: string, options: AdminRequestOptions = {}): Promise<PipelineResponse> {
    return this.request<PipelineResponse>({
      method: 'DELETE',
      path: `admin/audio/pipelines/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single PipelineResponse by id
   *
   * `GET /api/v1/admin/audio/pipelines/{id}` — `AudioPipelineController.fetchById`.
   */
  fetchById(id: string, options: AdminRequestOptions = {}): Promise<PipelineResponse> {
    return this.request<PipelineResponse>({
      method: 'GET',
      path: `admin/audio/pipelines/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Updating a PipelineResponse by id
   *
   * Updates one AsrPipeline row. Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED, and the server runs a Compare-And-Set against the row's `_version` column. When the header is present, its value overrides the body-field `expectedVersion`. On version drift the response is `412 Precondition Failed`; missing header is `428 Precondition Required`. DEPRECATED (TASK-861 — removed in R4; use /api/v1/admin/agents (task SPEECH_TO_TEXT, TASK-863)).
   *
   * `PATCH /api/v1/admin/audio/pipelines/{id}` — `AudioPipelineController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  update(id: string, body: UpdatePipelineRequest, options: AdminRequestOptions & { ifMatch: IfMatchPrecondition }): Promise<PipelineResponse> {
    return this.requestWithPrecondition<PipelineResponse>({
      method: 'PATCH',
      path: `admin/audio/pipelines/${encodePathSegment(String(id))}`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Assign an ASR pipeline within its tenant
   *
   * DEPRECATED (TASK-861 — removed in R4; use /api/v1/admin/agents (task SPEECH_TO_TEXT, TASK-863)).
   *
   * `POST /api/v1/admin/audio/pipelines/{id}/assign-tenant` — `AudioPipelineController.assignTenant`.
   */
  assignTenant(id: string, body: AssignTenantRequest, options: AdminRequestOptions = {}): Promise<AssignTenantResponse> {
    return this.request<AssignTenantResponse>({
      method: 'POST',
      path: `admin/audio/pipelines/${encodePathSegment(String(id))}/assign-tenant`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Clone a pipeline into a new editable copy
   *
   * Creates a NEW pipeline from an existing one. The copy is never `templateLocked`, carries the source `sourceTemplateSlug` forward, and starts with the source's current config as its v1 version snapshot. Counts against the `maxAsrPipelines` plan quota like any other create.
   *
   * `POST /api/v1/admin/audio/pipelines/{id}/clone` — `AudioPipelineController.clone`.
   */
  clone(id: string, body: ClonePipelineRequest, options: AdminRequestOptions = {}): Promise<PipelineResponse> {
    return this.request<PipelineResponse>({
      method: 'POST',
      path: `admin/audio/pipelines/${encodePathSegment(String(id))}/clone`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Set a pipeline as the tenant default
   *
   * DEPRECATED (TASK-861 — removed in R4; use /api/v1/admin/agents (task SPEECH_TO_TEXT, TASK-863)).
   *
   * `POST /api/v1/admin/audio/pipelines/{id}/set-default` — `AudioPipelineController.setDefault`.
   */
  setDefault(id: string, options: AdminRequestOptions = {}): Promise<PipelineResponse> {
    return this.request<PipelineResponse>({
      method: 'POST',
      path: `admin/audio/pipelines/${encodePathSegment(String(id))}/set-default`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Enable/disable a pipeline
   *
   * Flips the pipeline `resourceStatus` (ENABLED ⇄ DISABLED). Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED and runs a Compare-And-Set against the row `_version`. Drift → `412`, missing header → `428`.
   *
   * `PATCH /api/v1/admin/audio/pipelines/{id}/toggle` — `AudioPipelineController.toggle`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  toggle(id: string, body: TogglePipelineRequest, options: AdminRequestOptions & { ifMatch: IfMatchPrecondition }): Promise<PipelineResponse> {
    return this.requestWithPrecondition<PipelineResponse>({
      method: 'PATCH',
      path: `admin/audio/pipelines/${encodePathSegment(String(id))}/toggle`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List config-version snapshots for a pipeline
   *
   * `GET /api/v1/admin/audio/pipelines/{id}/versions` — `AudioPipelineController.listVersions`.
   */
  listVersions(id: string, options: AdminRequestOptions = {}): Promise<PipelineVersionResponse[]> {
    return this.request<PipelineVersionResponse[]>({
      method: 'GET',
      path: `admin/audio/pipelines/${encodePathSegment(String(id))}/versions`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get one config-version snapshot by version number
   *
   * `GET /api/v1/admin/audio/pipelines/{id}/versions/{versionNumber}` — `AudioPipelineController.getVersion`.
   */
  getVersion(id: string, versionNumber: number, options: AdminRequestOptions = {}): Promise<PipelineVersionResponse> {
    return this.request<PipelineVersionResponse>({
      method: 'GET',
      path: `admin/audio/pipelines/${encodePathSegment(String(id))}/versions/${encodePathSegment(String(versionNumber))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single PaginatedPipelineResponse
   *
   * `GET /api/v1/admin/audio/pipelines/list` — `AudioPipelineController.list`.
   */
  list(options: AdminRequestOptions & { query?: { limit?: number; page?: number } } = {}): Promise<PaginatedPipelineResponse> {
    return this.request<PaginatedPipelineResponse>({
      method: 'GET',
      path: 'admin/audio/pipelines/list',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single PipelineResponse by slug
   *
   * `GET /api/v1/admin/audio/pipelines/slug/{slug}` — `AudioPipelineController.fetchBySlug`.
   */
  fetchBySlug(slug: string, options: AdminRequestOptions = {}): Promise<PipelineResponse> {
    return this.request<PipelineResponse>({
      method: 'GET',
      path: `admin/audio/pipelines/slug/${encodePathSegment(String(slug))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Creating a PipelineResponse
   *
   * DEPRECATED (TASK-861 — removed in R4; use /api/v1/admin/agents (task SPEECH_TO_TEXT, TASK-863)).
   *
   * `POST /api/v1/admin/audio/pipelines/validate` — `AudioPipelineController.validateYaml`.
   */
  validateYaml(body: ValidateYamlRequest, options: AdminRequestOptions = {}): Promise<PipelineResponse> {
    return this.request<PipelineResponse>({
      method: 'POST',
      path: 'admin/audio/pipelines/validate',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
