/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions, IfMatchPrecondition } from './admin-resource';
import type { ChangelogEntryResponse, CreateChangelogEntryRequest, UpdateChangelogEntryRequest } from './schemas';

/**
 * `hope.admin.changelog` — the `svc:admin:changelog:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:changelog:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller ChangelogAdminController
 * (4 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminChangelogResource extends AdminResource {
  readonly svcScope = 'svc:admin:changelog:manage';

  /**
   * Create a release note (always DRAFT)
   *
   * CI creates DRAFTs by this route. Nothing here makes an entry visible — publishing is a separate human action.
   *
   * `POST /api/v1/admin/changelog` — `ChangelogAdminController.create`.
   */
  create(body: CreateChangelogEntryRequest, options: AdminRequestOptions = {}): Promise<ChangelogEntryResponse> {
    return this.request<ChangelogEntryResponse>({
      method: 'POST',
      path: 'admin/changelog',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Read a release note for editing (DRAFT included)
   *
   * The authoring read. Answers a strong `ETag` carrying `_version`, which `PATCH` and `publish` both require as `If-Match` — this route is how the client learns it. The reader plane (`GET /changelog`) is unaffected and still serves PUBLISHED entries only.
   *
   * `GET /api/v1/admin/changelog/{id}` — `ChangelogAdminController.get`.
   */
  get(id: string, options: AdminRequestOptions = {}): Promise<ChangelogEntryResponse> {
    return this.request<ChangelogEntryResponse>({
      method: 'GET',
      path: `admin/changelog/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Edit a release note (If-Match OCC)
   *
   * Sparse patch. `If-Match` (RFC 7232) is REQUIRED and CASes against `_version`; drift → 412, missing → 428.
   *
   * `PATCH /api/v1/admin/changelog/{id}` — `ChangelogAdminController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  update(
    id: string,
    body: UpdateChangelogEntryRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<ChangelogEntryResponse> {
    return this.requestWithPrecondition<ChangelogEntryResponse>({
      method: 'PATCH',
      path: `admin/changelog/${encodePathSegment(String(id))}`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Publish a release note
   *
   * The ONLY path from DRAFT to PUBLISHED, and always a human action — CI never publishes. Publishing an already-published entry is rejected with 409.
   *
   * `POST /api/v1/admin/changelog/{id}/publish` — `ChangelogAdminController.publish`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  publish(id: string, options: AdminRequestOptions & { ifMatch: IfMatchPrecondition }): Promise<ChangelogEntryResponse> {
    return this.requestWithPrecondition<ChangelogEntryResponse>({
      method: 'POST',
      path: `admin/changelog/${encodePathSegment(String(id))}/publish`,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
