/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions, IfMatchPrecondition } from './admin-resource';
import type {
  ConsultationContextSchemaResponse,
  ConsultationContextSchemaVersionResponse,
  ContextSchemaUsagesResponse,
  CreateConsultationContextSchemaRequest,
  PinConsultationContextSchemaVersionRequest,
  PublishConsultationContextSchemaRequest,
  UpdateConsultationContextSchemaRequest,
} from './schemas';

/**
 * `hope.admin.consultationContextSchema` — the `svc:admin:consultation-context-schema:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:consultation-context-schema:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller ConsultationContextSchemaAdminController
 * (9 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminConsultationContextSchemaResource extends AdminResource {
  readonly svcScope = 'svc:admin:consultation-context-schema:manage';

  /**
   * List the caller tenant's consultation context schemas
   *
   * `GET /api/v1/admin/consultation-context-schemas` — `ConsultationContextSchemaAdminController.list`.
   */
  list(options: AdminRequestOptions = {}): Promise<ConsultationContextSchemaResponse[]> {
    return this.request<ConsultationContextSchemaResponse[]>({
      method: 'GET',
      path: 'admin/consultation-context-schemas',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Create a DRAFT context schema
   *
   * A schema is always born DRAFT with no pinned version — `POST :id/publish` is the only way to get one.
   *
   * `POST /api/v1/admin/consultation-context-schemas` — `ConsultationContextSchemaAdminController.create`.
   */
  create(body: CreateConsultationContextSchemaRequest, options: AdminRequestOptions = {}): Promise<ConsultationContextSchemaResponse> {
    return this.request<ConsultationContextSchemaResponse>({
      method: 'POST',
      path: 'admin/consultation-context-schemas',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Soft-delete a context schema
   *
   * Published versions are NOT removed — a ContextItem stamped with one must resolve it forever.
   *
   * `DELETE /api/v1/admin/consultation-context-schemas/{id}` — `ConsultationContextSchemaAdminController.deleteById`.
   */
  deleteById(id: string, options: AdminRequestOptions = {}): Promise<ConsultationContextSchemaResponse> {
    return this.request<ConsultationContextSchemaResponse>({
      method: 'DELETE',
      path: `admin/consultation-context-schemas/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get one context schema by id
   *
   * `GET /api/v1/admin/consultation-context-schemas/{id}` — `ConsultationContextSchemaAdminController.getById`.
   */
  getById(id: string, options: AdminRequestOptions = {}): Promise<ConsultationContextSchemaResponse> {
    return this.request<ConsultationContextSchemaResponse>({
      method: 'GET',
      path: `admin/consultation-context-schemas/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Update schema metadata under optimistic concurrency
   *
   * Metadata only — the DECLARATION is never edited in place (`POST :id/publish` writes a new immutable version). `If-Match` (RFC 7232) is REQUIRED; when present it overrides the body-field `expectedVersion`. Version drift answers 412, a missing header 428.
   *
   * `PATCH /api/v1/admin/consultation-context-schemas/{id}` — `ConsultationContextSchemaAdminController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  update(
    id: string,
    body: UpdateConsultationContextSchemaRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<ConsultationContextSchemaResponse> {
    return this.requestWithPrecondition<ConsultationContextSchemaResponse>({
      method: 'PATCH',
      path: `admin/consultation-context-schemas/${encodePathSegment(String(id))}`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Move the pin to an already-published version
   *
   * The rollback path: discovery and payload validation immediately serve the named version instead.
   *
   * `POST /api/v1/admin/consultation-context-schemas/{id}/pin` — `ConsultationContextSchemaAdminController.pin`.
   */
  pin(id: string, body: PinConsultationContextSchemaVersionRequest, options: AdminRequestOptions = {}): Promise<ConsultationContextSchemaResponse> {
    return this.request<ConsultationContextSchemaResponse>({
      method: 'POST',
      path: `admin/consultation-context-schemas/${encodePathSegment(String(id))}/pin`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Validate a definition, publish it as a new immutable version, and pin it
   *
   * Each `kinds[].primitive` must be one of the five platform primitives; `fields` must stay inside the authorable JSON Schema subset (no `if`/`then`/`else`; `oneOf` only with an explicit discriminator). Re-publishing an IDENTICAL definition is a no-op: no version row, no pin move, and the discovery ETag does not change. A BREAKING change (removed/renamed kind or property, changed primitive/type, widened `required`) is refused with 400 listing every break unless `allowBreakingChange` is set.
   *
   * `POST /api/v1/admin/consultation-context-schemas/{id}/publish` — `ConsultationContextSchemaAdminController.publish`.
   */
  publish(id: string, body: PublishConsultationContextSchemaRequest, options: AdminRequestOptions = {}): Promise<ConsultationContextSchemaResponse> {
    return this.request<ConsultationContextSchemaResponse>({
      method: 'POST',
      path: `admin/consultation-context-schemas/${encodePathSegment(String(id))}/publish`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List the workflows and agents bound to a context schema, with a verdict per consumer
   *
   * Answers "what does changing this schema break?" BEFORE an admin publishes. Every workflow and agent bound to the schema is listed with its `binding` (`latest` = its trigger re-reads the tenant pin at dispatch; `pinned` = it keeps the version it was published with) and a `verdict` against `againstVersion`. A follow-latest consumer always `accepts`. A PINNED one `refuses` when the target version declares a kind its frozen trigger does not, and each such kind is named in `problems`; `unknown` means the consumer's compiled configuration could not be read, which is reported rather than silently treated as acceptance. This is the same document `POST :id/publish` and `POST :id/pin` return as `impact`, and the same one a publish refused with `SCHEMA_IMPACT_UNACKNOWLEDGED` carries — a preview and the write that follows it can never disagree.
   *
   * `GET /api/v1/admin/consultation-context-schemas/{id}/usages` — `ConsultationContextSchemaAdminController.usages`.
   */
  usages(id: string, options: AdminRequestOptions & { query?: { againstVersion?: number } } = {}): Promise<ContextSchemaUsagesResponse> {
    return this.request<ContextSchemaUsagesResponse>({
      method: 'GET',
      path: `admin/consultation-context-schemas/${encodePathSegment(String(id))}/usages`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List the immutable published versions of a context schema, newest first
   *
   * Versions are never edited or deleted — a correction is a new version.
   *
   * `GET /api/v1/admin/consultation-context-schemas/{id}/versions` — `ConsultationContextSchemaAdminController.listVersions`.
   */
  listVersions(id: string, options: AdminRequestOptions = {}): Promise<ConsultationContextSchemaVersionResponse[]> {
    return this.request<ConsultationContextSchemaVersionResponse[]>({
      method: 'GET',
      path: `admin/consultation-context-schemas/${encodePathSegment(String(id))}/versions`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
