/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions } from './admin-resource';
import type { ConsultationAggregateResponse, ConsultationResponse, PaginatedResponse } from './schemas';

/**
 * `hope.admin.consultationAdmin` — the `svc:admin:consultation-admin:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:consultation-admin:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller AdminConsultationController
 * (3 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminConsultationAdminResource extends AdminResource {
  readonly svcScope = 'svc:admin:consultation-admin:manage';

  /**
   * Retrieving multiple ConsultationResponses
   *
   * `GET /api/v1/admin/consultations` — `AdminConsultationController.list`.
   */
  list(
    options: AdminRequestOptions & {
      query?: {
        departmentId?: string;
        doctorId?: string;
        limit?: number;
        page?: number;
        patientId?: string;
        status?:
          | 'OPEN'
          | 'RECORDING'
          | 'DRAFT_PENDING_SENSORS'
          | 'PENDING_REVIEW'
          | 'SIGNED'
          | 'CLOSED'
          | 'REOPENED'
          | 'PRIMED'
          | 'DRAINING'
          | 'TIMED_OUT'
          | 'CLOSED_COMPLETE'
          | 'CLOSED_INCOMPLETE';
      };
    } = {},
  ): Promise<PaginatedResponse & { data?: ConsultationResponse[] }> {
    return this.request<PaginatedResponse & { data?: ConsultationResponse[] }>({
      method: 'GET',
      path: 'admin/consultations',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single ConsultationResponse by id
   *
   * `GET /api/v1/admin/consultations/{id}` — `AdminConsultationController.getById`.
   */
  getById(id: string, options: AdminRequestOptions = {}): Promise<ConsultationResponse> {
    return this.request<ConsultationResponse>({
      method: 'GET',
      path: `admin/consultations/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Server-side, zero-filled new/revisit aggregation over a date range. Scope follows the same model as `list`: a SUPER_ADMIN with no working tenant aggregates cross-tenant; everyone else is pinned to their CLS tenant. Declared BEFORE the `:id` route so `GET /aggregate` is not captured by the `:id` param matcher.
   *
   * `GET /api/v1/admin/consultations/aggregate` — `AdminConsultationController.aggregate`.
   */
  aggregate(
    options: AdminRequestOptions & { query?: { from: string; granularity?: 'day' | 'month'; to: string } } = {},
  ): Promise<ConsultationAggregateResponse> {
    return this.request<ConsultationAggregateResponse>({
      method: 'GET',
      path: 'admin/consultations/aggregate',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
