/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminListOptions, AdminListQuery, AdminRequestOptions, IfMatchPrecondition, PaginatedPage } from './admin-resource';
import type {
  CloneDepartmentAgentRequest,
  CreateDepartmentAgentRequest,
  DepartmentAgentResponse,
  DepartmentAgentVersionResponse,
  PinDepartmentAgentRequest,
  ResyncDepartmentAgentsRequest,
  UpdateDepartmentAgentRequest,
} from './schemas';

/**
 * `hope.admin.departmentAgent` — the `svc:admin:department-agent:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:department-agent:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controllers DepartmentAgentController, DepartmentAgentResyncController
 * (10 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminDepartmentAgentResource extends AdminResource {
  readonly svcScope = 'svc:admin:department-agent:manage';

  /**
   * Retrieving a single PaginatedDepartmentAgentResponse
   *
   * `GET /api/v1/admin/department-agents` — `DepartmentAgentController.list`.
   *
   * Returns ONE page. `page` is 0-based and both `page` and `limit` are always sent explicitly — the gateway echoes RAW query values back, so the response's own `page`/`limit` are not usable as loop state. Use {@link listIterate} to walk every page.
   */
  list(options: AdminListOptions & { query?: AdminListQuery & { departmentId?: string } } = {}): Promise<PaginatedPage<DepartmentAgentResponse>> {
    return this.listPage<DepartmentAgentResponse>('admin/department-agents', options);
  }

  /**
   * Retrieving a single PaginatedDepartmentAgentResponse
   *
   * `GET /api/v1/admin/department-agents` — `DepartmentAgentController.list`.
   *
   * Walks every page, yielding rows: `for await (const row of …)`. Pagination is driven from the REQUEST side; a failure on page N propagates after page N-1's rows, so "the list ended" and "the list broke" never look alike.
   */
  listIterate(
    options: AdminListOptions & { query?: AdminListQuery & { departmentId?: string } } = {},
  ): AsyncGenerator<DepartmentAgentResponse, void, undefined> {
    return this.listAll<DepartmentAgentResponse>('admin/department-agents', options);
  }

  /**
   * Creating a DepartmentAgentResponse
   *
   * `POST /api/v1/admin/department-agents` — `DepartmentAgentController.create`.
   */
  create(body: CreateDepartmentAgentRequest, options: AdminRequestOptions = {}): Promise<DepartmentAgentResponse> {
    return this.request<DepartmentAgentResponse>({
      method: 'POST',
      path: 'admin/department-agents',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Deleting a DepartmentAgentResponse by id
   *
   * `DELETE /api/v1/admin/department-agents/{id}` — `DepartmentAgentController.delete`.
   */
  delete(id: string, options: AdminRequestOptions = {}): Promise<DepartmentAgentResponse> {
    return this.request<DepartmentAgentResponse>({
      method: 'DELETE',
      path: `admin/department-agents/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single DepartmentAgentResponse by id
   *
   * `GET /api/v1/admin/department-agents/{id}` — `DepartmentAgentController.getById`.
   */
  getById(id: string, options: AdminRequestOptions = {}): Promise<DepartmentAgentResponse> {
    return this.request<DepartmentAgentResponse>({
      method: 'GET',
      path: `admin/department-agents/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Updating a DepartmentAgentResponse by id
   *
   * Updates one agent row. Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED, and the server runs a Compare-And-Set against the row's `_version`. On version drift the response is `412 Precondition Failed`; missing header is `428 Precondition Required`.
   *
   * `PATCH /api/v1/admin/department-agents/{id}` — `DepartmentAgentController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  update(
    id: string,
    body: UpdateDepartmentAgentRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<DepartmentAgentResponse> {
    return this.requestWithPrecondition<DepartmentAgentResponse>({
      method: 'PATCH',
      path: `admin/department-agents/${encodePathSegment(String(id))}`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Clone an agent into a new editable copy (clone to customize)
   *
   * Deep-copies the bound PromptTemplate into an editable DRAFT tenant template and creates a new, UNLOCKED agent bound to it (carrying lineage). The source row is left untouched.
   *
   * `POST /api/v1/admin/department-agents/{id}/clone` — `DepartmentAgentController.clone`.
   */
  clone(id: string, body: CloneDepartmentAgentRequest, options: AdminRequestOptions = {}): Promise<DepartmentAgentResponse> {
    return this.request<DepartmentAgentResponse>({
      method: 'POST',
      path: `admin/department-agents/${encodePathSegment(String(id))}/clone`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Pin the agent to a PromptVersion number, or null to track latest APPROVED
   *
   * `POST /api/v1/admin/department-agents/{id}/pin` — `DepartmentAgentController.pin`.
   */
  pin(id: string, body: PinDepartmentAgentRequest, options: AdminRequestOptions = {}): Promise<DepartmentAgentResponse> {
    return this.request<DepartmentAgentResponse>({
      method: 'POST',
      path: `admin/department-agents/${encodePathSegment(String(id))}/pin`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Mark this agent as the department default (atomic flip)
   *
   * `POST /api/v1/admin/department-agents/{id}/set-default` — `DepartmentAgentController.setDefault`.
   */
  setDefault(id: string, options: AdminRequestOptions = {}): Promise<DepartmentAgentResponse> {
    return this.request<DepartmentAgentResponse>({
      method: 'POST',
      path: `admin/department-agents/${encodePathSegment(String(id))}/set-default`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List the immutable loop-configuration versions of an agent, newest first
   *
   * Versions are never edited or deleted — a correction is a new version.
   *
   * `GET /api/v1/admin/department-agents/{id}/versions` — `DepartmentAgentController.listVersions`.
   */
  listVersions(id: string, options: AdminRequestOptions = {}): Promise<DepartmentAgentVersionResponse[]> {
    return this.request<DepartmentAgentVersionResponse[]>({
      method: 'GET',
      path: `admin/department-agents/${encodePathSegment(String(id))}/versions`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Resync tenant DepartmentAgent catalogs against the SYSTEM golden library
   *
   * Reconciles tenants against the SYSTEM agent golden library: missing golden agents are cloned in as locked copies (with an APPROVED template snapshot), and pristine locked copies are fast-forwarded to the golden template's current content. UNLOCKED agents — customized, and rows the lineage could not prove pristine — are NEVER touched. With `{ tenantId }` reconciles that one tenant; with no body sweeps every non-SYSTEM tenant. Idempotent: re-running returns an all-zero summary.
   *
   * `POST /api/v1/admin/department-agents/resync` — `DepartmentAgentResyncController.resync`.
   */
  resync(body: ResyncDepartmentAgentsRequest, options: AdminRequestOptions = {}): Promise<unknown> {
    return this.request<unknown>({
      method: 'POST',
      path: 'admin/department-agents/resync',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
