/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminListOptions, AdminListQuery, AdminRequestOptions, IfMatchPrecondition, PaginatedPage } from './admin-resource';
import type {
  CreateDepartmentRequest,
  DepartmentResponse,
  PaginatedResponse,
  UpdateDepartmentPromptConfigRequest,
  UpdateDepartmentRequest,
} from './schemas';

/**
 * `hope.admin.department` — the `svc:admin:department:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:department:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller DepartmentController
 * (10 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminDepartmentResource extends AdminResource {
  readonly svcScope = 'svc:admin:department:manage';

  /**
   * Retrieving multiple DepartmentResponses
   *
   * `GET /api/v1/admin/departments` — `DepartmentController.fetchAll`.
   */
  fetchAll(
    options: AdminRequestOptions & { query?: { includeDisabled?: boolean } } = {},
  ): Promise<PaginatedResponse & { data?: DepartmentResponse[] }> {
    return this.request<PaginatedResponse & { data?: DepartmentResponse[] }>({
      method: 'GET',
      path: 'admin/departments',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Creating a DepartmentResponse
   *
   * `POST /api/v1/admin/departments` — `DepartmentController.create`.
   */
  create(body: CreateDepartmentRequest, options: AdminRequestOptions = {}): Promise<DepartmentResponse> {
    return this.request<DepartmentResponse>({
      method: 'POST',
      path: 'admin/departments',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Deleting a DepartmentResponse by id
   *
   * `DELETE /api/v1/admin/departments/{id}` — `DepartmentController.delete`.
   */
  delete(id: string, options: AdminRequestOptions = {}): Promise<DepartmentResponse> {
    return this.request<DepartmentResponse>({
      method: 'DELETE',
      path: `admin/departments/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single DepartmentResponse by id
   *
   * `GET /api/v1/admin/departments/{id}` — `DepartmentController.fetchById`.
   */
  fetchById(id: string, options: AdminRequestOptions = {}): Promise<DepartmentResponse> {
    return this.request<DepartmentResponse>({
      method: 'GET',
      path: `admin/departments/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Updating a DepartmentResponse by id
   *
   * Updates one department row. Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED, and the server runs a Compare-And-Set against the row's `_version`. When the header is present, its value overrides the body-field `expectedVersion`. On version drift the response is `412 Precondition Failed`; missing header is `428 Precondition Required`.
   *
   * `PATCH /api/v1/admin/departments/{id}` — `DepartmentController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  update(id: string, body: UpdateDepartmentRequest, options: AdminRequestOptions & { ifMatch: IfMatchPrecondition }): Promise<DepartmentResponse> {
    return this.requestWithPrecondition<DepartmentResponse>({
      method: 'PATCH',
      path: `admin/departments/${encodePathSegment(String(id))}`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving multiple DepartmentResponses by id
   *
   * `GET /api/v1/admin/departments/{id}/children` — `DepartmentController.fetchChildren`.
   */
  fetchChildren(id: string, options: AdminRequestOptions = {}): Promise<PaginatedResponse & { data?: DepartmentResponse[] }> {
    return this.request<PaginatedResponse & { data?: DepartmentResponse[] }>({
      method: 'GET',
      path: `admin/departments/${encodePathSegment(String(id))}/children`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Updating a DepartmentResponse by id (prompt config)
   *
   * `PATCH /api/v1/admin/departments/{id}/prompt-config` — `DepartmentController.updatePromptConfig`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  updatePromptConfig(
    id: string,
    body: UpdateDepartmentPromptConfigRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<DepartmentResponse> {
    return this.requestWithPrecondition<DepartmentResponse>({
      method: 'PATCH',
      path: `admin/departments/${encodePathSegment(String(id))}/prompt-config`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List a department's members (users)
   *
   * `GET /api/v1/admin/departments/{id}/users` — `DepartmentController.fetchUsers`.
   *
   * Returns ONE page. `page` is 0-based and both `page` and `limit` are always sent explicitly — the gateway echoes RAW query values back, so the response's own `page`/`limit` are not usable as loop state. Use {@link fetchUsersIterate} to walk every page.
   */
  fetchUsers(id: string, options: AdminListOptions & { query?: AdminListQuery & { pageSize?: number } } = {}): Promise<PaginatedPage<unknown[]>> {
    return this.listPage<unknown[]>(`admin/departments/${encodePathSegment(String(id))}/users`, options);
  }

  /**
   * List a department's members (users)
   *
   * `GET /api/v1/admin/departments/{id}/users` — `DepartmentController.fetchUsers`.
   *
   * Walks every page, yielding rows: `for await (const row of …)`. Pagination is driven from the REQUEST side; a failure on page N propagates after page N-1's rows, so "the list ended" and "the list broke" never look alike.
   */
  fetchUsersIterate(
    id: string,
    options: AdminListOptions & { query?: AdminListQuery & { pageSize?: number } } = {},
  ): AsyncGenerator<unknown[], void, undefined> {
    return this.listAll<unknown[]>(`admin/departments/${encodePathSegment(String(id))}/users`, options);
  }

  /**
   * Retrieving a single DepartmentResponse by code
   *
   * `GET /api/v1/admin/departments/code/{code}` — `DepartmentController.fetchByCode`.
   */
  fetchByCode(code: string, options: AdminRequestOptions = {}): Promise<DepartmentResponse> {
    return this.request<DepartmentResponse>({
      method: 'GET',
      path: `admin/departments/code/${encodePathSegment(String(code))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving multiple DepartmentResponses
   *
   * `GET /api/v1/admin/departments/roots` — `DepartmentController.fetchRoots`.
   */
  fetchRoots(options: AdminRequestOptions = {}): Promise<PaginatedResponse & { data?: DepartmentResponse[] }> {
    return this.request<PaginatedResponse & { data?: DepartmentResponse[] }>({
      method: 'GET',
      path: 'admin/departments/roots',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
