/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions, IfMatchPrecondition } from './admin-resource';
import type {
  DnaDashboardResponse,
  DnaErasureResponse,
  DnaJobResponseDto,
  DnaJobStatusResponseDto,
  DnaReportResponse,
  DnaVersionResponse,
  GenerateDnaReportRequest,
  PaginatedResponse,
  UpdateDnaReportRequest,
} from './schemas';

/**
 * `hope.admin.dnaWritingStyle` — the `svc:admin:dna-writing-style:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:dna-writing-style:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller DnaWritingStyleAdminController
 * (9 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminDnaWritingStyleResource extends AdminResource {
  readonly svcScope = 'svc:admin:dna-writing-style:manage';

  /**
   * Retrieving multiple DnaReportResponses
   *
   * `GET /api/v1/admin/dna-writing-styles` — `DnaWritingStyleAdminController.list`.
   */
  list(
    options: AdminRequestOptions & {
      query?: { doctorId?: string; includeDisabled?: boolean; limit?: number; page?: number; tenantId?: string };
    } = {},
  ): Promise<PaginatedResponse & { data?: DnaReportResponse[] }> {
    return this.request<PaginatedResponse & { data?: DnaReportResponse[] }>({
      method: 'GET',
      path: 'admin/dna-writing-styles',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Updating a DnaReportResponse by reportId
   *
   * Updates one DNA writing-style report row. Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED and the server runs a Compare-And-Set against the row's `_version` column (DISTINCT from `currentVersionNumber`, the DnaVersion history counter). When the header is present, its value overrides the body-field `expectedVersion`. On version drift the response is `412 Precondition Failed`; a missing header is `428 Precondition Required`.
   *
   * `PATCH /api/v1/admin/dna-writing-styles/{reportId}` — `DnaWritingStyleAdminController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  update(
    reportId: string,
    body: UpdateDnaReportRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<DnaReportResponse> {
    return this.requestWithPrecondition<DnaReportResponse>({
      method: 'PATCH',
      path: `admin/dna-writing-styles/${encodePathSegment(String(reportId))}`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving multiple DnaVersionResponses by reportId
   *
   * `GET /api/v1/admin/dna-writing-styles/{reportId}/versions` — `DnaWritingStyleAdminController.getVersions`.
   */
  getVersions(reportId: string, options: AdminRequestOptions = {}): Promise<PaginatedResponse & { data?: DnaVersionResponse[] }> {
    return this.request<PaginatedResponse & { data?: DnaVersionResponse[] }>({
      method: 'GET',
      path: `admin/dna-writing-styles/${encodePathSegment(String(reportId))}/versions`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * DNA aggregate dashboard (users with a style, avg versions, recent usage activity)
   *
   * `GET /api/v1/admin/dna-writing-styles/dashboard` — `DnaWritingStyleAdminController.getDashboard`.
   */
  getDashboard(options: AdminRequestOptions & { query?: { tenantId?: string } } = {}): Promise<DnaDashboardResponse> {
    return this.request<DnaDashboardResponse>({
      method: 'GET',
      path: 'admin/dna-writing-styles/dashboard',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Erase a doctor's entire learned DNA writing-style profile (admin)
   *
   * Soft-deletes every DNA writing-style report the doctor owns; the report versions are counted but left in place (they carry no resourceStatus column and become unreachable once the parent report is deleted). Complements the doctor's own self-service `DELETE /dna-writing-styles/my-style`. Idempotent — a doctor with no profile gets zero counts.
   *
   * `DELETE /api/v1/admin/dna-writing-styles/doctor/{doctorId}` — `DnaWritingStyleAdminController.resetDoctorProfile`.
   */
  resetDoctorProfile(doctorId: string, options: AdminRequestOptions = {}): Promise<DnaErasureResponse> {
    return this.request<DnaErasureResponse>({
      method: 'DELETE',
      path: `admin/dna-writing-styles/doctor/${encodePathSegment(String(doctorId))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Latest DNA writing-style report for a doctor (admin cross-user, tenant-scoped PHI-gated)
   *
   * `GET /api/v1/admin/dna-writing-styles/doctor/{doctorId}` — `DnaWritingStyleAdminController.getReportForDoctor`.
   */
  getReportForDoctor(doctorId: string, options: AdminRequestOptions = {}): Promise<DnaReportResponse> {
    return this.request<DnaReportResponse>({
      method: 'GET',
      path: `admin/dna-writing-styles/doctor/${encodePathSegment(String(doctorId))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Creating a DnaJobResponseDto by doctorId
   *
   * `POST /api/v1/admin/dna-writing-styles/generate/{doctorId}` — `DnaWritingStyleAdminController.generateForDoctor`.
   */
  generateForDoctor(doctorId: string, body: GenerateDnaReportRequest, options: AdminRequestOptions = {}): Promise<DnaJobResponseDto> {
    return this.request<DnaJobResponseDto>({
      method: 'POST',
      path: `admin/dna-writing-styles/generate/${encodePathSegment(String(doctorId))}`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get DNA generation job status
   *
   * `GET /api/v1/admin/dna-writing-styles/jobs/{jobId}` — `DnaWritingStyleAdminController.getJobStatus`.
   */
  getJobStatus(jobId: string, options: AdminRequestOptions = {}): Promise<DnaJobStatusResponseDto> {
    return this.request<DnaJobStatusResponseDto>({
      method: 'GET',
      path: `admin/dna-writing-styles/jobs/${encodePathSegment(String(jobId))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Stream DNA generation job status via SSE
   *
   * Accepts either `Authorization: Bearer <jwt>` or a single-use `?ticket=<ticket>` issued by `POST /auth/stream-ticket` with scope `dna_job:<jobId>`.
   *
   * `GET /api/v1/admin/dna-writing-styles/jobs/{jobId}/stream` — `DnaWritingStyleAdminController.streamJobStatus`.
   */
  streamJobStatus(jobId: string, options: AdminRequestOptions = {}): Promise<unknown> {
    return this.request<unknown>({
      method: 'GET',
      path: `admin/dna-writing-styles/jobs/${encodePathSegment(String(jobId))}/stream`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
