/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions } from './admin-resource';
import type {
  EntitlementCapabilitiesResponse,
  EntitlementsEnabledResponse,
  PlanEntitlementResponse,
  SetEnforcementEnabledRequest,
  TenantEntitlementResponse,
  TriggerDowngradeRequest,
  UpdatePlanEntitlementRequest,
  UpsertTenantEntitlementRequest,
} from './schemas';

/**
 * `hope.admin.entitlement` — the `svc:admin:entitlement:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:entitlement:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller EntitlementsAdminController
 * (11 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminEntitlementResource extends AdminResource {
  readonly svcScope = 'svc:admin:entitlement:manage';

  /**
   * Read the global entitlements enforcement kill-switch (Q9).
   *
   * `GET /api/v1/admin/entitlements/enabled` — `EntitlementsAdminController.getEnabled`.
   */
  getEnabled(options: AdminRequestOptions = {}): Promise<EntitlementsEnabledResponse> {
    return this.request<EntitlementsEnabledResponse>({
      method: 'GET',
      path: 'admin/entitlements/enabled',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Flip the global entitlements enforcement kill-switch (Q9).
   *
   * `PUT /api/v1/admin/entitlements/enabled` — `EntitlementsAdminController.setEnabled`.
   */
  setEnabled(body: SetEnforcementEnabledRequest, options: AdminRequestOptions = {}): Promise<EntitlementsEnabledResponse> {
    return this.request<EntitlementsEnabledResponse>({
      method: 'PUT',
      path: 'admin/entitlements/enabled',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List the per-plan default entitlement matrix.
   *
   * `GET /api/v1/admin/entitlements/plans` — `EntitlementsAdminController.listPlans`.
   */
  listPlans(options: AdminRequestOptions = {}): Promise<PlanEntitlementResponse[]> {
    return this.request<PlanEntitlementResponse[]>({
      method: 'GET',
      path: 'admin/entitlements/plans',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get a single plan default row.
   *
   * `GET /api/v1/admin/entitlements/plans/{plan}` — `EntitlementsAdminController.getPlan`.
   */
  getPlan(plan: string, options: AdminRequestOptions = {}): Promise<PlanEntitlementResponse> {
    return this.request<PlanEntitlementResponse>({
      method: 'GET',
      path: `admin/entitlements/plans/${encodePathSegment(String(plan))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Edit a plan default row (OCC via expectedVersion → 412 on drift).
   *
   * `PATCH /api/v1/admin/entitlements/plans/{plan}` — `EntitlementsAdminController.updatePlan`.
   */
  updatePlan(plan: string, body: UpdatePlanEntitlementRequest, options: AdminRequestOptions = {}): Promise<PlanEntitlementResponse> {
    return this.request<PlanEntitlementResponse>({
      method: 'PATCH',
      path: `admin/entitlements/plans/${encodePathSegment(String(plan))}`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Capability/usage snapshot for ANY tenant (super-admin view).
   *
   * `GET /api/v1/admin/entitlements/tenants/{tenantId}` — `EntitlementsAdminController.getTenantSnapshot`.
   */
  getTenantSnapshot(tenantId: string, options: AdminRequestOptions = {}): Promise<EntitlementCapabilitiesResponse> {
    return this.request<EntitlementCapabilitiesResponse>({
      method: 'GET',
      path: `admin/entitlements/tenants/${encodePathSegment(String(tenantId))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Downgrade a tenant plan (Q10). Plan change always applies; newest-first soft-disable of overflow rows runs only when enforcement is ON.
   *
   * `POST /api/v1/admin/entitlements/tenants/{tenantId}/downgrade` — `EntitlementsAdminController.triggerDowngrade`.
   */
  triggerDowngrade(tenantId: string, body: TriggerDowngradeRequest, options: AdminRequestOptions = {}): Promise<Record<string, unknown>> {
    return this.request<Record<string, unknown>>({
      method: 'POST',
      path: `admin/entitlements/tenants/${encodePathSegment(String(tenantId))}/downgrade`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Clear a tenant override back to plan inheritance (nulls the row; reversible — never deleted).
   *
   * `DELETE /api/v1/admin/entitlements/tenants/{tenantId}/override` — `EntitlementsAdminController.clearOverride`.
   */
  clearOverride(tenantId: string, options: AdminRequestOptions = {}): Promise<unknown> {
    return this.request<unknown>({
      method: 'DELETE',
      path: `admin/entitlements/tenants/${encodePathSegment(String(tenantId))}/override`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get a tenant's entitlement override (null = inherits the plan default).
   *
   * `GET /api/v1/admin/entitlements/tenants/{tenantId}/override` — `EntitlementsAdminController.getOverride`.
   */
  getOverride(tenantId: string, options: AdminRequestOptions = {}): Promise<TenantEntitlementResponse> {
    return this.request<TenantEntitlementResponse>({
      method: 'GET',
      path: `admin/entitlements/tenants/${encodePathSegment(String(tenantId))}/override`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Create-or-update a tenant override ("increase on demand", Q7). OCC required to update.
   *
   * `PUT /api/v1/admin/entitlements/tenants/{tenantId}/override` — `EntitlementsAdminController.upsertOverride`.
   */
  upsertOverride(tenantId: string, body: UpsertTenantEntitlementRequest, options: AdminRequestOptions = {}): Promise<TenantEntitlementResponse> {
    return this.request<TenantEntitlementResponse>({
      method: 'PUT',
      path: `admin/entitlements/tenants/${encodePathSegment(String(tenantId))}/override`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Manually run the trial-expiry sweep (Q4): downgrade every expired TRIAL tenant to STARTER, plan-only.
   *
   * `POST /api/v1/admin/entitlements/trial-expiry/run` — `EntitlementsAdminController.runTrialExpiry`.
   */
  runTrialExpiry(options: AdminRequestOptions = {}): Promise<Record<string, unknown>> {
    return this.request<Record<string, unknown>>({
      method: 'POST',
      path: 'admin/entitlements/trial-expiry/run',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
