/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import type { QueryValue } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions, IfMatchPrecondition } from './admin-resource';
import type {
  CreateGoldenCaseRequest,
  CreateGoldenSetRequest,
  EditBurdenResponse,
  EvalRunDetailResponse,
  EvalRunListResponse,
  EvalRunTriggerResponse,
  ExemplarCurationRequest,
  GateQueueResponse,
  GoldenCaseListResponse,
  GoldenCaseMetaResponse,
  GoldenSetListResponse,
  GoldenSetResponse,
  HarnessAuditListResponse,
  HarnessPolicyResponse,
  LiveDocEngineConfigResponse,
  LiveDocSessionStatsResponse,
  LiveDocSessionsListResponse,
  SignalWorkflowRequest,
  UpdateHarnessPolicyRequest,
  UpdateLiveDocEngineConfigRequest,
  WorkflowActionRequest,
} from './schemas';

/**
 * `hope.admin.harness` — the `svc:admin:harness:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:harness:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller HarnessAdminController
 * (26 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminHarnessResource extends AdminResource {
  readonly svcScope = 'svc:admin:harness:manage';

  /**
   * List the WORM audit trail (newest-first) + the chain-integrity verdict
   *
   * `GET /api/v1/admin/harness/audit` — `HarnessAdminController.listAudit`.
   */
  listAudit(
    options: AdminRequestOptions & {
      query?: {
        action?: QueryValue;
        consultationId?: QueryValue;
        from?: QueryValue;
        limit?: number;
        offset?: number;
        tenantId?: QueryValue;
        to?: QueryValue;
      };
    } = {},
  ): Promise<HarnessAuditListResponse> {
    return this.request<HarnessAuditListResponse>({
      method: 'GET',
      path: 'admin/harness/audit',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Derived clinician edit-burden telemetry for one consultation (edit distance, deferral rate, time-to-sign)
   *
   * Composes over already-persisted WORM audit rows + summary versions — read-only, no new capture, no workflow change. PHI hygiene: only derived scalars are returned; the note text itself never leaves the service.
   *
   * `GET /api/v1/admin/harness/edit-burden` — `HarnessAdminController.getEditBurden`.
   */
  getEditBurden(options: AdminRequestOptions & { query?: { consultationId: string; tenantId?: string } } = {}): Promise<EditBurdenResponse> {
    return this.request<EditBurdenResponse>({
      method: 'GET',
      path: 'admin/harness/edit-burden',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List eval runs (newest-first)
   *
   * `GET /api/v1/admin/harness/eval-runs` — `HarnessAdminController.listEvalRuns`.
   */
  listEvalRuns(
    options: AdminRequestOptions & { query?: { goldenSetId?: QueryValue; limit?: number; page?: number; tenantId?: QueryValue } } = {},
  ): Promise<EvalRunListResponse> {
    return this.request<EvalRunListResponse>({
      method: 'GET',
      path: 'admin/harness/eval-runs',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get one eval run with its per-case scores
   *
   * `GET /api/v1/admin/harness/eval-runs/{id}` — `HarnessAdminController.getEvalRun`.
   */
  getEvalRun(id: string, options: AdminRequestOptions & { query?: { tenantId?: QueryValue } } = {}): Promise<EvalRunDetailResponse> {
    return this.request<EvalRunDetailResponse>({
      method: 'GET',
      path: `admin/harness/eval-runs/${encodePathSegment(String(id))}`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Export gate-edit exemplar candidates for eval regression-corpus review
   *
   * Derived, PHI-REDACTED-at-write learning-loop rows mined from the clinician approve-vs-edit signal. Returned as UNREVIEWED candidates (`reviewStatus: PENDING_SME_REVIEW`) — admission to a golden set is a separate, SME-gated decision. Omitting `qualitySignal` returns both APPROVED_CLEAN and HEAVILY_EDITED, because a regression corpus needs the failures as well as the successes.
   *
   * `GET /api/v1/admin/harness/gate-edit-exemplars` — `HarnessAdminController.exportGateEditExemplars`.
   */
  exportGateEditExemplars(
    options: AdminRequestOptions & { query?: { departmentId?: QueryValue; limit?: number; qualitySignal?: QueryValue; tenantId?: QueryValue } } = {},
  ): Promise<Record<string, unknown>> {
    return this.request<Record<string, unknown>>({
      method: 'GET',
      path: 'admin/harness/gate-edit-exemplars',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Record the human curation verdict on one mined gate-edit exemplar
   *
   * Moves an exemplar between PENDING / APPROVED / REJECTED. Whether the verdict actually GATES prompt injection is governed separately by `agentic.fewshot.curationMode` (default `off`), so curating a corpus and enforcing the gate are two deliberate, independent steps.
   *
   * `PATCH /api/v1/admin/harness/gate-edit-exemplars/{id}/curation` — `HarnessAdminController.curateGateEditExemplar`.
   */
  curateGateEditExemplar(
    id: string,
    body: ExemplarCurationRequest,
    options: AdminRequestOptions & { query?: { tenantId?: QueryValue } } = {},
  ): Promise<unknown> {
    return this.request<unknown>({
      method: 'PATCH',
      path: `admin/harness/gate-edit-exemplars/${encodePathSegment(String(id))}/curation`,
      query: options.query,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List consultations awaiting clinician review with SLA/escalation from the effective policy
   *
   * `GET /api/v1/admin/harness/gate-queue` — `HarnessAdminController.gateQueue`.
   */
  gateQueue(options: AdminRequestOptions & { query?: { tenantId?: QueryValue } } = {}): Promise<GateQueueResponse> {
    return this.request<GateQueueResponse>({
      method: 'GET',
      path: 'admin/harness/gate-queue',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List golden sets (newest-first)
   *
   * `GET /api/v1/admin/harness/golden-sets` — `HarnessAdminController.listGoldenSets`.
   */
  listGoldenSets(
    options: AdminRequestOptions & { query?: { limit?: number; page?: number; tenantId?: QueryValue } } = {},
  ): Promise<GoldenSetListResponse> {
    return this.request<GoldenSetListResponse>({
      method: 'GET',
      path: 'admin/harness/golden-sets',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Create a golden set for the caller tenant
   *
   * `POST /api/v1/admin/harness/golden-sets` — `HarnessAdminController.createGoldenSet`.
   */
  createGoldenSet(
    body: CreateGoldenSetRequest,
    options: AdminRequestOptions & { query?: { tenantId?: QueryValue } } = {},
  ): Promise<GoldenSetResponse> {
    return this.request<GoldenSetResponse>({
      method: 'POST',
      path: 'admin/harness/golden-sets',
      query: options.query,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get one golden set
   *
   * `GET /api/v1/admin/harness/golden-sets/{id}` — `HarnessAdminController.getGoldenSet`.
   */
  getGoldenSet(id: string, options: AdminRequestOptions & { query?: { tenantId?: QueryValue } } = {}): Promise<GoldenSetResponse> {
    return this.request<GoldenSetResponse>({
      method: 'GET',
      path: `admin/harness/golden-sets/${encodePathSegment(String(id))}`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List a golden set's cases — PHI-safe metadata only
   *
   * The encrypted clinical payloads (`transcript`, `referenceNote`) are never surfaced through this plane.
   *
   * `GET /api/v1/admin/harness/golden-sets/{id}/cases` — `HarnessAdminController.listGoldenCases`.
   */
  listGoldenCases(
    id: string,
    options: AdminRequestOptions & { query?: { limit?: number; page?: number; tenantId?: QueryValue } } = {},
  ): Promise<GoldenCaseListResponse> {
    return this.request<GoldenCaseListResponse>({
      method: 'GET',
      path: `admin/harness/golden-sets/${encodePathSegment(String(id))}/cases`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Add a case to a golden set (PHI encrypted at rest, write-only)
   *
   * Returns the PHI-safe metadata projection — the transcript/reference note are never echoed back.
   *
   * `POST /api/v1/admin/harness/golden-sets/{id}/cases` — `HarnessAdminController.createGoldenCase`.
   */
  createGoldenCase(
    id: string,
    body: CreateGoldenCaseRequest,
    options: AdminRequestOptions & { query?: { tenantId?: QueryValue } } = {},
  ): Promise<GoldenCaseMetaResponse> {
    return this.request<GoldenCaseMetaResponse>({
      method: 'POST',
      path: `admin/harness/golden-sets/${encodePathSegment(String(id))}/cases`,
      query: options.query,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Run an eval over a golden set now (synchronous)
   *
   * Decrypts the set’s cases, runs the harness eval + release gate, persists the EvalRun (triggerType=MANUAL) + per-case scores, and returns the verdict. Tenant admins run their own sets; a SYSTEM set is super-admin-only (a cross-tenant id 404s).
   *
   * `POST /api/v1/admin/harness/golden-sets/{id}/run` — `HarnessAdminController.runGoldenSet`.
   */
  runGoldenSet(id: string, options: AdminRequestOptions & { query?: { tenantId?: QueryValue } } = {}): Promise<EvalRunTriggerResponse> {
    return this.request<EvalRunTriggerResponse>({
      method: 'POST',
      path: `admin/harness/golden-sets/${encodePathSegment(String(id))}/run`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Read the live-documentation engine kill-switch (super-admin / global scope)
   *
   * `GET /api/v1/admin/harness/live/config` — `HarnessAdminController.getLiveConfig`.
   */
  getLiveConfig(options: AdminRequestOptions = {}): Promise<LiveDocEngineConfigResponse> {
    return this.request<LiveDocEngineConfigResponse>({
      method: 'GET',
      path: 'admin/harness/live/config',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Toggle the live-documentation engine kill-switch (super-admin / global scope)
   *
   * Persists a Redis override that survives restart and fans out to all API instances (no redeploy). `enabled: false` engages the kill-switch — new `start()` calls are refused while in-flight sessions drain.
   *
   * `PATCH /api/v1/admin/harness/live/config` — `HarnessAdminController.updateLiveConfig`.
   */
  updateLiveConfig(body: UpdateLiveDocEngineConfigRequest, options: AdminRequestOptions = {}): Promise<LiveDocEngineConfigResponse> {
    return this.request<LiveDocEngineConfigResponse>({
      method: 'PATCH',
      path: 'admin/harness/live/config',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List the active live-documentation sessions (PHI-safe stats) for the caller tenant
   *
   * `GET /api/v1/admin/harness/live/sessions` — `HarnessAdminController.listLiveSessions`.
   */
  listLiveSessions(options: AdminRequestOptions & { query?: { tenantId?: QueryValue } } = {}): Promise<LiveDocSessionsListResponse> {
    return this.request<LiveDocSessionsListResponse>({
      method: 'GET',
      path: 'admin/harness/live/sessions',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get one live-documentation session's latest PHI-safe stats
   *
   * `GET /api/v1/admin/harness/live/sessions/{id}` — `HarnessAdminController.getLiveSession`.
   */
  getLiveSession(id: string, options: AdminRequestOptions & { query?: { tenantId?: QueryValue } } = {}): Promise<LiveDocSessionStatsResponse> {
    return this.request<LiveDocSessionStatsResponse>({
      method: 'GET',
      path: `admin/harness/live/sessions/${encodePathSegment(String(id))}`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get the caller tenant's effective harness policy (tenant row over global default over code default)
   *
   * `GET /api/v1/admin/harness/policy` — `HarnessAdminController.getPolicy`.
   */
  getPolicy(options: AdminRequestOptions = {}): Promise<HarnessPolicyResponse> {
    return this.request<HarnessPolicyResponse>({
      method: 'GET',
      path: 'admin/harness/policy',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Update the caller tenant's harness policy (created on first edit)
   *
   * Sparse patch over the effective policy. Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED and CAS'es against the row `_version`; drift → 412, missing → 428. Every edit appends a WORM `HarnessPolicyChange` (before/after) in the same transaction.
   *
   * `PATCH /api/v1/admin/harness/policy` — `HarnessAdminController.updatePolicy`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  updatePolicy(body: UpdateHarnessPolicyRequest, options: AdminRequestOptions & { ifMatch: IfMatchPrecondition }): Promise<HarnessPolicyResponse> {
    return this.requestWithPrecondition<HarnessPolicyResponse>({
      method: 'PATCH',
      path: 'admin/harness/policy',
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get the platform GLOBAL-DEFAULT harness policy (super-admin only)
   *
   * `GET /api/v1/admin/harness/policy/global` — `HarnessAdminController.getGlobalPolicy`.
   */
  getGlobalPolicy(options: AdminRequestOptions = {}): Promise<HarnessPolicyResponse> {
    return this.request<HarnessPolicyResponse>({
      method: 'GET',
      path: 'admin/harness/policy/global',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Update the platform GLOBAL-DEFAULT harness policy (super-admin only)
   *
   * Same OCC + WORM semantics as `PATCH policy`, targeting the SYSTEM-tenant GLOBAL-DEFAULT row. Restricted to platform super-admins.
   *
   * `PATCH /api/v1/admin/harness/policy/global` — `HarnessAdminController.updateGlobalPolicy`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  updateGlobalPolicy(
    body: UpdateHarnessPolicyRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<HarnessPolicyResponse> {
    return this.requestWithPrecondition<HarnessPolicyResponse>({
      method: 'PATCH',
      path: 'admin/harness/policy/global',
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List harness Temporal document workflows (tenant-filtered)
   *
   * `GET /api/v1/admin/harness/workflows` — `HarnessAdminController.listWorkflows`.
   */
  listWorkflows(
    options: AdminRequestOptions & {
      query?: { consultationId?: QueryValue; limit?: number; pageToken?: QueryValue; status?: QueryValue; tenantId?: QueryValue };
    } = {},
  ): Promise<Record<string, unknown>> {
    return this.request<Record<string, unknown>>({
      method: 'GET',
      path: 'admin/harness/workflows',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Describe one harness workflow (add ?phase=true for the loop phase)
   *
   * `GET /api/v1/admin/harness/workflows/{id}` — `HarnessAdminController.describeWorkflow`.
   */
  describeWorkflow(id: string, options: AdminRequestOptions & { query?: { phase?: boolean } } = {}): Promise<Record<string, unknown>> {
    return this.request<Record<string, unknown>>({
      method: 'GET',
      path: `admin/harness/workflows/${encodePathSegment(String(id))}`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Cancel a harness workflow (graceful). Tenant admins limited to their own tenant.
   *
   * `POST /api/v1/admin/harness/workflows/{id}/cancel` — `HarnessAdminController.cancelWorkflow`.
   */
  cancelWorkflow(id: string, body: WorkflowActionRequest, options: AdminRequestOptions = {}): Promise<Record<string, unknown>> {
    return this.request<Record<string, unknown>>({
      method: 'POST',
      path: `admin/harness/workflows/${encodePathSegment(String(id))}/cancel`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Send a signal to a harness workflow. Tenant admins limited to their own tenant.
   *
   * `POST /api/v1/admin/harness/workflows/{id}/signal` — `HarnessAdminController.signalWorkflow`.
   */
  signalWorkflow(id: string, body: SignalWorkflowRequest, options: AdminRequestOptions = {}): Promise<Record<string, unknown>> {
    return this.request<Record<string, unknown>>({
      method: 'POST',
      path: `admin/harness/workflows/${encodePathSegment(String(id))}/signal`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Terminate a harness workflow (forceful). Tenant admins limited to their own tenant.
   *
   * `POST /api/v1/admin/harness/workflows/{id}/terminate` — `HarnessAdminController.terminateWorkflow`.
   */
  terminateWorkflow(id: string, body: WorkflowActionRequest, options: AdminRequestOptions = {}): Promise<Record<string, unknown>> {
    return this.request<Record<string, unknown>>({
      method: 'POST',
      path: `admin/harness/workflows/${encodePathSegment(String(id))}/terminate`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
