/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminListOptions, AdminListQuery, AdminRequestOptions, PaginatedPage } from './admin-resource';
import type { KnowledgeChunkResponse, KnowledgeDocumentResponse } from './schemas';

/**
 * `hope.admin.knowledge` — the `svc:admin:knowledge:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:knowledge:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller KnowledgeController
 * (5 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminKnowledgeResource extends AdminResource {
  readonly svcScope = 'svc:admin:knowledge:manage';

  /**
   * Paginated list of the caller tenant's institutional-knowledge documents
   *
   * `GET /api/v1/admin/knowledge/documents` — `KnowledgeController.list`.
   *
   * Returns ONE page. `page` is 0-based and both `page` and `limit` are always sent explicitly — the gateway echoes RAW query values back, so the response's own `page`/`limit` are not usable as loop state. Use {@link listIterate} to walk every page.
   */
  list(options: AdminListOptions & { query?: AdminListQuery } = {}): Promise<PaginatedPage<KnowledgeDocumentResponse>> {
    return this.listPage<KnowledgeDocumentResponse>('admin/knowledge/documents', options);
  }

  /**
   * Paginated list of the caller tenant's institutional-knowledge documents
   *
   * `GET /api/v1/admin/knowledge/documents` — `KnowledgeController.list`.
   *
   * Walks every page, yielding rows: `for await (const row of …)`. Pagination is driven from the REQUEST side; a failure on page N propagates after page N-1's rows, so "the list ended" and "the list broke" never look alike.
   */
  listIterate(options: AdminListOptions & { query?: AdminListQuery } = {}): AsyncGenerator<KnowledgeDocumentResponse, void, undefined> {
    return this.listAll<KnowledgeDocumentResponse>('admin/knowledge/documents', options);
  }

  /**
   * Soft-delete a document and remove its vectors from Qdrant
   *
   * FAIL-CLOSED: the Qdrant vector cleanup is called first; if the harness cannot confirm the vectors are gone, the whole delete is aborted (the document stays listed) rather than leaving retrievable content behind a "deleted" row.
   *
   * `DELETE /api/v1/admin/knowledge/documents/{id}` — `KnowledgeController.deleteById`.
   */
  deleteById(id: string, options: AdminRequestOptions = {}): Promise<KnowledgeDocumentResponse> {
    return this.request<KnowledgeDocumentResponse>({
      method: 'DELETE',
      path: `admin/knowledge/documents/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get one knowledge document by id
   *
   * `GET /api/v1/admin/knowledge/documents/{id}` — `KnowledgeController.getById`.
   */
  getById(id: string, options: AdminRequestOptions = {}): Promise<KnowledgeDocumentResponse> {
    return this.request<KnowledgeDocumentResponse>({
      method: 'GET',
      path: `admin/knowledge/documents/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Archive a document (status -> ARCHIVED)
   *
   * A soft-touch, NOT a delete — the document stays listed and its chunks/vectors are untouched.
   *
   * `POST /api/v1/admin/knowledge/documents/{id}/archive` — `KnowledgeController.archive`.
   */
  archive(id: string, options: AdminRequestOptions = {}): Promise<KnowledgeDocumentResponse> {
    return this.request<KnowledgeDocumentResponse>({
      method: 'POST',
      path: `admin/knowledge/documents/${encodePathSegment(String(id))}/archive`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Paginated, decrypted chunk content for one document, ordered by chunkIndex
   *
   * Chunk TEXT is the sensitive read this route exists for — every call is force-audited (an AuditLog row is always written, unlike an ordinary list read).
   *
   * `GET /api/v1/admin/knowledge/documents/{id}/chunks` — `KnowledgeController.listChunks`.
   *
   * Returns ONE page. `page` is 0-based and both `page` and `limit` are always sent explicitly — the gateway echoes RAW query values back, so the response's own `page`/`limit` are not usable as loop state. Use {@link listChunksIterate} to walk every page.
   */
  listChunks(id: string, options: AdminListOptions & { query?: AdminListQuery } = {}): Promise<PaginatedPage<KnowledgeChunkResponse>> {
    return this.listPage<KnowledgeChunkResponse>(`admin/knowledge/documents/${encodePathSegment(String(id))}/chunks`, options);
  }

  /**
   * Paginated, decrypted chunk content for one document, ordered by chunkIndex
   *
   * Chunk TEXT is the sensitive read this route exists for — every call is force-audited (an AuditLog row is always written, unlike an ordinary list read).
   *
   * `GET /api/v1/admin/knowledge/documents/{id}/chunks` — `KnowledgeController.listChunks`.
   *
   * Walks every page, yielding rows: `for await (const row of …)`. Pagination is driven from the REQUEST side; a failure on page N propagates after page N-1's rows, so "the list ended" and "the list broke" never look alike.
   */
  listChunksIterate(
    id: string,
    options: AdminListOptions & { query?: AdminListQuery } = {},
  ): AsyncGenerator<KnowledgeChunkResponse, void, undefined> {
    return this.listAll<KnowledgeChunkResponse>(`admin/knowledge/documents/${encodePathSegment(String(id))}/chunks`, options);
  }
}
