/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { AdminResource } from './admin-resource';
import type { AdminRequestOptions } from './admin-resource';
import type { ConsumptionRollupResponse, OpenSocketsResponse, PlatformMetricsResponse } from './schemas';

/**
 * `hope.admin.platformMetrics` — the `svc:admin:platform-metrics:read` administration area.
 *
 * **Required service-account scope: `svc:admin:platform-metrics:read`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller PlatformMetricsController
 * (3 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminPlatformMetricsResource extends AdminResource {
  readonly svcScope = 'svc:admin:platform-metrics:read';

  /**
   * Consumption / usage roll-up (transcription minutes, summaries-24h, storage, consultations)
   *
   * `GET /api/v1/admin/platform/consumption` — `PlatformMetricsController.getConsumption`.
   */
  getConsumption(options: AdminRequestOptions & { query?: { tenantId?: string } } = {}): Promise<ConsumptionRollupResponse> {
    return this.request<ConsumptionRollupResponse>({
      method: 'GET',
      path: 'admin/platform/consumption',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Platform runtime metrics (requests/min, error rate, P95, sockets, models, series)
   *
   * `GET /api/v1/admin/platform/metrics` — `PlatformMetricsController.getMetrics`.
   */
  getMetrics(options: AdminRequestOptions = {}): Promise<PlatformMetricsResponse> {
    return this.request<PlatformMetricsResponse>({
      method: 'GET',
      path: 'admin/platform/metrics',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Open WebSocket count (live, multi-instance aggregate)
   *
   * `GET /api/v1/admin/platform/sockets` — `PlatformMetricsController.getSockets`.
   */
  getSockets(options: AdminRequestOptions = {}): Promise<OpenSocketsResponse> {
    return this.request<OpenSocketsResponse>({
      method: 'GET',
      path: 'admin/platform/sockets',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
