/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminListOptions, AdminListQuery, AdminRequestOptions, IfMatchPrecondition, PaginatedPage } from './admin-resource';
import type {
  ApprovePromptTemplateRequest,
  AssignDepartmentPromptRequest,
  CreatePromptTemplateRequest,
  DepartmentResponse,
  FinalizePromptTestRequest,
  PaginatedResponse,
  PromptTemplateResponse,
  PromptTestAckResponse,
  PromptTestResultResponse,
  PromptUsageAnalyticsResponse,
  PromptUsageRecordResponse,
  PromptUsageStatsResponse,
  PromptVersionDiffResponse,
  PromptVersionResponse,
  TestPromptTemplateRequest,
  UpdatePromptTemplateRequest,
} from './schemas';

/**
 * `hope.admin.promptTemplate` — the `svc:admin:prompt-template:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:prompt-template:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller PromptManagementController
 * (16 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminPromptTemplateResource extends AdminResource {
  readonly svcScope = 'svc:admin:prompt-template:manage';

  /**
   * Retrieving multiple PromptTemplateResponses
   *
   * `GET /api/v1/admin/prompt-templates` — `PromptManagementController.list`.
   */
  list(
    options: AdminRequestOptions & {
      query?: {
        category?: string;
        departmentId?: string;
        includeDisabled?: boolean;
        limit?: number;
        ownerUserId?: string;
        page?: number;
        scope?: 'TENANT_DEFAULT' | 'DEPARTMENT_DEFAULT' | 'USER_PERSONAL';
        search?: string;
        status?: 'DRAFT' | 'PUBLISHED';
      };
    } = {},
  ): Promise<PaginatedResponse & { data?: PromptTemplateResponse[] }> {
    return this.request<PaginatedResponse & { data?: PromptTemplateResponse[] }>({
      method: 'GET',
      path: 'admin/prompt-templates',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Creating a PromptTemplateResponse
   *
   * `POST /api/v1/admin/prompt-templates` — `PromptManagementController.create`.
   */
  create(body: CreatePromptTemplateRequest, options: AdminRequestOptions = {}): Promise<PromptTemplateResponse> {
    return this.request<PromptTemplateResponse>({
      method: 'POST',
      path: 'admin/prompt-templates',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Deleting a PromptTemplateResponse by id
   *
   * `DELETE /api/v1/admin/prompt-templates/{id}` — `PromptManagementController.remove`.
   */
  remove(id: string, options: AdminRequestOptions = {}): Promise<PromptTemplateResponse> {
    return this.request<PromptTemplateResponse>({
      method: 'DELETE',
      path: `admin/prompt-templates/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single PromptTemplateResponse by id
   *
   * `GET /api/v1/admin/prompt-templates/{id}` — `PromptManagementController.getById`.
   */
  getById(id: string, options: AdminRequestOptions = {}): Promise<PromptTemplateResponse> {
    return this.request<PromptTemplateResponse>({
      method: 'GET',
      path: `admin/prompt-templates/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Updating a PromptTemplateResponse by id
   *
   * Updates one prompt template row. Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED, and the server runs a Compare-And-Set against the row's `_version` column (distinct from `currentVersionNumber`, the PromptVersion history counter). When the header is present, its value overrides the body-field `expectedVersion`. On version drift the response is `412 Precondition Failed`; missing header is `428 Precondition Required`.
   *
   * `PATCH /api/v1/admin/prompt-templates/{id}` — `PromptManagementController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  update(
    id: string,
    body: UpdatePromptTemplateRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<PromptTemplateResponse> {
    return this.requestWithPrecondition<PromptTemplateResponse>({
      method: 'PATCH',
      path: `admin/prompt-templates/${encodePathSegment(String(id))}`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Approve a prompt template for clinical use
   *
   * Sets `status = APPROVED` (required by prompt resolution for clinical flows), pins a PromptVersion snapshot, and records a WORM-style audit change row. OD-3 split gate: SYSTEM/library templates are SUPER_ADMIN-only; tenant-owned templates require `manage:PromptTemplate` for that tenant — 403 otherwise. Optimistic concurrency: `If-Match` REQUIRED (folds over body `expectedVersion`); missing header → 428, version drift → 412. Idempotent: approving an already-APPROVED template returns the current row.
   *
   * `POST /api/v1/admin/prompt-templates/{id}/approve` — `PromptManagementController.approve`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  approve(
    id: string,
    body: ApprovePromptTemplateRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<PromptTemplateResponse> {
    return this.requestWithPrecondition<PromptTemplateResponse>({
      method: 'POST',
      path: `admin/prompt-templates/${encodePathSegment(String(id))}/approve`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Creating a PromptTestAckResponse by id
   *
   * Assembles the prompt, resolves the `text.test` provider/model and submits a STREAMING generation job to SMR, returning an ack in well under a second. Open the returned `streamUrl` over SSE for tokens, then call `POST :id/test/finalize` with the `taskId` to score and persist. `dryRun: true` returns the assembled prompt and generates NOTHING. This route no longer writes, so it carries NO `If-Match` requirement.
   *
   * `POST /api/v1/admin/prompt-templates/{id}/test` — `PromptManagementController.testTemplate`.
   */
  testTemplate(id: string, body: TestPromptTemplateRequest, options: AdminRequestOptions = {}): Promise<PromptTestAckResponse> {
    return this.request<PromptTestAckResponse>({
      method: 'POST',
      path: `admin/prompt-templates/${encodePathSegment(String(id))}/test`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Creating a PromptTestResultResponse by id
   *
   * Fetches the finished generation from SMR SERVER-SIDE by `taskId` (the generated text is never accepted from the request body), scores it, and persists `lastTestScore/lastTestOutput/lastTestAt`. This is the optimistic-concurrency write of the test flow: the `If-Match` header is REQUIRED and folds over any body-supplied `expectedVersion`. Version drift → 412.
   *
   * `POST /api/v1/admin/prompt-templates/{id}/test/finalize` — `PromptManagementController.finalizeTestTemplate`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  finalizeTestTemplate(
    id: string,
    body: FinalizePromptTestRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<PromptTestResultResponse> {
    return this.requestWithPrecondition<PromptTestResultResponse>({
      method: 'POST',
      path: `admin/prompt-templates/${encodePathSegment(String(id))}/test/finalize`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get usage statistics for a prompt template
   *
   * `GET /api/v1/admin/prompt-templates/{id}/usage` — `PromptManagementController.getUsageStats`.
   */
  getUsageStats(id: string, options: AdminRequestOptions = {}): Promise<PromptUsageStatsResponse> {
    return this.request<PromptUsageStatsResponse>({
      method: 'GET',
      path: `admin/prompt-templates/${encodePathSegment(String(id))}/usage`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving multiple PromptVersionResponses by id
   *
   * `GET /api/v1/admin/prompt-templates/{id}/versions` — `PromptManagementController.getVersions`.
   */
  getVersions(id: string, options: AdminRequestOptions = {}): Promise<PaginatedResponse & { data?: PromptVersionResponse[] }> {
    return this.request<PaginatedResponse & { data?: PromptVersionResponse[] }>({
      method: 'GET',
      path: `admin/prompt-templates/${encodePathSegment(String(id))}/versions`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Diff two versions of a prompt template (server-side)
   *
   * Returns a structured field-level diff (content + variables) plus a combined line diff between the "from" and "to" version numbers. Tenant-scoped: a cross-tenant/unknown template id is 404.
   *
   * `GET /api/v1/admin/prompt-templates/{id}/versions/{from}/diff/{to}` — `PromptManagementController.diffVersions`.
   */
  diffVersions(id: string, from: number, to: number, options: AdminRequestOptions = {}): Promise<PromptVersionDiffResponse> {
    return this.request<PromptVersionDiffResponse>({
      method: 'GET',
      path: `admin/prompt-templates/${encodePathSegment(String(id))}/versions/${encodePathSegment(String(from))}/diff/${encodePathSegment(String(to))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single PromptVersionResponse by id and versionNumber
   *
   * `GET /api/v1/admin/prompt-templates/{id}/versions/{versionNumber}` — `PromptManagementController.getVersion`.
   */
  getVersion(id: string, versionNumber: number, options: AdminRequestOptions = {}): Promise<PromptVersionResponse> {
    return this.request<PromptVersionResponse>({
      method: 'GET',
      path: `admin/prompt-templates/${encodePathSegment(String(id))}/versions/${encodePathSegment(String(versionNumber))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Creating a PromptTemplateResponse by id and versionNumber
   *
   * `POST /api/v1/admin/prompt-templates/{id}/versions/{versionNumber}/activate` — `PromptManagementController.activateVersion`.
   */
  activateVersion(id: string, versionNumber: number, options: AdminRequestOptions = {}): Promise<PromptTemplateResponse> {
    return this.request<PromptTemplateResponse>({
      method: 'POST',
      path: `admin/prompt-templates/${encodePathSegment(String(id))}/versions/${encodePathSegment(String(versionNumber))}/activate`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Usage analytics grouped by department / doctor / day
   *
   * `GET /api/v1/admin/prompt-templates/analytics/usage` — `PromptManagementController.getUsageAnalytics`.
   */
  getUsageAnalytics(options: AdminRequestOptions & { query?: { promptTemplateId?: string } } = {}): Promise<PromptUsageAnalyticsResponse> {
    return this.request<PromptUsageAnalyticsResponse>({
      method: 'GET',
      path: 'admin/prompt-templates/analytics/usage',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Assign prompt templates to a department
   *
   * `POST /api/v1/admin/prompt-templates/assign-department` — `PromptManagementController.assignDepartment`.
   */
  assignDepartment(body: AssignDepartmentPromptRequest, options: AdminRequestOptions = {}): Promise<DepartmentResponse> {
    return this.request<DepartmentResponse>({
      method: 'POST',
      path: 'admin/prompt-templates/assign-department',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Paginated prompt run history (PromptUsageRecord rows), newest first
   *
   * `GET /api/v1/admin/prompt-templates/usage-records` — `PromptManagementController.listUsageRecords`.
   *
   * Returns ONE page. `page` is 0-based and both `page` and `limit` are always sent explicitly — the gateway echoes RAW query values back, so the response's own `page`/`limit` are not usable as loop state. Use {@link listUsageRecordsIterate} to walk every page.
   */
  listUsageRecords(
    options: AdminListOptions & { query?: AdminListQuery & { promptTemplateId?: string } } = {},
  ): Promise<PaginatedPage<PromptUsageRecordResponse>> {
    return this.listPage<PromptUsageRecordResponse>('admin/prompt-templates/usage-records', options);
  }

  /**
   * Paginated prompt run history (PromptUsageRecord rows), newest first
   *
   * `GET /api/v1/admin/prompt-templates/usage-records` — `PromptManagementController.listUsageRecords`.
   *
   * Walks every page, yielding rows: `for await (const row of …)`. Pagination is driven from the REQUEST side; a failure on page N propagates after page N-1's rows, so "the list ended" and "the list broke" never look alike.
   */
  listUsageRecordsIterate(
    options: AdminListOptions & { query?: AdminListQuery & { promptTemplateId?: string } } = {},
  ): AsyncGenerator<PromptUsageRecordResponse, void, undefined> {
    return this.listAll<PromptUsageRecordResponse>('admin/prompt-templates/usage-records', options);
  }
}
