/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions } from './admin-resource';
import type {
  BulkActionResultResponse,
  BulkJobActionRequest,
  CleanQueueRequest,
  CleanQueueResponse,
  JobDetailResponse,
  PaginatedJobsResponse,
  QueueStatsResponse,
  RedisHealthInfoResponse,
  SuccessResponse,
} from './schemas';

/**
 * `hope.admin.queue` — the `svc:admin:queue:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:queue:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller QueueAdminController
 * (12 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminQueueResource extends AdminResource {
  readonly svcScope = 'svc:admin:queue:manage';

  /**
   * List every registered queue with its stats (counts, paused flag, worker count).
   *
   * `GET /api/v1/admin/queues` — `QueueAdminController.listQueues`.
   */
  listQueues(options: AdminRequestOptions = {}): Promise<QueueStatsResponse[]> {
    return this.request<QueueStatsResponse[]>({
      method: 'GET',
      path: 'admin/queues',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get stats for a single queue.
   *
   * `GET /api/v1/admin/queues/{queueName}` — `QueueAdminController.getQueue`.
   */
  getQueue(queueName: string, options: AdminRequestOptions = {}): Promise<QueueStatsResponse> {
    return this.request<QueueStatsResponse>({
      method: 'GET',
      path: `admin/queues/${encodePathSegment(String(queueName))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Clean finished (completed/failed) jobs older than a grace period.
   *
   * `POST /api/v1/admin/queues/{queueName}/clean` — `QueueAdminController.cleanQueue`.
   */
  cleanQueue(queueName: string, body: CleanQueueRequest, options: AdminRequestOptions = {}): Promise<CleanQueueResponse> {
    return this.request<CleanQueueResponse>({
      method: 'POST',
      path: `admin/queues/${encodePathSegment(String(queueName))}/clean`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List jobs in a queue (paginated, optionally status/name filtered).
   *
   * `GET /api/v1/admin/queues/{queueName}/jobs` — `QueueAdminController.listJobs`.
   */
  listJobs(
    queueName: string,
    options: AdminRequestOptions & {
      query?: { jobName?: string; limit?: number; page?: number; status?: 'waiting' | 'active' | 'completed' | 'failed' | 'delayed' };
    } = {},
  ): Promise<PaginatedJobsResponse> {
    return this.request<PaginatedJobsResponse>({
      method: 'GET',
      path: `admin/queues/${encodePathSegment(String(queueName))}/jobs`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Remove a job from the queue.
   *
   * `DELETE /api/v1/admin/queues/{queueName}/jobs/{jobId}` — `QueueAdminController.removeJob`.
   */
  removeJob(queueName: string, jobId: string, options: AdminRequestOptions = {}): Promise<SuccessResponse> {
    return this.request<SuccessResponse>({
      method: 'DELETE',
      path: `admin/queues/${encodePathSegment(String(queueName))}/jobs/${encodePathSegment(String(jobId))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get a single job with PII-redacted data, options, stacktrace.
   *
   * `GET /api/v1/admin/queues/{queueName}/jobs/{jobId}` — `QueueAdminController.getJob`.
   */
  getJob(queueName: string, jobId: string, options: AdminRequestOptions = {}): Promise<JobDetailResponse> {
    return this.request<JobDetailResponse>({
      method: 'GET',
      path: `admin/queues/${encodePathSegment(String(queueName))}/jobs/${encodePathSegment(String(jobId))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Promote a delayed job so it runs immediately.
   *
   * `POST /api/v1/admin/queues/{queueName}/jobs/{jobId}/promote` — `QueueAdminController.promoteJob`.
   */
  promoteJob(queueName: string, jobId: string, options: AdminRequestOptions = {}): Promise<SuccessResponse> {
    return this.request<SuccessResponse>({
      method: 'POST',
      path: `admin/queues/${encodePathSegment(String(queueName))}/jobs/${encodePathSegment(String(jobId))}/promote`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retry a failed job (re-uses the original payload).
   *
   * `POST /api/v1/admin/queues/{queueName}/jobs/{jobId}/retry` — `QueueAdminController.retryJob`.
   */
  retryJob(queueName: string, jobId: string, options: AdminRequestOptions = {}): Promise<SuccessResponse> {
    return this.request<SuccessResponse>({
      method: 'POST',
      path: `admin/queues/${encodePathSegment(String(queueName))}/jobs/${encodePathSegment(String(jobId))}/retry`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Apply a bulk retry/remove action to a set of job ids.
   *
   * `POST /api/v1/admin/queues/{queueName}/jobs/bulk` — `QueueAdminController.bulkJobAction`.
   */
  bulkJobAction(queueName: string, body: BulkJobActionRequest, options: AdminRequestOptions = {}): Promise<BulkActionResultResponse> {
    return this.request<BulkActionResultResponse>({
      method: 'POST',
      path: `admin/queues/${encodePathSegment(String(queueName))}/jobs/bulk`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Pause a queue (stops processing new jobs).
   *
   * `POST /api/v1/admin/queues/{queueName}/pause` — `QueueAdminController.pauseQueue`.
   */
  pauseQueue(queueName: string, options: AdminRequestOptions = {}): Promise<SuccessResponse> {
    return this.request<SuccessResponse>({
      method: 'POST',
      path: `admin/queues/${encodePathSegment(String(queueName))}/pause`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Resume a paused queue.
   *
   * `POST /api/v1/admin/queues/{queueName}/resume` — `QueueAdminController.resumeQueue`.
   */
  resumeQueue(queueName: string, options: AdminRequestOptions = {}): Promise<SuccessResponse> {
    return this.request<SuccessResponse>({
      method: 'POST',
      path: `admin/queues/${encodePathSegment(String(queueName))}/resume`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Redis connection health for the queue infrastructure (PING latency + INFO stats). Never errors.
   *
   * `GET /api/v1/admin/queues/health/redis` — `QueueAdminController.getRedisHealth`.
   */
  getRedisHealth(options: AdminRequestOptions = {}): Promise<RedisHealthInfoResponse> {
    return this.request<RedisHealthInfoResponse>({
      method: 'GET',
      path: 'admin/queues/health/redis',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
