/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions } from './admin-resource';
import type { RateLimitPolicyResponse, SetRateLimitEnabledRequest, SetRateLimitRouteRequest, SetRateLimitTierRequest } from './schemas';

/**
 * `hope.admin.rateLimit` — the `svc:admin:rate-limit:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:rate-limit:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller RateLimitAdminController
 * (4 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminRateLimitResource extends AdminResource {
  readonly svcScope = 'svc:admin:rate-limit:manage';

  /**
   * Get the effective rate-limit policy (global flag, tier baselines, known-route overrides).
   *
   * `GET /api/v1/admin/rate-limit` — `RateLimitAdminController.getPolicy`.
   */
  getPolicy(options: AdminRequestOptions = {}): Promise<RateLimitPolicyResponse> {
    return this.request<RateLimitPolicyResponse>({
      method: 'GET',
      path: 'admin/rate-limit',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Flip the global rate-limit kill-switch.
   *
   * `PUT /api/v1/admin/rate-limit/enabled` — `RateLimitAdminController.setEnabled`.
   */
  setEnabled(body: SetRateLimitEnabledRequest, options: AdminRequestOptions = {}): Promise<RateLimitPolicyResponse> {
    return this.request<RateLimitPolicyResponse>({
      method: 'PUT',
      path: 'admin/rate-limit/enabled',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Update a per-endpoint override for a known throttled route (e.g. auth.login).
   *
   * `PUT /api/v1/admin/rate-limit/routes/{routeId}` — `RateLimitAdminController.setRoute`.
   */
  setRoute(routeId: string, body: SetRateLimitRouteRequest, options: AdminRequestOptions = {}): Promise<RateLimitPolicyResponse> {
    return this.request<RateLimitPolicyResponse>({
      method: 'PUT',
      path: `admin/rate-limit/routes/${encodePathSegment(String(routeId))}`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Update a tier baseline (default | strict | heavy | relaxed).
   *
   * `PUT /api/v1/admin/rate-limit/tiers/{tier}` — `RateLimitAdminController.setTier`.
   */
  setTier(tier: string, body: SetRateLimitTierRequest, options: AdminRequestOptions = {}): Promise<RateLimitPolicyResponse> {
    return this.request<RateLimitPolicyResponse>({
      method: 'PUT',
      path: `admin/rate-limit/tiers/${encodePathSegment(String(tier))}`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
