/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions } from './admin-resource';
import type { SchedulerInfoResponse, SuccessResponse, ToggleSchedulerRequest, UpdateSchedulerCronRequest } from './schemas';

/**
 * `hope.admin.scheduler` — the `svc:admin:scheduler:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:scheduler:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller SchedulerAdminController
 * (5 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminSchedulerResource extends AdminResource {
  readonly svcScope = 'svc:admin:scheduler:manage';

  /**
   * List all schedulers (static @Cron + dynamic) with cron/interval/run metadata.
   *
   * `GET /api/v1/admin/schedulers` — `SchedulerAdminController.listSchedulers`.
   */
  listSchedulers(options: AdminRequestOptions = {}): Promise<SchedulerInfoResponse[]> {
    return this.request<SchedulerInfoResponse[]>({
      method: 'GET',
      path: 'admin/schedulers',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Update a dynamic scheduler cron expression (static schedulers are rejected).
   *
   * `PATCH /api/v1/admin/schedulers/{name}/cron` — `SchedulerAdminController.updateCron`.
   */
  updateCron(name: string, body: UpdateSchedulerCronRequest, options: AdminRequestOptions = {}): Promise<SchedulerInfoResponse> {
    return this.request<SchedulerInfoResponse>({
      method: 'PATCH',
      path: `admin/schedulers/${encodePathSegment(String(name))}/cron`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Pause (stop) a running cron scheduler.
   *
   * `POST /api/v1/admin/schedulers/{name}/pause` — `SchedulerAdminController.pauseScheduler`.
   */
  pauseScheduler(name: string, options: AdminRequestOptions = {}): Promise<SuccessResponse> {
    return this.request<SuccessResponse>({
      method: 'POST',
      path: `admin/schedulers/${encodePathSegment(String(name))}/pause`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Resume (start) a paused cron scheduler.
   *
   * `POST /api/v1/admin/schedulers/{name}/resume` — `SchedulerAdminController.resumeScheduler`.
   */
  resumeScheduler(name: string, options: AdminRequestOptions = {}): Promise<SuccessResponse> {
    return this.request<SuccessResponse>({
      method: 'POST',
      path: `admin/schedulers/${encodePathSegment(String(name))}/resume`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Enable/disable a dynamic scheduler (static schedulers are rejected).
   *
   * `PATCH /api/v1/admin/schedulers/{name}/toggle` — `SchedulerAdminController.toggleScheduler`.
   */
  toggleScheduler(name: string, body: ToggleSchedulerRequest, options: AdminRequestOptions = {}): Promise<SchedulerInfoResponse> {
    return this.request<SchedulerInfoResponse>({
      method: 'PATCH',
      path: `admin/schedulers/${encodePathSegment(String(name))}/toggle`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
