/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminListOptions, AdminListQuery, AdminRequestOptions, PaginatedPage } from './admin-resource';
import type { CurrentServiceResponse, ServiceReleaseResponse } from './schemas';

/**
 * `hope.admin.serviceRelease` — the `svc:admin:service-release:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:service-release:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller ServiceReleaseAdminController
 * (3 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminServiceReleaseResource extends AdminResource {
  readonly svcScope = 'svc:admin:service-release:manage';

  /**
   * Release history across all services, newest build first
   *
   * `GET /api/v1/admin/service-releases` — `ServiceReleaseAdminController.list`.
   *
   * Returns ONE page. `page` is 0-based and both `page` and `limit` are always sent explicitly — the gateway echoes RAW query values back, so the response's own `page`/`limit` are not usable as loop state. Use {@link listIterate} to walk every page.
   */
  list(
    options: AdminListOptions & { query?: AdminListQuery & { environment?: 'dev' | 'staging' | 'prod'; serviceName?: string } } = {},
  ): Promise<PaginatedPage<ServiceReleaseResponse>> {
    return this.listPage<ServiceReleaseResponse>('admin/service-releases', options);
  }

  /**
   * Release history across all services, newest build first
   *
   * `GET /api/v1/admin/service-releases` — `ServiceReleaseAdminController.list`.
   *
   * Walks every page, yielding rows: `for await (const row of …)`. Pagination is driven from the REQUEST side; a failure on page N propagates after page N-1's rows, so "the list ended" and "the list broke" never look alike.
   */
  listIterate(
    options: AdminListOptions & { query?: AdminListQuery & { environment?: 'dev' | 'staging' | 'prod'; serviceName?: string } } = {},
  ): AsyncGenerator<ServiceReleaseResponse, void, undefined> {
    return this.listAll<ServiceReleaseResponse>('admin/service-releases', options);
  }

  /**
   * Release timeline for one service, newest first
   *
   * `GET /api/v1/admin/service-releases/{serviceName}/history` — `ServiceReleaseAdminController.history`.
   */
  history(serviceName: string, options: AdminRequestOptions = {}): Promise<ServiceReleaseResponse[]> {
    return this.request<ServiceReleaseResponse[]>({
      method: 'GET',
      path: `admin/service-releases/${encodePathSegment(String(serviceName))}/history`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * What is running right now, one row per service
   *
   * `GET /api/v1/admin/service-releases/current` — `ServiceReleaseAdminController.current`.
   */
  current(options: AdminRequestOptions & { query?: { environment: 'dev' | 'staging' | 'prod' } } = {}): Promise<CurrentServiceResponse[]> {
    return this.request<CurrentServiceResponse[]>({
      method: 'GET',
      path: 'admin/service-releases/current',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
