/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminListOptions, AdminListQuery, AdminRequestOptions, IfMatchPrecondition, PaginatedPage } from './admin-resource';
import type {
  CreateGlobalSettingRequest,
  EffectiveSettingResponse,
  GlobalSettingResponse,
  PaginatedResponse,
  RevealGlobalSettingRequest,
  RevealGlobalSettingResponse,
  RotateGlobalSettingRequest,
  SettingCatalogResponse,
  UpdateGlobalSettingRequest,
  WriteRegistrySettingRequest,
  WriteRegistrySettingResponse,
} from './schemas';

/**
 * `hope.admin.settings` — the `svc:admin:settings:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:settings:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controllers GlobalSettingController, SettingsCatalogController, SettingsRegistryWriteController
 * (12 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminSettingsResource extends AdminResource {
  readonly svcScope = 'svc:admin:settings:manage';

  /**
   * Retrieving multiple GlobalSettingResponses
   *
   * `GET /api/v1/admin/settings` — `GlobalSettingController.fetchAll`.
   */
  fetchAll(
    options: AdminRequestOptions & {
      query?: { filters?: string; limit?: number; page?: number; search?: string; searchFields?: string; secretsOnly?: boolean; sort?: string };
    } = {},
  ): Promise<PaginatedResponse & { data?: GlobalSettingResponse[] }> {
    return this.request<PaginatedResponse & { data?: GlobalSettingResponse[] }>({
      method: 'GET',
      path: 'admin/settings',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Creating a GlobalSettingResponse
   *
   * `POST /api/v1/admin/settings` — `GlobalSettingController.create`.
   */
  create(body: CreateGlobalSettingRequest, options: AdminRequestOptions = {}): Promise<GlobalSettingResponse> {
    return this.request<GlobalSettingResponse>({
      method: 'POST',
      path: 'admin/settings',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Deleting a GlobalSettingResponse by id
   *
   * `DELETE /api/v1/admin/settings/{id}` — `GlobalSettingController.delete`.
   */
  delete(id: string, options: AdminRequestOptions = {}): Promise<GlobalSettingResponse> {
    return this.request<GlobalSettingResponse>({
      method: 'DELETE',
      path: `admin/settings/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Retrieving a single GlobalSettingResponse by id
   *
   * `GET /api/v1/admin/settings/{id}` — `GlobalSettingController.fetchById`.
   */
  fetchById(id: string, options: AdminRequestOptions = {}): Promise<GlobalSettingResponse> {
    return this.request<GlobalSettingResponse>({
      method: 'GET',
      path: `admin/settings/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Updating a GlobalSettingResponse by id
   *
   * Updates one GlobalSetting row. Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED and the server runs a Compare-And-Set against the row's `_version` column. When the header is present, its value overrides the body-field `expectedVersion`. On version drift the response is `412 Precondition Failed`; a missing header is `428 Precondition Required`. `locked` rows are super-admin-only.
   *
   * `PATCH /api/v1/admin/settings/{id}` — `GlobalSettingController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  update(
    id: string,
    body: UpdateGlobalSettingRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<GlobalSettingResponse> {
    return this.requestWithPrecondition<GlobalSettingResponse>({
      method: 'PATCH',
      path: `admin/settings/${encodePathSegment(String(id))}`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Reveal a secret setting (super-admin, step-up re-auth, audited)
   *
   * Returns the decrypted plaintext of ONE global setting. SUPER_ADMIN only (CASL `manage:all`). Requires step-up re-authentication: the request body must carry the caller's current account password, verified server-side against the stored hash. Every reveal is audit-logged; the plaintext is never logged. Never bulk-reveals.
   *
   * `POST /api/v1/admin/settings/{id}/reveal` — `GlobalSettingController.reveal`.
   */
  reveal(id: string, body: RevealGlobalSettingRequest, options: AdminRequestOptions = {}): Promise<RevealGlobalSettingResponse> {
    return this.request<RevealGlobalSettingResponse>({
      method: 'POST',
      path: `admin/settings/${encodePathSegment(String(id))}/reveal`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Rotate a secret setting (super-admin, step-up re-auth, OCC, audited)
   *
   * Atomically replaces the stored secret value of ONE global setting under optimistic concurrency. SUPER_ADMIN only (CASL `manage:all`). Requires step-up re-authentication (the caller's current password in the body) AND the RFC 7232 `If-Match` header carrying the row version (missing → 428, drift → 412). The old value is invalidated by the same versioned write. Every rotation is distinctly audit-logged; neither the old nor the new plaintext is ever logged or returned — the response is the masked setting.
   *
   * `POST /api/v1/admin/settings/{id}/rotate` — `GlobalSettingController.rotate`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  rotate(
    id: string,
    body: RotateGlobalSettingRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<GlobalSettingResponse> {
    return this.requestWithPrecondition<GlobalSettingResponse>({
      method: 'POST',
      path: `admin/settings/${encodePathSegment(String(id))}/rotate`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List the capability/settings catalog (RBAC-filtered metadata).
   *
   * `GET /api/v1/admin/settings/catalog` — `SettingsCatalogController.getCatalog`.
   */
  getCatalog(options: AdminRequestOptions = {}): Promise<SettingCatalogResponse> {
    return this.request<SettingCatalogResponse>({
      method: 'GET',
      path: 'admin/settings/catalog',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Resolve the effective value of one non-secret setting for a context (with cascade trace).
   *
   * `GET /api/v1/admin/settings/effective` — `SettingsCatalogController.getEffective`.
   */
  getEffective(
    options: AdminRequestOptions & { query?: { departmentId?: string; doctorId?: string; key: string; tenantId?: string } } = {},
  ): Promise<EffectiveSettingResponse> {
    return this.request<EffectiveSettingResponse>({
      method: 'GET',
      path: 'admin/settings/effective',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Read one registry setting: its descriptor metadata plus the effective value and cascade trace.
   *
   * `GET /api/v1/admin/settings/registry/{key}` — `SettingsRegistryWriteController.getSetting`.
   */
  getSetting(
    key: string,
    options: AdminRequestOptions & { query?: { departmentId?: string; doctorId?: string; scope?: 'system' | 'tenant'; tenantId?: string } } = {},
  ): Promise<EffectiveSettingResponse> {
    return this.request<EffectiveSettingResponse>({
      method: 'GET',
      path: `admin/settings/registry/${encodePathSegment(String(key))}`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Write one registry setting through the single descriptor-driven enforcement point.
   *
   * Enforcement order: unknown key → 400; secret sensitivity → 400; `globalOnly` without super admin → 403; scope deeper than the descriptor `maxScope` → 400; non-`global-kv` tier → 400 (those keys keep their dedicated services); value type mismatch against `dataType` → 400. On success the backing KV row is upserted under the reserved `registry` namespace, a sys-event is broadcast, and the AppSettings cache the consumers read is refreshed.
   *
   * `PUT /api/v1/admin/settings/registry/{key}` — `SettingsRegistryWriteController.putSetting`.
   */
  putSetting(key: string, body: WriteRegistrySettingRequest, options: AdminRequestOptions = {}): Promise<WriteRegistrySettingResponse> {
    return this.request<WriteRegistrySettingResponse>({
      method: 'PUT',
      path: `admin/settings/registry/${encodePathSegment(String(key))}`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List global settings for a specific tenant
   *
   * `GET /api/v1/admin/settings/tenant/{tenantId}` — `GlobalSettingController.fetchByTenant`.
   *
   * Returns ONE page. `page` is 0-based and both `page` and `limit` are always sent explicitly — the gateway echoes RAW query values back, so the response's own `page`/`limit` are not usable as loop state. Use {@link fetchByTenantIterate} to walk every page.
   */
  fetchByTenant(tenantId: string, options: AdminListOptions & { query?: AdminListQuery } = {}): Promise<PaginatedPage<unknown[]>> {
    return this.listPage<unknown[]>(`admin/settings/tenant/${encodePathSegment(String(tenantId))}`, options);
  }

  /**
   * List global settings for a specific tenant
   *
   * `GET /api/v1/admin/settings/tenant/{tenantId}` — `GlobalSettingController.fetchByTenant`.
   *
   * Walks every page, yielding rows: `for await (const row of …)`. Pagination is driven from the REQUEST side; a failure on page N propagates after page N-1's rows, so "the list ended" and "the list broke" never look alike.
   */
  fetchByTenantIterate(tenantId: string, options: AdminListOptions & { query?: AdminListQuery } = {}): AsyncGenerator<unknown[], void, undefined> {
    return this.listAll<unknown[]>(`admin/settings/tenant/${encodePathSegment(String(tenantId))}`, options);
  }
}
