/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions, IfMatchPrecondition } from './admin-resource';
import type {
  CreateTenantIdpConfigRequest,
  SetDirectoryCredentialsRequest,
  SyncDirectoryUsersResponse,
  TenantIdpConfigResponse,
  TestConnectionResponse,
  UpdateTenantIdpConfigRequest,
} from './schemas';

/**
 * `hope.admin.tenantIdpConfig` — the `svc:admin:tenant-idp-config:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:tenant-idp-config:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller TenantIdpConfigAdminController
 * (8 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminTenantIdpConfigResource extends AdminResource {
  readonly svcScope = 'svc:admin:tenant-idp-config:manage';

  /**
   * List a tenant's configured external identity providers
   *
   * `GET /api/v1/admin/tenant-idp-config` — `TenantIdpConfigAdminController.list`.
   */
  list(options: AdminRequestOptions & { query?: { tenantId?: string } } = {}): Promise<TenantIdpConfigResponse[]> {
    return this.request<TenantIdpConfigResponse[]>({
      method: 'GET',
      path: 'admin/tenant-idp-config',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Configure a new external OIDC identity provider (starts DRAFT — D7, no self-lockout)
   *
   * The client secret is Vault-sealed and never echoed back. The row must pass "Test connection" before it can be used at /auth/sso/start.
   *
   * `POST /api/v1/admin/tenant-idp-config` — `TenantIdpConfigAdminController.create`.
   */
  create(
    body: CreateTenantIdpConfigRequest,
    options: AdminRequestOptions & { query?: { tenantId?: string } } = {},
  ): Promise<TenantIdpConfigResponse> {
    return this.request<TenantIdpConfigResponse>({
      method: 'POST',
      path: 'admin/tenant-idp-config',
      query: options.query,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Remove an identity provider config
   *
   * `DELETE /api/v1/admin/tenant-idp-config/{id}` — `TenantIdpConfigAdminController.remove`.
   */
  remove(id: string, options: AdminRequestOptions & { query?: { tenantId?: string } } = {}): Promise<unknown> {
    return this.request<unknown>({
      method: 'DELETE',
      path: `admin/tenant-idp-config/${encodePathSegment(String(id))}`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get one identity provider config
   *
   * `GET /api/v1/admin/tenant-idp-config/{id}` — `TenantIdpConfigAdminController.getById`.
   */
  getById(id: string, options: AdminRequestOptions & { query?: { tenantId?: string } } = {}): Promise<TenantIdpConfigResponse> {
    return this.request<TenantIdpConfigResponse>({
      method: 'GET',
      path: `admin/tenant-idp-config/${encodePathSegment(String(id))}`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Update an identity provider config under optimistic concurrency
   *
   * `PUT /api/v1/admin/tenant-idp-config/{id}` — `TenantIdpConfigAdminController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  update(
    id: string,
    body: UpdateTenantIdpConfigRequest,
    options: AdminRequestOptions & { query?: { tenantId?: string } } & { ifMatch: IfMatchPrecondition },
  ): Promise<TenantIdpConfigResponse> {
    return this.requestWithPrecondition<TenantIdpConfigResponse>({
      method: 'PUT',
      path: `admin/tenant-idp-config/${encodePathSegment(String(id))}`,
      query: options.query,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Seal a directory-API credential bundle for admin-triggered sync (P3)
   *
   * Vault-seals the credential bundle into directoryCredentialsRef. Shape matches config.directoryProvider (ms-graph: {azureTenantId, clientId, clientSecret}; google-directory: {serviceAccountEmail, privateKey, delegatedAdminEmail, customerId?}). Write-only — never echoed back. No If-Match (a narrow secret rotation, same posture as the client secret's own rotation on PUT :id).
   *
   * `PUT /api/v1/admin/tenant-idp-config/{id}/directory-credentials` — `TenantIdpConfigAdminController.setDirectoryCredentials`.
   */
  setDirectoryCredentials(
    id: string,
    body: SetDirectoryCredentialsRequest,
    options: AdminRequestOptions & { query?: { tenantId?: string } } = {},
  ): Promise<TenantIdpConfigResponse> {
    return this.request<TenantIdpConfigResponse>({
      method: 'PUT',
      path: `admin/tenant-idp-config/${encodePathSegment(String(id))}/directory-credentials`,
      query: options.query,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Bulk-pull the provider's directory (MS Graph / Google) and pre-provision users (P3)
   *
   * Admin-triggered, async. Idempotent (safe to re-run) — upserts are keyed on (providerId, subject); a directory user with an existing FederatedIdentity link is a no-op. Requires config.directoryProvider and a sealed directoryCredentialsRef to already be set on this provider. Poll progress/result via GET /admin/queues/SyncTenantDirectoryUsers/jobs/:jobId.
   *
   * `POST /api/v1/admin/tenant-idp-config/{id}/sync` — `TenantIdpConfigAdminController.syncDirectory`.
   */
  syncDirectory(id: string, options: AdminRequestOptions & { query?: { tenantId?: string } } = {}): Promise<SyncDirectoryUsersResponse> {
    return this.request<SyncDirectoryUsersResponse>({
      method: 'POST',
      path: `admin/tenant-idp-config/${encodePathSegment(String(id))}/sync`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Test connection — OIDC discovery + client construction (D7)
   *
   * A successful probe flips the row DRAFT → ENABLED. Never drives a full browser login (no user is present at config time).
   *
   * `POST /api/v1/admin/tenant-idp-config/{id}/test` — `TenantIdpConfigAdminController.testConnection`.
   */
  testConnection(id: string, options: AdminRequestOptions & { query?: { tenantId?: string } } = {}): Promise<TestConnectionResponse> {
    return this.request<TestConnectionResponse>({
      method: 'POST',
      path: `admin/tenant-idp-config/${encodePathSegment(String(id))}/test`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
