/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminRequestOptions, IfMatchPrecondition } from './admin-resource';
import type {
  EffectiveSttConfigResponse,
  PipelineResponse,
  SetSttCredentialRequest,
  SetSttFallbackRequest,
  SttCredentialResponse,
  TenantSttConfigResponse,
  TestSttCredentialRequest,
  TestSttCredentialResponse,
} from './schemas';

/**
 * `hope.admin.tenantSttConfig` — the `svc:admin:tenant-stt-config:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:tenant-stt-config:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller TenantSttConfigAdminController
 * (8 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminTenantSttConfigResource extends AdminResource {
  readonly svcScope = 'svc:admin:tenant-stt-config:manage';

  /**
   * Resolve the effective STT fallback spec for a tenant (tenant row over the SYSTEM default)
   *
   * Merges the tenant row over the SYSTEM-tenant platform default. Read-only; this is what the gateway reads on the session-create path.
   *
   * `GET /api/v1/admin/stt-config` — `TenantSttConfigAdminController.getEffective`.
   */
  getEffective(options: AdminRequestOptions & { query?: { tenantId?: string } } = {}): Promise<EffectiveSttConfigResponse> {
    return this.request<EffectiveSttConfigResponse>({
      method: 'GET',
      path: 'admin/stt-config',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List a tenant's BYO provider credentials (masked — never the key)
   *
   * `GET /api/v1/admin/stt-config/credentials` — `TenantSttConfigAdminController.getCredentials`.
   */
  getCredentials(options: AdminRequestOptions & { query?: { tenantId?: string } } = {}): Promise<SttCredentialResponse[]> {
    return this.request<SttCredentialResponse[]>({
      method: 'GET',
      path: 'admin/stt-config/credentials',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Remove a tenant BYO provider credential
   *
   * `DELETE /api/v1/admin/stt-config/credentials/{provider}` — `TenantSttConfigAdminController.removeCredential`.
   */
  removeCredential(provider: string, options: AdminRequestOptions & { query?: { tenantId?: string } } = {}): Promise<unknown> {
    return this.request<unknown>({
      method: 'DELETE',
      path: `admin/stt-config/credentials/${encodePathSegment(String(provider))}`,
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Set or rotate a tenant BYO provider key (write-only; Vault-encrypted at rest, never returned)
   *
   * `If-Match` (RFC 7232) carries the credential version — `"0"` creates, an existing version CASes against `_version` (drift → 412, missing → 428).
   *
   * `PUT /api/v1/admin/stt-config/credentials/{provider}` — `TenantSttConfigAdminController.setCredential`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  setCredential(
    provider: string,
    body: SetSttCredentialRequest,
    options: AdminRequestOptions & { query?: { tenantId?: string } } & { ifMatch: IfMatchPrecondition },
  ): Promise<SttCredentialResponse> {
    return this.requestWithPrecondition<SttCredentialResponse>({
      method: 'PUT',
      path: `admin/stt-config/credentials/${encodePathSegment(String(provider))}`,
      query: options.query,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Test an apiKey/region/endpoint combination against the live provider BEFORE saving it
   *
   * Ephemeral probe — never persisted, no Vault write, no OCC. Lets a tenant admin validate a key before (or independent of) saving it, since the saved key is write-only and never returned for re-testing.
   *
   * `POST /api/v1/admin/stt-config/credentials/{provider}/test` — `TenantSttConfigAdminController.testCredential`.
   */
  testCredential(
    provider: string,
    body: TestSttCredentialRequest,
    options: AdminRequestOptions & { query?: { tenantId?: string } } = {},
  ): Promise<TestSttCredentialResponse> {
    return this.request<TestSttCredentialResponse>({
      method: 'POST',
      path: `admin/stt-config/credentials/${encodePathSegment(String(provider))}/test`,
      query: options.query,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List the enabled, cloud-engine-backed pipelines a tenant may set as its fallback
   *
   * The valid targets for the fallback pointer — the picker offers exactly these, so the PUT never rejects a selection.
   *
   * `GET /api/v1/admin/stt-config/fallback-candidates` — `TenantSttConfigAdminController.getFallbackCandidates`.
   */
  getFallbackCandidates(options: AdminRequestOptions & { query?: { tenantId?: string } } = {}): Promise<PipelineResponse[]> {
    return this.request<PipelineResponse[]>({
      method: 'GET',
      path: 'admin/stt-config/fallback-candidates',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get the raw, editable STT config row for a tenant
   *
   * Returns the tenant row, or a `version:0` placeholder (all-inherit) when none exists yet. The `version` drives the `If-Match` OCC token for the matching `PUT` (create with `expectedVersion: 0`).
   *
   * `GET /api/v1/admin/stt-config/row` — `TenantSttConfigAdminController.getRow`.
   */
  getRow(options: AdminRequestOptions & { query?: { tenantId?: string } } = {}): Promise<TenantSttConfigResponse> {
    return this.request<TenantSttConfigResponse>({
      method: 'GET',
      path: 'admin/stt-config/row',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Create or update the tenant STT fallback row under optimistic concurrency
   *
   * Upserts the fallback pipeline pointer + auto-switch knobs (omit = unchanged; `fallbackPipelineId: null` clears it). `If-Match` (RFC 7232) carries the version read from the prior GET — `"0"` creates the row, an existing version CASes against `_version` (drift → 412, missing → 428). The fallback target is validated (tenant-visible, ENABLED, cloud-engine-backed).
   *
   * `PUT /api/v1/admin/stt-config/row` — `TenantSttConfigAdminController.updateRow`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  updateRow(
    body: SetSttFallbackRequest,
    options: AdminRequestOptions & { query?: { tenantId?: string } } & { ifMatch: IfMatchPrecondition },
  ): Promise<TenantSttConfigResponse> {
    return this.requestWithPrecondition<TenantSttConfigResponse>({
      method: 'PUT',
      path: 'admin/stt-config/row',
      query: options.query,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
