/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { AdminResource } from './admin-resource';
import type { AdminRequestOptions } from './admin-resource';
import type { CostPerEncounterResponse, TopTenantsResponse, UsageSummaryResponse, UsageTimeseriesResponse } from './schemas';

/**
 * `hope.admin.usage` — the `svc:admin:usage:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:usage:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller AdminUsageController
 * (4 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminUsageResource extends AdminResource {
  readonly svcScope = 'svc:admin:usage:manage';

  /**
   * p50/p90/p99 + count of the Σ INTERNAL-basis cost per consultation over a billing period.
   *
   * `GET /api/v1/admin/usage/cost-per-encounter` — `AdminUsageController.costPerEncounter`.
   */
  costPerEncounter(options: AdminRequestOptions & { query?: { period?: string; tenantId?: string } } = {}): Promise<CostPerEncounterResponse> {
    return this.request<CostPerEncounterResponse>({
      method: 'GET',
      path: 'admin/usage/cost-per-encounter',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Units + rated cost per capability x provider x model for a billing period. BYOK notional split out.
   *
   * Also carries four figures the per-model breakdown cannot answer on its own (TASK-959): `computeSeconds` (GPU vs CPU occupancy across the inference capabilities), `workflowCpuSeconds` (the durable worker, kept separate so it is not billed twice), `thirdPartyBytes` (CLOUD/BYOK only — self-hosted LAN traffic is excluded) and `storage`, which is the LATEST nightly snapshot in the period split by class, not the period’s GB-day sum. `storage` is null when no snapshot exists for the period.
   *
   * `GET /api/v1/admin/usage/summary` — `AdminUsageController.summary`.
   */
  summary(options: AdminRequestOptions & { query?: { period?: string; tenantId?: string } } = {}): Promise<UsageSummaryResponse> {
    return this.request<UsageSummaryResponse>({
      method: 'GET',
      path: 'admin/usage/summary',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Bounded-range rollup timeseries for one capability x unit (max 92 days daily / 72h hourly).
   *
   * Each point carries the selected series (`quantity`/`costMicros`) plus that bucket's compute, workflow CPU, third-party bytes and storage GB across EVERY capability — so one request draws a series against the platform cost that moved with it. A bucket holding only those companion figures still yields a point, with a zeroed selected series.
   *
   * `GET /api/v1/admin/usage/timeseries` — `AdminUsageController.timeseries`.
   */
  timeseries(
    options: AdminRequestOptions & {
      query?: {
        capability: 'STT' | 'LLM' | 'NLP' | 'TTS' | 'EMBEDDING' | 'STORAGE' | 'WORKFLOW';
        from: string;
        granularity: 'day' | 'hour';
        tenantId?: string;
        to: string;
        unit:
          | 'INPUT_TOKEN'
          | 'OUTPUT_TOKEN'
          | 'CACHE_READ_TOKEN'
          | 'CACHE_WRITE_TOKEN'
          | 'REASONING_TOKEN'
          | 'AUDIO_SECOND'
          | 'SESSION_SECOND'
          | 'CHARACTER'
          | 'TEXT_UNIT'
          | 'REQUEST'
          | 'GPU_SECOND'
          | 'CPU_SECOND'
          | 'EGRESS_BYTE'
          | 'INGRESS_BYTE'
          | 'STORAGE_GB_DAY';
      };
    } = {},
  ): Promise<UsageTimeseriesResponse> {
    return this.request<UsageTimeseriesResponse>({
      method: 'GET',
      path: 'admin/usage/timeseries',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * SUPER_ADMIN-only cross-tenant top-N by rollup cost. Every other route on this controller is tenant-scoped; this one is not.
   *
   * `GET /api/v1/admin/usage/top-tenants` — `AdminUsageController.topTenants`.
   */
  topTenants(
    options: AdminRequestOptions & {
      query?: { capability?: 'STT' | 'LLM' | 'NLP' | 'TTS' | 'EMBEDDING' | 'STORAGE' | 'WORKFLOW'; limit?: number; metric?: 'cost'; period?: string };
    } = {},
  ): Promise<TopTenantsResponse> {
    return this.request<TopTenantsResponse>({
      method: 'GET',
      path: 'admin/usage/top-tenants',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
