/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { AdminResource } from './admin-resource';
import type { AdminRequestOptions } from './admin-resource';
import type {
  CostPerEncounterResponse,
  ProviderReconciliationRunResponse,
  TopTenantsResponse,
  UsageSummaryResponse,
  UsageTimeseriesResponse,
} from './schemas';

/**
 * `hope.admin.usage` — the `svc:admin:usage:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:usage:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controllers AdminReconciliationController, AdminUsageController
 * (7 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminUsageResource extends AdminResource {
  readonly svcScope = 'svc:admin:usage:manage';

  /**
   * p50/p90/p99 + count of the Σ INTERNAL-basis cost per consultation over a billing period.
   *
   * `GET /api/v1/admin/usage/cost-per-encounter` — `AdminUsageController.costPerEncounter`.
   */
  costPerEncounter(options: AdminRequestOptions & { query?: { period?: string; tenantId?: string } } = {}): Promise<CostPerEncounterResponse> {
    return this.request<CostPerEncounterResponse>({
      method: 'GET',
      path: 'admin/usage/cost-per-encounter',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Most recent run per provider — the status board.
   *
   * `GET /api/v1/admin/usage/reconciliation/latest` — `AdminReconciliationController.latest`.
   */
  latest(options: AdminRequestOptions = {}): Promise<ProviderReconciliationRunResponse[]> {
    return this.request<ProviderReconciliationRunResponse[]>({
      method: 'GET',
      path: 'admin/usage/reconciliation/latest',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Run the reconciliation sweep NOW against the last settled window, and record the attempts.
   *
   * Not a mutation of business data: the sweep only READS the ledger and each vendor report, then appends audit rows. It never writes to the ledger ( rule 5). Provided because the scheduled sweep ships OFF, so without it the audit trail stays empty until an operator enables the cron.
   *
   * `POST /api/v1/admin/usage/reconciliation/run` — `AdminReconciliationController.run`.
   */
  run(options: AdminRequestOptions = {}): Promise<unknown> {
    return this.request<unknown>({
      method: 'POST',
      path: 'admin/usage/reconciliation/run',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Provider-reconciliation runs, newest first. Includes SKIPPED and FAILED attempts — the gap is the point.
   *
   * Every attempt is recorded, not just successful comparisons: "not reconciled since March because the credential expired" is exactly what an audit asks about. Quantities are strings (Decimal columns); null means no comparison happened and is never 0.
   *
   * `GET /api/v1/admin/usage/reconciliation/runs` — `AdminReconciliationController.runs`.
   */
  runs(
    options: AdminRequestOptions & { query?: { breachedOnly?: boolean; from?: string; limit?: number; provider?: string; to?: string } } = {},
  ): Promise<ProviderReconciliationRunResponse[]> {
    return this.request<ProviderReconciliationRunResponse[]>({
      method: 'GET',
      path: 'admin/usage/reconciliation/runs',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Units + rated cost per capability x provider x model for a billing period. BYOK notional split out.
   *
   * `GET /api/v1/admin/usage/summary` — `AdminUsageController.summary`.
   */
  summary(options: AdminRequestOptions & { query?: { period?: string; tenantId?: string } } = {}): Promise<UsageSummaryResponse> {
    return this.request<UsageSummaryResponse>({
      method: 'GET',
      path: 'admin/usage/summary',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Bounded-range rollup timeseries for one capability x unit (max 92 days daily / 72h hourly).
   *
   * `GET /api/v1/admin/usage/timeseries` — `AdminUsageController.timeseries`.
   */
  timeseries(
    options: AdminRequestOptions & {
      query?: {
        capability: 'STT' | 'LLM' | 'NLP' | 'TTS' | 'EMBEDDING';
        from: string;
        granularity: 'day' | 'hour';
        tenantId?: string;
        to: string;
        unit:
          | 'INPUT_TOKEN'
          | 'OUTPUT_TOKEN'
          | 'CACHE_READ_TOKEN'
          | 'CACHE_WRITE_TOKEN'
          | 'REASONING_TOKEN'
          | 'AUDIO_SECOND'
          | 'SESSION_SECOND'
          | 'CHARACTER'
          | 'TEXT_UNIT'
          | 'REQUEST'
          | 'GPU_SECOND';
      };
    } = {},
  ): Promise<UsageTimeseriesResponse> {
    return this.request<UsageTimeseriesResponse>({
      method: 'GET',
      path: 'admin/usage/timeseries',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * SUPER_ADMIN-only cross-tenant top-N by rollup cost. Every other route on this controller is tenant-scoped; this one is not.
   *
   * `GET /api/v1/admin/usage/top-tenants` — `AdminUsageController.topTenants`.
   */
  topTenants(
    options: AdminRequestOptions & {
      query?: { capability?: 'STT' | 'LLM' | 'NLP' | 'TTS' | 'EMBEDDING'; limit?: number; metric?: 'cost'; period?: string };
    } = {},
  ): Promise<TopTenantsResponse> {
    return this.request<TopTenantsResponse>({
      method: 'GET',
      path: 'admin/usage/top-tenants',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
