/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import type { QueryValue } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminListOptions, AdminListQuery, AdminRequestOptions, IfMatchPrecondition, PaginatedPage } from './admin-resource';
import type {
  CreateWebhookRequest,
  CreateWebhookResponse,
  RotateWebhookSecretRequest,
  UpdateWebhookRequest,
  WebhookResponse,
  WebhookRunHistoryResponse,
} from './schemas';

/**
 * `hope.admin.webhookEvent` — the `svc:webhook:event:write` administration area.
 *
 * **Required service-account scope: `svc:webhook:event:write`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller WebhookController
 * (7 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminWebhookEventResource extends AdminResource {
  readonly svcScope = 'svc:webhook:event:write';

  /**
   * List webhooks (tenant-scoped; SUPER_ADMIN sees all, or targets one via ?tenantId=)
   *
   * `GET /api/v1/admin/webhooks` — `WebhookController.fetchAll`.
   *
   * Returns ONE page. `page` is 0-based and both `page` and `limit` are always sent explicitly — the gateway echoes RAW query values back, so the response's own `page`/`limit` are not usable as loop state. Use {@link fetchAllIterate} to walk every page.
   */
  fetchAll(options: AdminListOptions & { query?: AdminListQuery & { tenantId?: QueryValue } } = {}): Promise<PaginatedPage<unknown[]>> {
    return this.listPage<unknown[]>('admin/webhooks', options);
  }

  /**
   * List webhooks (tenant-scoped; SUPER_ADMIN sees all, or targets one via ?tenantId=)
   *
   * `GET /api/v1/admin/webhooks` — `WebhookController.fetchAll`.
   *
   * Walks every page, yielding rows: `for await (const row of …)`. Pagination is driven from the REQUEST side; a failure on page N propagates after page N-1's rows, so "the list ended" and "the list broke" never look alike.
   */
  fetchAllIterate(
    options: AdminListOptions & { query?: AdminListQuery & { tenantId?: QueryValue } } = {},
  ): AsyncGenerator<unknown[], void, undefined> {
    return this.listAll<unknown[]>('admin/webhooks', options);
  }

  /**
   * Create a webhook for the caller tenant. The signing secret is server-generated and returned only once.
   *
   * `POST /api/v1/admin/webhooks` — `WebhookController.create`.
   */
  create(body: CreateWebhookRequest, options: AdminRequestOptions = {}): Promise<CreateWebhookResponse> {
    return this.request<CreateWebhookResponse>({
      method: 'POST',
      path: 'admin/webhooks',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Soft-delete a webhook
   *
   * `DELETE /api/v1/admin/webhooks/{id}` — `WebhookController.delete`.
   */
  delete(id: string, options: AdminRequestOptions = {}): Promise<WebhookResponse> {
    return this.request<WebhookResponse>({
      method: 'DELETE',
      path: `admin/webhooks/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get one webhook
   *
   * `GET /api/v1/admin/webhooks/{id}` — `WebhookController.fetchById`.
   */
  fetchById(id: string, options: AdminRequestOptions = {}): Promise<WebhookResponse> {
    return this.request<WebhookResponse>({
      method: 'GET',
      path: `admin/webhooks/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Update a webhook (If-Match OCC)
   *
   * Sparse patch. Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED and CAS'es against the row `_version`; drift → 412, missing header → 428.
   *
   * `PATCH /api/v1/admin/webhooks/{id}` — `WebhookController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  update(id: string, body: UpdateWebhookRequest, options: AdminRequestOptions & { ifMatch: IfMatchPrecondition }): Promise<WebhookResponse> {
    return this.requestWithPrecondition<WebhookResponse>({
      method: 'PATCH',
      path: `admin/webhooks/${encodePathSegment(String(id))}`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List a webhook's delivery log (newest-first)
   *
   * Read-only projection of `WebhookRunHistory`. Rows carry no tenantId — tenancy is enforced through the parent webhook (cross-tenant id → 404).
   *
   * `GET /api/v1/admin/webhooks/{id}/deliveries` — `WebhookController.fetchDeliveries`.
   *
   * Returns ONE page. `page` is 0-based and both `page` and `limit` are always sent explicitly — the gateway echoes RAW query values back, so the response's own `page`/`limit` are not usable as loop state. Use {@link fetchDeliveriesIterate} to walk every page.
   */
  fetchDeliveries(id: string, options: AdminListOptions & { query?: AdminListQuery } = {}): Promise<PaginatedPage<WebhookRunHistoryResponse>> {
    return this.listPage<WebhookRunHistoryResponse>(`admin/webhooks/${encodePathSegment(String(id))}/deliveries`, options);
  }

  /**
   * List a webhook's delivery log (newest-first)
   *
   * Read-only projection of `WebhookRunHistory`. Rows carry no tenantId — tenancy is enforced through the parent webhook (cross-tenant id → 404).
   *
   * `GET /api/v1/admin/webhooks/{id}/deliveries` — `WebhookController.fetchDeliveries`.
   *
   * Walks every page, yielding rows: `for await (const row of …)`. Pagination is driven from the REQUEST side; a failure on page N propagates after page N-1's rows, so "the list ended" and "the list broke" never look alike.
   */
  fetchDeliveriesIterate(
    id: string,
    options: AdminListOptions & { query?: AdminListQuery } = {},
  ): AsyncGenerator<WebhookRunHistoryResponse, void, undefined> {
    return this.listAll<WebhookRunHistoryResponse>(`admin/webhooks/${encodePathSegment(String(id))}/deliveries`, options);
  }

  /**
   * Rotate a webhook signing secret (If-Match OCC)
   *
   * Mints a fresh, server-generated signing secret and invalidates the prior one immediately (no overlap window). The raw secret is returned exactly once, same contract as `POST admin/webhooks`. Optimistic concurrency is enforced identically to `PATCH :id`: `If-Match` (RFC 7232) is REQUIRED; drift → 412, missing header → 428.
   *
   * `POST /api/v1/admin/webhooks/{id}/rotate-secret` — `WebhookController.rotateSecret`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  rotateSecret(
    id: string,
    body: RotateWebhookSecretRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<CreateWebhookResponse> {
    return this.requestWithPrecondition<CreateWebhookResponse>({
      method: 'POST',
      path: `admin/webhooks/${encodePathSegment(String(id))}/rotate-secret`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
