/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { AdminResource } from './admin-resource';
import type { AdminRequestOptions } from './admin-resource';
import type { WorkflowNodeRegistryResponse } from './schemas';

/**
 * `hope.admin.workflowNode` — the `svc:admin:workflow-node:read` administration area.
 *
 * **Required service-account scope: `svc:admin:workflow-node:read`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controller WorkflowNodeController
 * (1 route). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminWorkflowNodeResource extends AdminResource {
  readonly svcScope = 'svc:admin:workflow-node:read';

  /**
   * List the code-owned workflow node-type registry (the Studio’s node palette source)
   *
   * `GET /api/v1/admin/workflow-nodes` — `WorkflowNodeController.fetchAll`.
   */
  fetchAll(options: AdminRequestOptions = {}): Promise<WorkflowNodeRegistryResponse> {
    return this.request<WorkflowNodeRegistryResponse>({
      method: 'GET',
      path: 'admin/workflow-nodes',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
