/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: `apps/api/route-manifest.json` (route existence, verb,
 * path, `@RequiredSvcScopes`, `@RequiresIfMatch`) cross-checked against
 * `apps/api/openapi.json` (request/response types). Regenerate with
 * `pnpm --filter @arcaai/vox-node gen:admin`; `gen:admin:check` fails CI on
 * any hand-edit.
 */

import { encodePathSegment } from '../../core/url';
import { AdminResource } from './admin-resource';
import type { AdminListOptions, AdminListQuery, AdminRequestOptions, IfMatchPrecondition, PaginatedPage } from './admin-resource';
import type {
  CloneWorkflowDefinitionRequest,
  CreateWorkflowDefinitionRequest,
  NodePromptBindingResponse,
  NodePromptUpdateResponse,
  PublishWorkflowDefinitionRequest,
  SandboxRunCancelResponse,
  SandboxRunResponse,
  SandboxRunStatusResponse,
  StartSandboxRunRequest,
  UpdateNodePromptRequest,
  UpdateWorkflowDefinitionRequest,
  UpsertWorkflowAssignmentRequest,
  WorkflowAssignmentResponse,
  WorkflowDefinitionResponse,
  WorkflowWebhookSecretResponseDto,
} from './schemas';

/**
 * `hope.admin.workflowDefinition` — the `svc:admin:workflow-definition:manage` administration area.
 *
 * **Required service-account scope: `svc:admin:workflow-definition:manage`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.
 *
 * Backed by controllers WorkflowAssignmentController, WorkflowDefinitionController, WorkflowSandboxRunController
 * (22 routes). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class AdminWorkflowDefinitionResource extends AdminResource {
  readonly svcScope = 'svc:admin:workflow-definition:manage';

  /**
   * List the caller tenant’s workflow assignments for one palette
   *
   * `GET /api/v1/admin/workflow-assignments` — `WorkflowAssignmentController.fetchAll`.
   */
  workflowAssignmentFetchAll(options: AdminRequestOptions & { query?: { paletteKey: string } } = {}): Promise<WorkflowAssignmentResponse[]> {
    return this.request<WorkflowAssignmentResponse[]>({
      method: 'GET',
      path: 'admin/workflow-assignments',
      query: options.query,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Re-assign one tier
   *
   * Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED and the server runs a Compare-And-Set against the row’s `_version`. When the header is present it overrides the body-field `expectedVersion`. Version drift is `412`; a missing header is `428`.
   *
   * `PATCH /api/v1/admin/workflow-assignments` — `WorkflowAssignmentController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  workflowAssignmentUpdate(
    body: UpsertWorkflowAssignmentRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<WorkflowAssignmentResponse> {
    return this.requestWithPrecondition<WorkflowAssignmentResponse>({
      method: 'PATCH',
      path: 'admin/workflow-assignments',
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Create the assignment for one (scope, scopeId, palette) tier
   *
   * Creates the tier’s assignment. Editing an EXISTING assignment goes through `PATCH` so the optimistic-concurrency contract applies; this route is the first write for a tier.
   *
   * `POST /api/v1/admin/workflow-assignments` — `WorkflowAssignmentController.create`.
   */
  workflowAssignmentCreate(body: UpsertWorkflowAssignmentRequest, options: AdminRequestOptions = {}): Promise<WorkflowAssignmentResponse> {
    return this.request<WorkflowAssignmentResponse>({
      method: 'POST',
      path: 'admin/workflow-assignments',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Remove one assignment — the tier reverts to inheriting
   *
   * Soft-deletes the assignment row and appends a WORM change record with a null `afterSlug`.
   *
   * `DELETE /api/v1/admin/workflow-assignments/{id}` — `WorkflowAssignmentController.remove`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  remove(
    id: string,
    options: AdminRequestOptions & { query?: { reason?: string } } & { ifMatch: IfMatchPrecondition },
  ): Promise<WorkflowAssignmentResponse> {
    return this.requestWithPrecondition<WorkflowAssignmentResponse>({
      method: 'DELETE',
      path: `admin/workflow-assignments/${encodePathSegment(String(id))}`,
      query: options.query,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get one workflow assignment
   *
   * `GET /api/v1/admin/workflow-assignments/{id}` — `WorkflowAssignmentController.fetchById`.
   */
  workflowAssignmentFetchById(id: string, options: AdminRequestOptions = {}): Promise<WorkflowAssignmentResponse> {
    return this.request<WorkflowAssignmentResponse>({
      method: 'GET',
      path: `admin/workflow-assignments/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List the caller tenant’s workflow definition versions
   *
   * `GET /api/v1/admin/workflow-definitions` — `WorkflowDefinitionController.fetchAll`.
   *
   * Returns ONE page. `page` is 0-based and both `page` and `limit` are always sent explicitly — the gateway echoes RAW query values back, so the response's own `page`/`limit` are not usable as loop state. Use {@link workflowDefinitionFetchAllIterate} to walk every page.
   */
  workflowDefinitionFetchAll(options: AdminListOptions & { query?: AdminListQuery } = {}): Promise<PaginatedPage<WorkflowDefinitionResponse>> {
    return this.listPage<WorkflowDefinitionResponse>('admin/workflow-definitions', options);
  }

  /**
   * List the caller tenant’s workflow definition versions
   *
   * `GET /api/v1/admin/workflow-definitions` — `WorkflowDefinitionController.fetchAll`.
   *
   * Walks every page, yielding rows: `for await (const row of …)`. Pagination is driven from the REQUEST side; a failure on page N propagates after page N-1's rows, so "the list ended" and "the list broke" never look alike.
   */
  workflowDefinitionFetchAllIterate(
    options: AdminListOptions & { query?: AdminListQuery } = {},
  ): AsyncGenerator<WorkflowDefinitionResponse, void, undefined> {
    return this.listAll<WorkflowDefinitionResponse>('admin/workflow-definitions', options);
  }

  /**
   * Create a new DRAFT workflow definition version for the caller tenant
   *
   * `POST /api/v1/admin/workflow-definitions` — `WorkflowDefinitionController.create`.
   */
  workflowDefinitionCreate(body: CreateWorkflowDefinitionRequest, options: AdminRequestOptions = {}): Promise<WorkflowDefinitionResponse> {
    return this.request<WorkflowDefinitionResponse>({
      method: 'POST',
      path: 'admin/workflow-definitions',
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Start a sandbox run of the CURRENT graph of :definitionId — DRAFT or published, never writes external artifacts.
   *
   * `POST /api/v1/admin/workflow-definitions/{definitionId}/sandbox-runs` — `WorkflowSandboxRunController.start`.
   */
  start(definitionId: string, body: StartSandboxRunRequest, options: AdminRequestOptions = {}): Promise<SandboxRunResponse> {
    return this.request<SandboxRunResponse>({
      method: 'POST',
      path: `admin/workflow-definitions/${encodePathSegment(String(definitionId))}/sandbox-runs`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Live run status + stages (queried from the interpreter dispatcher).
   *
   * `GET /api/v1/admin/workflow-definitions/{definitionId}/sandbox-runs/{runId}` — `WorkflowSandboxRunController.getStatus`.
   */
  getStatus(definitionId: string, runId: string, options: AdminRequestOptions = {}): Promise<SandboxRunStatusResponse> {
    return this.request<SandboxRunStatusResponse>({
      method: 'GET',
      path: `admin/workflow-definitions/${encodePathSegment(String(definitionId))}/sandbox-runs/${encodePathSegment(String(runId))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Cancel a sandbox run — the interpreter's allow-listed cancel signal, never a caller-supplied signal name.
   *
   * `POST /api/v1/admin/workflow-definitions/{definitionId}/sandbox-runs/{runId}/cancel` — `WorkflowSandboxRunController.cancel`.
   */
  cancel(definitionId: string, runId: string, options: AdminRequestOptions = {}): Promise<SandboxRunCancelResponse> {
    return this.request<SandboxRunCancelResponse>({
      method: 'POST',
      path: `admin/workflow-definitions/${encodePathSegment(String(definitionId))}/sandbox-runs/${encodePathSegment(String(runId))}/cancel`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * SSE progress + result. Accepts `Authorization: Bearer <jwt>` or a single-use `?ticket=<ticket>` (scope `workflow_run:<runId>`).
   *
   * Reuses the SAME `workflow_run:<runId>` ticket namespace and mint-time ownership assertion registered (AuthController.assertWorkflowRunScopeOwnership) — a sandbox run is a `WorkflowRun` row like any other, just isSandbox: true. Bridges from a POLLING read of the harness dispatcher (no live event-stream producer exists on the interpreter yet); every reconnect resyncs from the CURRENT live status rather than resuming a gap.
   *
   * `GET /api/v1/admin/workflow-definitions/{definitionId}/sandbox-runs/{runId}/stream` — `WorkflowSandboxRunController.stream`.
   */
  stream(definitionId: string, runId: string, options: AdminRequestOptions = {}): Promise<unknown> {
    return this.request<unknown>({
      method: 'GET',
      path: `admin/workflow-definitions/${encodePathSegment(String(definitionId))}/sandbox-runs/${encodePathSegment(String(runId))}/stream`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Soft-delete a workflow definition version
   *
   * `DELETE /api/v1/admin/workflow-definitions/{id}` — `WorkflowDefinitionController.delete`.
   */
  delete(id: string, options: AdminRequestOptions = {}): Promise<WorkflowDefinitionResponse> {
    return this.request<WorkflowDefinitionResponse>({
      method: 'DELETE',
      path: `admin/workflow-definitions/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Get one workflow definition version
   *
   * `GET /api/v1/admin/workflow-definitions/{id}` — `WorkflowDefinitionController.fetchById`.
   */
  workflowDefinitionFetchById(id: string, options: AdminRequestOptions = {}): Promise<WorkflowDefinitionResponse> {
    return this.request<WorkflowDefinitionResponse>({
      method: 'GET',
      path: `admin/workflow-definitions/${encodePathSegment(String(id))}`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Update a DRAFT workflow definition version (If-Match OCC)
   *
   * Sparse patch. Optimistic concurrency is enforced: the `If-Match` header (RFC 7232) is REQUIRED and CAS'es against the row `_version`; drift → 412, missing header → 428. Rejected 400 if the row is PUBLISHED/DEPRECATED (branch a new draft instead), or if a replaced `graph` fails shape/engine validation.
   *
   * `PATCH /api/v1/admin/workflow-definitions/{id}` — `WorkflowDefinitionController.update`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  workflowDefinitionUpdate(
    id: string,
    body: UpdateWorkflowDefinitionRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<WorkflowDefinitionResponse> {
    return this.requestWithPrecondition<WorkflowDefinitionResponse>({
      method: 'PATCH',
      path: `admin/workflow-definitions/${encodePathSegment(String(id))}`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Clone an existing workflow (or a platform template) into a NEW draft workflow
   *
   * Seeds a NEW `(tenantId, slug)` lineage — `versionNumber` 1, DRAFT, inactive — from the source definition’s graph. This is NOT `POST /` with a `parentVersionId`: that branches a new version INSIDE the source’s slug. A `targetSlug` this tenant already uses is rejected 409 rather than silently becoming version N+1 of that lineage. Clonable sources are the caller tenant’s own definitions (any status) and the SYSTEM tenant’s live published templates (`GET /templates`). Any other tenant’s id is a 404, indistinguishable from a miss. The graph is copied verbatim; `compiledConfig` and its checksums, `publishedAt`, `isActive` and `tags` are NOT carried over, and the validation report is recomputed for this tenant against the current node registry. Consumes the `maxWorkflowDefinitions` quota exactly as create does.
   *
   * `POST /api/v1/admin/workflow-definitions/{id}/clone` — `WorkflowDefinitionController.clone`.
   */
  clone(id: string, body: CloneWorkflowDefinitionRequest, options: AdminRequestOptions = {}): Promise<WorkflowDefinitionResponse> {
    return this.request<WorkflowDefinitionResponse>({
      method: 'POST',
      path: `admin/workflow-definitions/${encodePathSegment(String(id))}/clone`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Edit a node’s prompt from within the node: mint a new version if the content changed, and move this node’s pin
   *
   * One of DD-11’s TWO update paths, and the only one that moves a pin. When `content` (and `variables`) differ from the template’s latest version, both writes happen in a single transaction: a new immutable `PromptVersion` is minted and THIS node’s `promptVersionNumber` is moved to it. Splitting them would leave either a version nothing points at, or a pin naming a version that was never created. Other nodes bound to the same template are untouched. ADOPTING is not authoring: when the submitted content is byte-identical to the template’s latest version, NOTHING is minted — the pin simply moves to that existing version, and the shared template head is left alone. Because an out-of-band template edit deliberately moves no pin, adoption is the COMMON path, and minting a duplicate on each one made the version list unreadable exactly where an admin goes to read it. Read `promptVersionMinted` on the response to tell the two outcomes apart. Only a DRAFT/VALIDATED definition may be edited — a PUBLISHED graph is immutable, so re-pointing a published workflow’s prompt means branching a new draft. `If-Match` (RFC 7232) is REQUIRED, and is checked on BOTH branches: an unchanged body never buys a stale client a silent 200.
   *
   * `PUT /api/v1/admin/workflow-definitions/{id}/nodes/{nodeId}/prompt` — `WorkflowDefinitionController.updateNodePrompt`.
   *
   * Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).
   */
  updateNodePrompt(
    id: string,
    nodeId: string,
    body: UpdateNodePromptRequest,
    options: AdminRequestOptions & { ifMatch: IfMatchPrecondition },
  ): Promise<NodePromptUpdateResponse> {
    return this.requestWithPrecondition<NodePromptUpdateResponse>({
      method: 'PUT',
      path: `admin/workflow-definitions/${encodePathSegment(String(id))}/nodes/${encodePathSegment(String(nodeId))}/prompt`,
      body,
      ifMatch: options.ifMatch,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Which prompt version each node is pinned to, and whether a newer one exists
   *
   * The "new version available" affordance. Editing a prompt template from the Prompt management screen creates a new version and deliberately moves NO node’s pin — that is what stops a shared template from silently changing every workflow that references it. This read is the other half of that guarantee: it makes "this node is behind" visible so it can be re-pinned deliberately, per node. An UNPINNED node is not reported as behind — following the template is a legitimate choice.
   *
   * `GET /api/v1/admin/workflow-definitions/{id}/prompt-bindings` — `WorkflowDefinitionController.listPromptBindings`.
   */
  listPromptBindings(id: string, options: AdminRequestOptions = {}): Promise<NodePromptBindingResponse[]> {
    return this.request<NodePromptBindingResponse[]>({
      method: 'GET',
      path: `admin/workflow-definitions/${encodePathSegment(String(id))}/prompt-bindings`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Compile the graph and publish this version
   *
   * Rejected 400 if the engine gate is not clean (a cycle, an unregistered node type, or malformed shape) — the sole publish-blocking predicate; DRAFT rule-catalogue findings never block publish. `activate` (default true) makes this the version the dispatcher resolves for new runs, demoting the slug’s previous active version. Once published (and WORKFLOW_EXPOSURE_ENABLED), this version becomes invokable through the public exposure plane (`POST /workflows/:slug/invoke`) — if its resolved AI task default (e.g. `smr.finalize`, set under AI Task Defaults) selects a cloud provider, public invocations send this tenant's data to that vendor. Public exposure does NOT restrict provider choice ( R-4 owner ruling, 2026-08-20): the tenant carries that risk.
   *
   * `POST /api/v1/admin/workflow-definitions/{id}/publish` — `WorkflowDefinitionController.publish`.
   */
  publish(id: string, body: PublishWorkflowDefinitionRequest, options: AdminRequestOptions = {}): Promise<WorkflowDefinitionResponse> {
    return this.request<WorkflowDefinitionResponse>({
      method: 'POST',
      path: `admin/workflow-definitions/${encodePathSegment(String(id))}/publish`,
      body,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Re-run shape + engine + DRAFT rule-catalogue validation and persist the report
   *
   * Advances DRAFT -> VALIDATED when the engine gate (shape + compile()) is clean. DRAFT rule-catalogue findings (’s not-yet-clinically-reviewed rules) are recorded on the report but never block this.
   *
   * `POST /api/v1/admin/workflow-definitions/{id}/validate` — `WorkflowDefinitionController.validate`.
   */
  validate(id: string, options: AdminRequestOptions = {}): Promise<WorkflowDefinitionResponse> {
    return this.request<WorkflowDefinitionResponse>({
      method: 'POST',
      path: `admin/workflow-definitions/${encodePathSegment(String(id))}/validate`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List every version row in this definition’s (tenantId, slug) lineage, most recent first
   *
   * `GET /api/v1/admin/workflow-definitions/{id}/versions` — `WorkflowDefinitionController.fetchVersions`.
   */
  fetchVersions(id: string, options: AdminRequestOptions = {}): Promise<WorkflowDefinitionResponse[]> {
    return this.request<WorkflowDefinitionResponse[]>({
      method: 'GET',
      path: `admin/workflow-definitions/${encodePathSegment(String(id))}/versions`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * Issue or rotate the inbound webhook secret for a workflow lineage (returned exactly once)
   *
   * Mints the HMAC secret external systems sign `POST /hooks/workflows/{hookId}` deliveries with, and the `hookUrl` they POST to. The raw secret is returned ONCE; only reversible ciphertext is persisted. Rotating invalidates the previous secret immediately. The Trigger node must declare the `webhook` kind for deliveries to be accepted.
   *
   * `POST /api/v1/admin/workflow-definitions/slug/{slug}/webhook-secret` — `WorkflowDefinitionController.rotateWebhookSecret`.
   */
  rotateWebhookSecret(slug: string, options: AdminRequestOptions = {}): Promise<WorkflowWebhookSecretResponseDto> {
    return this.request<WorkflowWebhookSecretResponseDto>({
      method: 'POST',
      path: `admin/workflow-definitions/slug/${encodePathSegment(String(slug))}/webhook-secret`,
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }

  /**
   * List the platform workflow template library a tenant can clone from
   *
   * The SYSTEM tenant’s live published definitions — one row per slug. Read-only and cross-tenant BY DESIGN, bounded to exactly the SYSTEM tenant: another customer tenant’s definitions can never appear here. This is the discovery half of `POST :id/clone`; the two share one predicate, so everything listed here is clonable.
   *
   * `GET /api/v1/admin/workflow-definitions/templates` — `WorkflowDefinitionController.fetchTemplates`.
   */
  fetchTemplates(options: AdminRequestOptions = {}): Promise<WorkflowDefinitionResponse[]> {
    return this.request<WorkflowDefinitionResponse[]>({
      method: 'GET',
      path: 'admin/workflow-definitions/templates',
      signal: options.signal,
      timeoutMs: options.timeoutMs,
    });
  }
}
