apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: project-hope

resources:
  - configmap.yaml
  - redis.yaml
  - ollama.yaml
  - lmstudio.yaml
  - api.yaml
  - guardrail.yaml
  - reranker.yaml
  - smr.yaml
  - stt-v2.yaml
  - stt-v2-worker.yaml
  - ui.yaml
  - admin-console.yaml
  - db-migrate.yaml
