/**
 * The provider-connection capability vocabulary — DERIVED, not transcribed.
 *
 * `service` is the discriminator of the unified connection plane
 * (`admin/providers/:service/:provider`). -C.1 widened it from the
 * closed `{llm,stt,tts}` set to six capabilities, and the console did not
 * follow: `api/types.ts` and `provider-credentials-tabs.tsx` each carried their
 * OWN hand-typed copy of the three-value list, so a tenant's Qdrant Cloud key
 * and the platform's embeddings connections had an API and no button.
 *
 * THE FIX IS THE SOURCE, NOT THE VALUES. Re-typing six strings here would only
 * move the desynchronisation one widening into the future. Instead the list is
 * derived from the gateway's own contract: `:service` is declared as a schema
 * `enum` on `/api/v1/admin/providers/{service}` in the committed OpenAPI
 * projection this app already ships (`src/server/api-docs/openapi.admin.json`,
 * regenerated by `pnpm api:portal`).
 *
 * WHY A CONSTANT PLUS A GATE, RATHER THAN IMPORTING THE JSON HERE. The admin
 * projection is ~2 MB and `server-only`; importing it into a client component
 * would ship the entire administration API surface to the browser to learn six
 * strings. So the values are materialised here and pinned by
 * `__tests__/provider-services.drift.test.ts`, which parses the snapshot and
 * fails if the two disagree in EITHER direction. The next widening therefore
 * cannot land silently: regenerating the portal turns the console's test suite
 * red until this list follows.
 */

/** The capability a connection row serves. Mirrors `ProviderService` in @arcaai/applications. */
export type ProviderService = 'llm' | 'stt' | 'tts' | 'embeddings' | 'rerank' | 'vector' | 'model-registry';

/**
 * Every capability, in the gateway's declared order. Pinned to the OpenAPI
 * `:service` enum by the drift test — do not edit by hand without the snapshot.
 */
export const PROVIDER_SERVICES = [
  'llm',
  'stt',
  'tts',
  'embeddings',
  'rerank',
  'vector',
  'model-registry',
] as const satisfies readonly ProviderService[];

/** Narrowing guard for a `?psvc=` query param or any other untrusted string. */
export function isProviderService(value: string): value is ProviderService {
  return (PROVIDER_SERVICES as readonly string[]).includes(value);
}
