/**
 * Render an {@link AdminSurface} to the files that land in
 * `packages/vox-node/src/resources/admin/`.
 *
 * Emission rules that keep the drift gate meaningful:
 *
 * - **No timestamps, no versions, no host/user/CI values.** The only inputs
 *   are the two checked-in artifacts, so a re-run on an unchanged tree is
 *   byte-identical by construction rather than by luck.
 * - **Total ordering everywhere** — areas by key, methods by (path, verb,
 *   controller, handler), schemas by name, object members by property name.
 *   `Object.keys()` order is never load-bearing.
 * - **Every file carries the `@generated` banner**, so a reader who opens one
 *   knows the edit will be reverted by `gen:admin:check` before it is reviewed.
 */

import { isSafePropertyName } from './naming';
import type { AdminArea, AdminMethod, AdminSurface } from './types';

/** One emitted file: a path relative to the output directory, and its contents. */
export interface EmittedFile {
  relativePath: string;
  contents: string;
}

const BANNER = `/**
 * @generated by @arcaai/vox-node-codegen — DO NOT EDIT BY HAND.
 *
 * Source of truth: \`apps/api/route-manifest.json\` (route existence, verb,
 * path, \`@RequiredSvcScopes\`, \`@RequiresIfMatch\`) cross-checked against
 * \`apps/api/openapi.json\` (request/response types). Regenerate with
 * \`pnpm --filter @arcaai/vox-node gen:admin\`; \`gen:admin:check\` fails CI on
 * any hand-edit.
 */`;

export function emitSurface(surface: AdminSurface): EmittedFile[] {
  const files: EmittedFile[] = [
    { relativePath: 'schemas.ts', contents: emitSchemas(surface) },
    { relativePath: 'admin-namespace.ts', contents: emitNamespace(surface) },
    { relativePath: 'index.ts', contents: emitBarrel(surface) },
  ];

  for (const area of surface.areas) {
    files.push({ relativePath: `${area.key}.ts`, contents: emitArea(area) });
  }

  return files.sort((a, b) => a.relativePath.localeCompare(b.relativePath));
}

// ─── schemas.ts ─────────────────────────────────────────────────────────────

function emitSchemas(surface: AdminSurface): string {
  const body = surface.schemas.map((schema) => schema.declaration).join('\n\n');
  return `${BANNER}

/**
 * Request and response types for the \`/api/v1/admin/**\` surface, derived from
 * the gateway's own DTOs via \`openapi.json\`.
 *
 * Only the ${surface.schemas.length} component schemas the generated surface transitively
 * reaches are emitted — the document declares more, and importing shapes no
 * method can produce would be noise.
 *
 * A property typed \`unknown\` is the document declining to describe a shape,
 * not this generator giving up: \`openapi-fidelity.md\` §B2 measured the
 * minority of admin operations with no usable schema and the recorded decision
 * was to emit \`unknown\` at those call sites rather than invent one.
 */

${body}
`;
}

// ─── <area>.ts ──────────────────────────────────────────────────────────────

function emitArea(area: AdminArea): string {
  const usedSchemas = collectSchemaNames(area);
  const needsListImports = area.methods.some((m) => m.paginated);
  const needsQueryValue = area.methods.some((m) => m.query.some((q) => q.tsType === 'QueryValue'));
  const needsEncode = area.methods.some((m) => m.pathParams.length > 0);
  const needsIfMatch = area.methods.some((m) => m.requiresIfMatch);

  const baseTypeImports = ['AdminRequestOptions'];
  if (needsListImports) baseTypeImports.push('AdminListOptions', 'AdminListQuery', 'PaginatedPage');
  if (needsIfMatch) baseTypeImports.push('IfMatchPrecondition');

  const imports: string[] = [];
  if (needsEncode) imports.push(`import { encodePathSegment } from '../../core/url';`);
  if (needsQueryValue) imports.push(`import type { QueryValue } from '../../core/url';`);
  imports.push(`import { AdminResource } from './admin-resource';`);
  imports.push(`import type { ${[...new Set(baseTypeImports)].sort().join(', ')} } from './admin-resource';`);
  if (usedSchemas.length > 0) imports.push(`import type { ${usedSchemas.join(', ')} } from './schemas';`);

  const methods = area.methods.flatMap((method) => emitMethod(method, area.svcScope)).join('\n\n');
  // The O-3 widening, stated once at the top of the module rather than only on
  // the individual methods: "which scope do I grant?" is answered by reading
  // the class doc, and the honest answer for these areas is two scopes with
  // different reach.
  const widened = area.methods.filter((method) => extraScopesOf(method, area.svcScope).length > 0);
  const alsoAccepted = [...new Set(widened.flatMap((method) => extraScopesOf(method, area.svcScope)))].sort();
  const readNote =
    alsoAccepted.length === 0
      ? ''
      : `\n *\n * ${widened.length} of its route${widened.length === 1 ? '' : 's'} ALSO accept${widened.length === 1 ? 's' : ''} ` +
        `${alsoAccepted.map((scope) => `\`${scope}\``).join(', ')}, so a read-only grant reaches\n * ${widened.length === 1 ? 'it' : 'them'} and nothing else here. ` +
        `Those methods name their own accepted scopes in a 403;\n * the scope above is the one that reaches EVERY route.`;

  return `${BANNER}

${imports.join('\n')}

/**
 * \`hope.admin.${area.property}\` — the \`${area.svcScope}\` administration area.
 *
 * **Required service-account scope: \`${area.svcScope}\`.** A token without it
 * authenticates normally and is then refused here with 403; {@link AdminResource}
 * names the scope in that error's message.${readNote}
 *
 * Backed by ${area.controllers.length === 1 ? 'controller' : 'controllers'} ${area.controllers.join(', ')}
 * (${area.methods.length} route${area.methods.length === 1 ? '' : 's'}). Several controllers sharing one scope share one
 * resource on purpose: the scope is the permission surface, so the SDK groups
 * by it rather than by URL.
 */
export class ${area.className} extends AdminResource {
  readonly svcScope = '${area.svcScope}';

${methods}
}
`;
}

/**
 * The module's `./schemas` import list — the union of every method's captured
 * refs. Captured during rendering rather than scraped back out of the rendered
 * text: a string enum renders as quoted LITERALS that a regex cannot tell from
 * type names (`SchemaRenderer.capturing`).
 */
function collectSchemaNames(area: AdminArea): string[] {
  const names = new Set<string>();
  for (const method of area.methods) {
    for (const ref of method.schemaRefs) names.add(ref);
  }
  return [...names].sort();
}

function emitMethod(method: AdminMethod, areaScope: string): string[] {
  return method.paginated ? [emitPageMethod(method, areaScope), emitIterateMethod(method, areaScope)] : [emitPlainMethod(method, areaScope)];
}

/**
 * The scopes this route accepts BEYOND the area's own — empty for all but the
 * O-3 read routes. Everything downstream keys off this being empty, so the
 * routes that declare exactly the area scope emit byte-identically to how they
 * did before the widening existed.
 */
function extraScopesOf(method: AdminMethod, areaScope: string): string[] {
  return method.svcScopes.filter((scope) => scope !== areaScope);
}

/** `['a', 'b']` for a route that accepts more than the area scope, otherwise `undefined`. */
function svcScopesLiteral(method: AdminMethod, areaScope: string): string | undefined {
  if (extraScopesOf(method, areaScope).length === 0) return undefined;
  return `[${method.svcScopes.map((scope) => `'${scope}'`).join(', ')}]`;
}

/** The doc-comment line that tells an integrator a read-only grant is enough here. */
function scopeDocLines(method: AdminMethod, areaScope: string): string[] {
  if (extraScopesOf(method, areaScope).length === 0) return [];
  return [
    `Reachable with ANY ONE of ${method.svcScopes.map((scope) => `\`${scope}\``).join(', ')} — the gateway matches required scopes with OR, so the area's \`${areaScope}\` still reaches this route and a read-only grant now does too.`,
  ];
}

/** `admin/tenants/:id` → `` `admin/tenants/${encodePathSegment(String(id))}` `` (or a plain quoted string). */
function pathExpression(method: AdminMethod): string {
  if (method.pathParams.length === 0) return `'${method.path}'`;
  const template = method.path.replace(/:([A-Za-z0-9_]+)\??/g, (_match, name: string) => {
    const param = method.pathParams.find((p) => p.name === name);
    return `\${encodePathSegment(String(${param?.identifier ?? name}))}`;
  });
  return `\`${template}\``;
}

function queryTypeLiteral(method: AdminMethod): string | undefined {
  if (method.query.length === 0) return undefined;
  const members = method.query.map((q) => {
    const key = isSafePropertyName(q.name) ? q.name : `'${q.name.replace(/'/g, "\\'")}'`;
    return `${key}${q.required ? '' : '?'}: ${q.tsType}`;
  });
  return `{ ${members.join('; ')} }`;
}

function docComment(method: AdminMethod, extra: string[] = []): string {
  const lines: string[] = [];
  if (method.summary) lines.push(method.summary);
  if (method.description && method.description !== method.summary) {
    if (lines.length > 0) lines.push('');
    lines.push(method.description);
  }
  if (lines.length > 0) lines.push('');
  lines.push(`\`${method.httpMethod} ${method.documentedPath}\` — \`${method.controller}.${method.handler}\`.`);
  if (method.requiresIfMatch) {
    lines.push('');
    lines.push(
      'Carries `@RequiresIfMatch()`: `options.ifMatch` is required by the type, so the 428 branch is unreachable. On drift the gateway answers 412 (`VersionConflictError.currentVersion`).',
    );
  }
  for (const line of extra) {
    lines.push('');
    lines.push(line);
  }
  return `  /**\n${lines.map((line) => (line ? `   * ${line}` : '   *')).join('\n')}\n   */`;
}

function signatureParams(method: AdminMethod, optionsType: string, optionsRequired: boolean): string {
  const params = method.pathParams.map((p) => `${p.identifier}: ${p.tsType}`);
  if (method.bodyType) params.push(`body${method.bodyRequired ? '' : '?'}: ${method.bodyType}`);
  params.push(optionsRequired ? `options: ${optionsType}` : `options: ${optionsType} = {}`);
  return params.join(', ');
}

function emitPlainMethod(method: AdminMethod, areaScope: string): string {
  const queryLiteral = queryTypeLiteral(method);
  const optionsParts = ['AdminRequestOptions'];
  if (queryLiteral) optionsParts.push(`{ query?: ${queryLiteral} }`);
  if (method.requiresIfMatch) optionsParts.push('{ ifMatch: IfMatchPrecondition }');
  const optionsType = optionsParts.join(' & ');
  const optionsRequired = method.requiresIfMatch;

  const call = method.requiresIfMatch ? 'this.requestWithPrecondition' : 'this.request';
  const specLines = [`method: '${method.httpMethod}'`, `path: ${pathExpression(method)}`];
  if (queryLiteral) specLines.push('query: options.query');
  if (method.bodyType) specLines.push('body');
  if (method.requiresIfMatch) specLines.push('ifMatch: options.ifMatch');
  const scopes = svcScopesLiteral(method, areaScope);
  if (scopes) specLines.push(`svcScopes: ${scopes}`);
  specLines.push('signal: options.signal', 'timeoutMs: options.timeoutMs');

  return `${docComment(method, scopeDocLines(method, areaScope))}
  ${method.name}(${signatureParams(method, optionsType, optionsRequired)}): Promise<${method.returnType}> {
    return ${call}<${method.returnType}>({
      ${specLines.join(',\n      ')},
    });
  }`;
}

function emitPageMethod(method: AdminMethod, areaScope: string): string {
  const queryLiteral = queryTypeLiteral(method);
  const queryType = queryLiteral ? `AdminListQuery & ${queryLiteral}` : 'AdminListQuery';
  const optionsType = `AdminListOptions & { query?: ${queryType} }`;
  const scopes = svcScopesLiteral(method, areaScope);

  return `${docComment(method, [
    `Returns ONE page. \`page\` is 0-based and both \`page\` and \`limit\` are always sent explicitly — the gateway echoes RAW query values back, so the response's own \`page\`/\`limit\` are not usable as loop state. Use {@link ${method.iterateName}} to walk every page.`,
    ...scopeDocLines(method, areaScope),
  ])}
  ${method.name}(${signatureParams(method, optionsType, false)}): Promise<PaginatedPage<${method.rowType}>> {
    return this.listPage<${method.rowType}>(${pathExpression(method)}, options${scopes ? `, ${scopes}` : ''});
  }`;
}

function emitIterateMethod(method: AdminMethod, areaScope: string): string {
  const queryLiteral = queryTypeLiteral(method);
  const queryType = queryLiteral ? `AdminListQuery & ${queryLiteral}` : 'AdminListQuery';
  const optionsType = `AdminListOptions & { query?: ${queryType} }`;
  const scopes = svcScopesLiteral(method, areaScope);

  return `${docComment(method, [
    `Walks every page, yielding rows: \`for await (const row of …)\`. Pagination is driven from the REQUEST side; a failure on page N propagates after page N-1's rows, so "the list ended" and "the list broke" never look alike.`,
    ...scopeDocLines(method, areaScope),
  ])}
  ${method.iterateName}(${signatureParams(method, optionsType, false)}): AsyncGenerator<${method.rowType}, void, undefined> {
    return this.listAll<${method.rowType}>(${pathExpression(method)}, options${scopes ? `, ${scopes}` : ''});
  }`;
}

// ─── admin-namespace.ts ─────────────────────────────────────────────────────

function emitNamespace(surface: AdminSurface): string {
  const imports = surface.areas.map((area) => `import { ${area.className} } from './${area.key}';`).join('\n');
  const fields = surface.areas
    .map(
      (area) =>
        `  /** \`${area.svcScope}\` — ${area.methods.length} route${area.methods.length === 1 ? '' : 's'}. */\n  readonly ${area.property}: ${area.className};`,
    )
    .join('\n');
  const assignments = surface.areas.map((area) => `    this.${area.property} = new ${area.className}(transport);`).join('\n');
  const closed = surface.machineClosed
    .map((entry) => `   * - \`${entry.controller}\` (${entry.routes} route${entry.routes === 1 ? '' : 's'})`)
    .join('\n');

  return `${BANNER}

import type { Transport } from '../../core/transport';
${imports}

/**
 * \`hope.admin\` — every machine-reachable \`/api/v1/admin/**\` area, one property
 * per \`svc:*\` scope (${surface.areas.length} areas, ${surface.areas.reduce((sum, area) => sum + area.methods.length, 0)} routes).
 *
 * Reaching any of it requires a SERVICE ACCOUNT: the admin plane refuses a
 * tenant API key by policy, not by omission. Construct the client with
 * \`serviceAccount: { clientId, clientSecret, workingTenantId? }\`.
 *
 * The following admin controllers are deliberately ABSENT — they are
 * machine-closed by owner decision, and a generated method that always 403s is
 * worse than no method:
 *
${closed}
 *
 * See the barrel (\`./index.ts\`) for which decision closed each one.
 */
export class AdminNamespace {
${fields}

  constructor(transport: Transport) {
${assignments}
  }
}
`;
}

// ─── index.ts ───────────────────────────────────────────────────────────────

function emitBarrel(surface: AdminSurface): string {
  const areaExports = surface.areas.map((area) => `export { ${area.className} } from './${area.key}';`).join('\n');

  return `${BANNER}

/**
 * Barrel for \`@arcaai/vox-node\`'s \`/api/v1/admin/**\` surface (TASK-773).
 *
 * The hand-authored {@link AdminResource} base — the part that holds judgment
 * (pagination, \`If-Match\` plumbing, scope-aware error mapping) — is
 * re-exported first; the ${surface.areas.length} generated per-area resources follow.
 *
 * ## Deliberately absent
 *
 * Five admin controllers are machine-closed by owner decision and are NOT
 * generated. Each carries \`@ForbidServiceAccount()\` or simply declares no
 * \`svc:*\` scope on the gateway, so a generated method would always 403 — and a
 * method that always 403s is worse than no method. Re-opening any of them is an
 * owner decision, not a code-review call (ticket §2.6 / §2.8):
 *
 * | Controller | Decision |
 * |---|---|
 * | \`ServiceAccountController\` (\`admin/service-accounts\`) | **D-3** — self-replication: a machine must not mint another machine. Also pinned by boot audit E. |
 * | \`AdminImpersonationController\` | **D-3** — impersonation is a machine assuming a HUMAN identity, defeating the audit attribution service accounts exist to provide. |
 * | \`ConsentGrantController\` (\`admin/consent-grants\`) | **D-3** — consent is an act of a person; a machine recording it is a compliance claim the platform cannot substantiate. |
 * | \`MonitoringController\` (\`admin/monitoring\`) | **O-1(b)** — never class-level scope-gated, so there is no \`admin:*\` scope to renamespace. |
 * | \`AdminHealthServicesController\` (\`admin/health/services\`) | **O-1(b)** — same. |
 *
 * The generator ASSERTS this rather than filtering on it: if one of these
 * controllers ever declares a \`svc:*\` scope, generation FAILS instead of
 * quietly emitting a surface an owner decision forbids
 * (\`packages/vox-node-codegen/src/surface.ts#MACHINE_CLOSED_CONTROLLERS\`).
 */

export type {
  AdminListOptions,
  AdminListQuery,
  AdminPreconditionedRequestSpec,
  AdminRequestOptions,
  AdminRequestSpec,
  IfMatchPrecondition,
  PaginatedPage,
} from './admin-resource';
export { AdminResource, DEFAULT_ADMIN_PAGE_SIZE, toIfMatchHeader } from './admin-resource';

export { AdminNamespace } from './admin-namespace';

${areaExports}
`;
}
