import * as fs from 'fs';
import * as path from 'path';
import { Logger } from '../../utils/Logger';

const logger = new Logger('PrismaIndexGenerator');

/**
 * Files to export from (excluding internal folder and browser.ts)
 */
const EXPORT_FILES = ['client', 'enums', 'models', 'commonInputTypes'];

/**
 * Generate an index.ts file for the Prisma generated client
 * This creates a barrel export file that re-exports all public artifacts
 */
export async function generatePrismaIndex(generatedClientPath: string): Promise<void> {
  logger.info(`Generating index.ts for Prisma client at: ${generatedClientPath}`);

  if (!fs.existsSync(generatedClientPath)) {
    logger.error(`Generated client path does not exist: ${generatedClientPath}`);
    throw new Error(`Generated client path does not exist: ${generatedClientPath}`);
  }

  // Check which files exist
  const existingFiles: string[] = [];
  for (const file of EXPORT_FILES) {
    const filePath = path.join(generatedClientPath, `${file}.ts`);
    if (fs.existsSync(filePath)) {
      existingFiles.push(file);
    } else {
      logger.warn(`Expected file not found: ${filePath}`);
    }
  }

  if (existingFiles.length === 0) {
    logger.error('No exportable files found in generated client');
    throw new Error('No exportable files found in generated client');
  }

  // Generate the index.ts content
  const indexContent = generateIndexContent(existingFiles);

  // Write the index.ts file
  const indexPath = path.join(generatedClientPath, 'index.ts');
  fs.writeFileSync(indexPath, indexContent, 'utf-8');

  logger.info(`Successfully generated index.ts with exports from: ${existingFiles.join(', ')}`);
}

/**
 * Generate the content for index.ts
 */
function generateIndexContent(files: string[]): string {
  const lines: string[] = [
    '/**',
    ' * Prisma Client Index',
    ' *',
    ' * Auto-generated barrel export file for the Prisma client.',
    ' * This file re-exports all public artifacts from the generated client.',
    ' *',
    ' * DO NOT EDIT THIS FILE MANUALLY - it will be regenerated.',
    ' */',
    '',
    '/* eslint-disable */',
    '// @ts-nocheck',
    '',
  ];

  // Add exports for each file
  for (const file of files) {
    if (file === 'client') {
      // Client file exports PrismaClient, Prisma namespace, and model types
      lines.push(`// Main Prisma Client and types`);
      lines.push(`export * from './${file}';`);
    } else if (file === 'enums') {
      // Enums file exports all enum constants and types
      lines.push(`// Enum exports`);
      lines.push(`export * from './${file}';`);
    } else if (file === 'models') {
      // Models file exports model-specific types
      lines.push(`// Model type exports`);
      lines.push(`export type * from './${file}';`);
    } else if (file === 'commonInputTypes') {
      // CommonInputTypes exports input/output types for queries
      lines.push(`// Common input/output type exports`);
      lines.push(`export type * from './${file}';`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Find the generated client path from the schema path
 * Reads the schema to find the output path configured in the generator block
 */
export function findGeneratedClientPath(schemaPath: string): string | null {
  try {
    // Read schema.prisma to find the output path
    const schemaFilePath = path.join(schemaPath, 'schema.prisma');
    if (!fs.existsSync(schemaFilePath)) {
      logger.warn(`Schema file not found: ${schemaFilePath}`);
      return null;
    }

    const schemaContent = fs.readFileSync(schemaFilePath, 'utf-8');

    // Parse the output path from generator block
    const outputMatch = schemaContent.match(/output\s*=\s*"([^"]+)"/);
    if (!outputMatch) {
      logger.warn('Could not find output path in schema.prisma');
      return null;
    }

    const outputPath = outputMatch[1];
    // Resolve relative to schema directory
    const absolutePath = path.resolve(schemaPath, outputPath);

    logger.info(`Found generated client path: ${absolutePath}`);
    return absolutePath;
  } catch (error) {
    logger.error('Error finding generated client path', error);
    return null;
  }
}

export default generatePrismaIndex;
