/**
 * LLM service-related types
 */

import type { Timestamp } from './common';

/**
 * Supported LLM providers
 */
export type LLMProvider = 'ollama' | 'azure-openai' | 'lm-studio' | 'openai-compat';

/**
 * LLM model information
 */
export interface LLMModel {
  id: string;
  name: string;
  provider: LLMProvider;
  contextLength?: number;
  description?: string;
}

/**
 * LLM generation options
 */
export interface LLMGenerationOptions {
  model: string;
  temperature?: number; // 0-1
  maxTokens?: number;
  topP?: number;
  stream?: boolean;
  systemPrompt?: string;
}

/**
 * LLM message role
 */
export type LLMMessageRole = 'system' | 'user' | 'assistant';

/**
 * LLM chat message
 */
export interface LLMMessage {
  role: LLMMessageRole;
  content: string;
  timestamp?: Timestamp;
}

/**
 * LLM generation response
 */
export interface LLMResponse {
  content: string;
  model: string;
  finishReason?: 'stop' | 'length' | 'error';
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}

/**
 * Meeting summary generated by LLM
 */
export interface LLMSummary {
  id: string;
  meetingId: string;
  summary: string;
  keyPoints?: string[];
  actionItems?: ActionItem[];
  topics?: string[];
  sentiment?: 'positive' | 'neutral' | 'negative';
  model: string;
  provider: LLMProvider;
  createdAt: Timestamp;
}

/**
 * Action item extracted from meeting
 */
export interface ActionItem {
  id: string;
  description: string;
  assignee?: string;
  dueDate?: Timestamp;
  priority?: 'low' | 'medium' | 'high';
  completed: boolean;
}

/**
 * Summary generation options
 */
export interface SummaryOptions {
  includeKeyPoints?: boolean;
  includeActionItems?: boolean;
  includeTopics?: boolean;
  includeSentiment?: boolean;
  customPrompt?: string;
}
