/**
 * `NODE_PORTS` — the declared input/output ports for every node type in
 * `WORKFLOW_NODE_REGISTRY` (closing defect D-4: "`WorkflowNodeDescriptor`
 * declares no `inputs`/`outputs`", `node-registry.ts:46-80`).
 *
 * Authored HERE rather than inline on the registry literals for exactly the reason
 * `NODE_CONFIG_SCHEMAS` is (`node-config-schemas.ts`): the tables are bulky, they are the piece
 * most likely to change per palette, and keeping them in one module means the registry file
 * stays readable as the pipeline it encodes. `node-registry.ts` attaches them uniformly, the
 * same way it attaches `configSchema`.
 *
 * ## Naming convention (uniform, and the canvas depends on it)
 *
 * | Port | Meaning |
 * |---|---|
 * | `after` | INPUT, `control` — "run this node after that one". Pure ordering, no payload. |
 * | `next` | OUTPUT, `control` — the ordering counterpart of `after`. |
 * | `in` | The node's PRIMARY data input. |
 * | `out` | The node's data output. |
 * | anything else | A secondary, semantically named data port (`context`, `prompt`, `verdict`, `entities`, `transcript`, `bypass`, `loop`). |
 *
 * Ordering is separated from data flow on purpose. Before this ticket, every graph in the repo
 * wired BOTH through a single untyped `in`/`out` pair — which is precisely why no type check
 * was possible: one port could not simultaneously mean "the transcript" and "run me after the
 * consent gate". Splitting them is what makes both checkable.
 *
 * ## `outputKey` — the socket's RUNTIME key (OD-15, option A)
 *
 * Every DATA output port declares the key of the producing activity's own output dict that it
 * carries; a `control` port declares none, and the TYPE enforces that (see `port-model.ts`'s
 * `WorkflowPortDescriptor`). This is what lets `_resolve_bound_inputs`
 * (`apps/harness/.../interpreter/workflow.py`) thread ONE value per socket instead of falling
 * back to the whole predecessor output object, and it is the ONE port field mirrored into
 * Python — through `NodeSpec.output_keys` and the committed parity fixture, never a second
 * hand-maintained table.
 *
 * ## MIGRATION — done, and what it cost
 *
 * The seeded graphs are MIGRATED: `seed/21-workflow-definition.ts` and
 * `seed/23-arcaai-workflow-authoring.ts` now name real sockets, their derived blobs were
 * regenerated by their own scripts, and the dead `publishTo` key is gone (see the NOTE on
 * `CONSULTATION_REALTIME_SUMMARY_SCHEMA` in `node-config-schemas.ts`). The golden fixtures under
 * `__tests__/golden/` are deliberately NOT migrated — several exist to FAIL a structural rule,
 * and re-porting them would change what they test.
 *
 * `workflowEdgePortProblems` is still invoked EXPLICITLY at publish time
 * (`port-validation.ts`) rather than folded into `validate()`'s default rule loop: the seeds are
 * migrated, but every OTHER definition saved before this package shipped is not, and folding it
 * in would retroactively invalidate them.
 *
 * One finding worth carrying forward from that migration, because it constrains any future edge
 * you are tempted to add: the consultation palette's structural rules are `allPathsPassThrough`
 * checks (WF-CONS-008/009/010/011/012), so a data edge that SKIPS a mandatory node does not
 * merely look untidy — it makes the graph fail validation. `captureBinding -> realtimeSummary`
 * is the clearest casualty; it jumps `extractEntities`, and WF-CONS-012 refuses it.
 *
 * ## The STT tables are DESIGN INTENT, not observed runtime behaviour
 *
 * All eight `stt.*` node types are RETIRED (`implemented: false`, TASK-861 step 10 / TASK-867)
 * and no interpreter activity exists for them (the former `nodes/stt_placeholder.py` was
 * deleted). A published STT `WorkflowDefinition` compiled into an `AsrPipeline` row and was
 * dispatched through the realtime/batch ASR path, never executed node-by-node by the
 * interpreter. There was never a runtime to infer ports from, so the tables below state the
 * pipeline's intended shape as the contract documented it (audio in → audio through the
 * pre-processors → transcript out of the engine). `bypass` and `loop` were declared because
 * the (since deleted) WF-STT golden fixtures authored those port names; the tables stay for the
 * deprecation window so already-published graphs remain resolvable.
 */
import type { WorkflowPortDescriptor } from './port-model';

export interface WorkflowNodePorts {
  readonly inputs: readonly WorkflowPortDescriptor[];
  readonly outputs: readonly WorkflowPortDescriptor[];
}

/**
 * A DATA port. `outputKey` is the key of the producing activity's `NodeActivityResult.output`
 * dict this socket carries ( option A — see `port-model.ts`'s
 * `WorkflowPortDescriptor` docstring). It is meaningful on OUTPUT ports only; an input port is
 * bound by its own `toPort`, so it never sets one.
 */
function port(
  name: string,
  primitive: Exclude<WorkflowPortDescriptor['primitive'], 'control'>,
  required: boolean,
  multiple: boolean,
  options?: { readonly outputKey: string },
): WorkflowPortDescriptor {
  return Object.freeze(
    options === undefined ? { name, primitive, required, multiple } : { name, primitive, required, multiple, outputKey: options.outputKey },
  );
}

/** A CONTROL port — ordering only. It carries no payload, so it can name no `outputKey`; the
 *  type makes that structural (`outputKey?: never`) rather than conventional. */
function control(name: string, required: boolean, multiple: boolean): WorkflowPortDescriptor {
  return Object.freeze({ name, primitive: 'control' as const, required, multiple });
}

/** The ordering-edge input every node accepts (`core.start` excepted — nothing precedes it). */
const AFTER = control('after', false, true);
/** The ordering-edge output every node offers (`core.end` excepted — nothing follows it). */
const NEXT = control('next', false, true);

function ports(inputs: readonly WorkflowPortDescriptor[], outputs: readonly WorkflowPortDescriptor[]): WorkflowNodePorts {
  return Object.freeze({ inputs: Object.freeze(inputs), outputs: Object.freeze(outputs) });
}

/**
 * Node type -> its declared ports. Every key in `WORKFLOW_NODE_REGISTRY` appears here; a key
 * missing from this table is a failing test (`node-contract.test.ts`), never a silent
 * `inputs: []`, because a node with no declared ports is exactly the D-4 state this closes.
 */
export const NODE_PORTS: Readonly<Record<string, WorkflowNodePorts>> = Object.freeze({
  // -------------------------------------------------------------------------------------------
  // TASK-864 — the `core` vocabulary: the owner's nine primitives plus the two platform-action
  // node types (`core.data`, `core.action`). One palette, composed; behaviour is CONFIGURATION.
  //
  // Three typing choices carry the contract here:
  //
  //  - **`any` (consumer-side wildcard)** on `core.humanReview.in`, `core.condition.in`,
  //    `core.loop.in` and `core.output.in` — the owner's own `in: any`. See `port-model.ts`'s
  //    `ANY_PORT_PRIMITIVE`: it accepts every DATA primitive and can widen nothing back out, so the
  //    anti-laundering rule survives it untouched.
  //  - **Branch handles are DYNAMIC and typed `control`.** `core.classify` fans out one handle
  //    per `classes[].key`, `core.condition` one per `branches[].key`; both keep a static
  //    `otherwise` / `else`, and `core.humanReview` keeps the static `approved` / `rejected` /
  //    `timedOut`. A branch handle carries NO payload — the routing decision is the fact that the
  //    handle was TAKEN — so it is an ordering edge into a downstream node's `after` socket, never a
  //    data edge. The per-class handles cannot be listed here (they are per-instance); the
  //    contract resolves them from the node's config (`core-contract.ts`'s `resolveOutputPort`),
  //    and the compiler turns an edge from any of them into a `branchGuards` entry on the target.
  //  - **`core.agent` declares the union of every task's sockets.** LLM: `in: text` /
  //    `context: object` -> `out: text` / `data: object`; ASR: `audio` -> `transcript`; TTS: `in:
  //    text` -> `audio`. Which subset is LIVE is derived from the referenced agent's task by the
  //    Studio and the activity (the registry is one static contract per TYPE, and an agent's task
  //    is per instance). Every declared socket is a real, typed one, so a graph that wires a
  //    socket the bound agent cannot serve is a publish problem, not a silent no-op.
  //
  // `core.trigger` and `core.output` are the graph BOUNDARIES: the trigger has only a source
  // handle (`out: context<schemaRef>`, the consultation-context object the whole session reads),
  // the output only target handles. `core.note` has NO ports at all — it is a canvas comment,
  // stripped by `compile()`; `node-contract.test.ts` exempts the `annotation` class from the
  // "a node must have a port" rule for exactly that reason.
  //
  // `core.action` declares a generic SUPERSET of sockets; the effective sockets of an instance
  // are the delegated action's own (`ACTION_CATALOGUE[actionKey]` -> the legacy node type's port
  // table), resolved by `core-contract.ts`. The static table exists so the descriptor stays
  // total and the parity fixture stays a projection of static declarations.
  // -------------------------------------------------------------------------------------------
  'core.trigger': ports([], [port('out', 'context<schemaRef>', true, true, { outputKey: 'context' }), NEXT]),
  'core.agent': ports(
    [port('in', 'text', false, true), port('context', 'object', false, true), port('audio', 'audio', false, false), AFTER],
    [
      port('out', 'text', true, true, { outputKey: 'text' }),
      port('data', 'object', false, true, { outputKey: 'data' }),
      port('transcript', 'transcript', false, true, { outputKey: 'transcript' }),
      port('audio', 'audio', false, true, { outputKey: 'audio' }),
      NEXT,
    ],
  ),
  // `in: any` rather than `text`: a Classify node routes whatever it is handed — a transcript,
  // a generated text, or the Trigger's context object (the activity reads `text` off an object
  // and classifies that) — and `any` is the consumer-side wildcard that says so honestly.
  'core.classify': ports(
    [port('in', 'any', true, false), AFTER],
    [port('out', 'object', true, true, { outputKey: 'classification' }), control('otherwise', false, true), NEXT],
  ),
  'core.humanReview': ports(
    [port('in', 'any', false, true), AFTER],
    [
      port('out', 'object', true, true, { outputKey: 'decision' }),
      control('approved', false, true),
      control('rejected', false, true),
      control('timedOut', false, true),
      NEXT,
    ],
  ),
  'core.variable': ports([port('set', 'object', false, true), AFTER], [port('out', 'object', true, true, { outputKey: 'vars' }), NEXT]),
  'core.condition': ports(
    [port('in', 'any', false, true), AFTER],
    [port('out', 'object', true, true, { outputKey: 'evaluation' }), control('else', false, true), NEXT],
  ),
  'core.loop': ports(
    [port('in', 'any', false, true), AFTER],
    [port('each', 'object', true, true, { outputKey: 'item' }), port('done', 'object', true, true, { outputKey: 'result' }), NEXT],
  ),
  'core.note': ports([], []),
  'core.output': ports([port('in', 'any', false, true), AFTER], []),
  'core.data': ports([port('in', 'object', true, true), AFTER], [port('out', 'object', true, true, { outputKey: 'data' }), NEXT]),
  'core.action': ports(
    [
      port('in', 'object', false, true),
      port('text', 'text', false, true),
      port('transcript', 'transcript', false, false),
      port('entities', 'entities', false, true),
      port('document', 'document', false, false),
      port('context', 'context<schemaRef>', false, true),
      AFTER,
    ],
    [
      port('out', 'object', true, true, { outputKey: 'result' }),
      port('text', 'text', false, true, { outputKey: 'text' }),
      port('entities', 'entities', false, true, { outputKey: 'entities' }),
      port('verdict', 'verdict', false, true, { outputKey: 'verdict' }),
      port('document', 'document', false, true, { outputKey: 'document' }),
      port('context', 'context<schemaRef>', false, true, { outputKey: 'context' }),
      NEXT,
    ],
  ),
});

/**
 * TASK-893 — the port tables of the 17 ACTIONS behind `core.action` (`action-catalogue.ts`),
 * keyed by action key. An action instance's EFFECTIVE sockets are its entry here
 * (`effectivePorts('core.action', config)`); `core.action`'s own entry above is the static
 * SUPERSET that keeps the descriptor total. Copied verbatim from the retired node types' tables.
 */
export const ACTION_PORTS: Readonly<Record<string, WorkflowNodePorts>> = Object.freeze({
  'consultation.consentGate': ports([AFTER], [control('out', true, true), NEXT]),
  'consultation.bindTerminology': ports(
    [port('in', 'entities', true, false), AFTER],
    [port('out', 'entities', true, true, { outputKey: 'entities' }), NEXT],
  ),
  'consultation.phiHop': ports([port('in', 'transcript', true, false), AFTER], [port('out', 'transcript', true, true, { outputKey: 'text' }), NEXT]),
  'consultation.retrieveEvidence': ports(
    [port('in', 'entities', false, true), AFTER],
    [port('out', 'context<schemaRef>', true, true, { outputKey: 'context' }), NEXT],
  ),
  'consultation.sensors': ports(
    [port('in', 'document', true, false), port('entities', 'entities', false, true), AFTER],
    [port('out', 'verdict', true, true, { outputKey: 'verdict' }), port('document', 'document', true, true, { outputKey: 'text' }), NEXT],
  ),
  'consultation.inferentialSensors': ports(
    [port('in', 'document', true, false), port('verdict', 'verdict', false, true), AFTER],
    [port('out', 'verdict', true, true, { outputKey: 'verdict' }), port('document', 'document', true, true, { outputKey: 'text' }), NEXT],
  ),
  'consultation.persistDraft': ports(
    [port('in', 'document', true, false), port('verdict', 'verdict', false, true), port('assurance', 'verdict', false, true), AFTER],
    [port('out', 'document', true, true, { outputKey: 'text' }), port('contextItemId', 'text', true, true, { outputKey: 'contextItemId' }), NEXT],
  ),
  'consultation.finalizeAssurance': ports(
    [
      port('in', 'document', true, false),
      port('contextItemId', 'text', false, false),
      port('verdict', 'verdict', false, true),
      port('assurance', 'verdict', false, true),
      AFTER,
    ],
    [port('contextItemId', 'text', true, true, { outputKey: 'contextItemId' }), NEXT],
  ),
  'guard.phi': ports(
    [port('in', 'text', true, false), AFTER],
    [port('out', 'verdict', true, true, { outputKey: 'verdict' }), port('text', 'text', true, true, { outputKey: 'text' }), NEXT],
  ),
  'guard.moderation': ports([port('in', 'text', true, false), AFTER], [port('out', 'verdict', true, true, { outputKey: 'verdict' }), NEXT]),
  'guard.groundedness': ports(
    [port('in', 'document', true, false), port('transcript', 'transcript', false, false), port('findings', 'entities', false, true), AFTER],
    [port('out', 'verdict', true, true, { outputKey: 'verdict' }), NEXT],
  ),
  'session.timeout': ports([AFTER], [NEXT]),
  'feedback.capture': ports([port('in', 'edits', false, true), AFTER], [NEXT]),
  'livedoc.stop': ports([AFTER], [NEXT]),
  'harness.finalize': ports([AFTER], [NEXT]),
  'summary.finalize': ports([port('in', 'document', false, true), AFTER], [NEXT]),
  'prompt.template_ref': ports([AFTER], [port('out', 'text', true, true, { outputKey: 'content' }), NEXT]),
});

/** `{ inputs: [], outputs: [] }` for an unregistered type — callers detect that via the
 *  registry, not by probing this table. */
export const EMPTY_PORTS: WorkflowNodePorts = Object.freeze({ inputs: Object.freeze([]), outputs: Object.freeze([]) });
