/**
 * `NODE_PORTS` — the declared input/output ports for every node type in
 * `WORKFLOW_NODE_REGISTRY` (TASK-809 Task 1, closing defect D-4: "`WorkflowNodeDescriptor`
 * declares no `inputs`/`outputs`", `node-registry.ts:46-80`).
 *
 * Authored HERE rather than inline on the registry literals for exactly the reason
 * `NODE_CONFIG_SCHEMAS` is (`node-config-schemas.ts`): the tables are bulky, they are the piece
 * most likely to change per palette, and keeping them in one module means the registry file
 * stays readable as the pipeline it encodes. `node-registry.ts` attaches them uniformly, the
 * same way it attaches `configSchema`.
 *
 * ## Naming convention (uniform, and the canvas depends on it)
 *
 * | Port | Meaning |
 * |---|---|
 * | `after` | INPUT, `control` — "run this node after that one". Pure ordering, no payload. |
 * | `next` | OUTPUT, `control` — the ordering counterpart of `after`. |
 * | `in` | The node's PRIMARY data input. |
 * | `out` | The node's data output. |
 * | anything else | A secondary, semantically named data port (`context`, `prompt`, `verdict`, `entities`, `transcript`, `bypass`, `loop`). |
 *
 * Ordering is separated from data flow on purpose. Before this ticket, every graph in the repo
 * wired BOTH through a single untyped `in`/`out` pair — which is precisely why no type check
 * was possible: one port could not simultaneously mean "the transcript" and "run me after the
 * consent gate". Splitting them is what makes both checkable.
 *
 * ## `outputKey` — the socket's RUNTIME key (OD-15, option A)
 *
 * Every DATA output port declares the key of the producing activity's own output dict that it
 * carries; a `control` port declares none, and the TYPE enforces that (see `port-model.ts`'s
 * `WorkflowPortDescriptor`). This is what lets `_resolve_bound_inputs`
 * (`apps/harness/.../interpreter/workflow.py`) thread ONE value per socket instead of falling
 * back to the whole predecessor output object, and it is the ONE port field mirrored into
 * Python — through `NodeSpec.output_keys` and the committed parity fixture, never a second
 * hand-maintained table.
 *
 * ## MIGRATION — done, and what it cost
 *
 * The seeded graphs are MIGRATED (OD-15): `seed/21-workflow-definition.ts` and
 * `seed/23-arcaai-workflow-authoring.ts` now name real sockets, their derived blobs were
 * regenerated by their own scripts, and the dead `publishTo` key is gone (see the §SEED NOTE on
 * `CONSULTATION_REALTIME_SUMMARY_SCHEMA` in `node-config-schemas.ts`). The golden fixtures under
 * `__tests__/golden/` are deliberately NOT migrated — several exist to FAIL a structural rule,
 * and re-porting them would change what they test.
 *
 * `workflowEdgePortProblems` is still invoked EXPLICITLY at publish time
 * (`port-validation.ts`) rather than folded into `validate()`'s default rule loop: the seeds are
 * migrated, but every OTHER definition saved before this package shipped is not, and folding it
 * in would retroactively invalidate them.
 *
 * One finding worth carrying forward from that migration, because it constrains any future edge
 * you are tempted to add: the consultation palette's structural rules are `allPathsPassThrough`
 * checks (WF-CONS-008/009/010/011/012), so a data edge that SKIPS a mandatory node does not
 * merely look untidy — it makes the graph fail validation. `captureBinding -> realtimeSummary`
 * is the clearest casualty; it jumps `extractEntities`, and WF-CONS-012 refuses it.
 *
 * ## The STT tables are DESIGN INTENT, not observed runtime behaviour
 *
 * All eight `stt.*` activities are deliberate non-execution placeholders
 * (`apps/harness/src/harness/temporal/interpreter/nodes/stt_placeholder.py:1-13`): a published
 * STT `WorkflowDefinition` compiles into an `AsrPipeline` row and is dispatched through the
 * existing realtime/batch ASR path, never executed node-by-node by the interpreter. There is no
 * runtime to infer ports from, so the tables below state the pipeline's intended shape as
 * TASK-724's contract documents it (audio in → audio through the pre-processors → transcript
 * out of the engine). `bypass` and `loop` are declared because the committed golden FIXTURES
 * author those port names; declaring them keeps those graphs resolvable, so they fail on the
 * structural rule they were written to exercise rather than on "unknown port".
 */
import type { WorkflowPortDescriptor } from './port-model';

export interface WorkflowNodePorts {
  readonly inputs: readonly WorkflowPortDescriptor[];
  readonly outputs: readonly WorkflowPortDescriptor[];
}

/**
 * A DATA port. `outputKey` is the key of the producing activity's `NodeActivityResult.output`
 * dict this socket carries (TASK-809 OD-15 option A — see `port-model.ts`'s
 * `WorkflowPortDescriptor` docstring). It is meaningful on OUTPUT ports only; an input port is
 * bound by its own `toPort`, so it never sets one.
 */
function port(
  name: string,
  primitive: Exclude<WorkflowPortDescriptor['primitive'], 'control'>,
  required: boolean,
  multiple: boolean,
  options?: { readonly outputKey: string },
): WorkflowPortDescriptor {
  return Object.freeze(options === undefined ? { name, primitive, required, multiple } : { name, primitive, required, multiple, outputKey: options.outputKey });
}

/** A CONTROL port — ordering only. It carries no payload, so it can name no `outputKey`; the
 *  type makes that structural (`outputKey?: never`) rather than conventional. */
function control(name: string, required: boolean, multiple: boolean): WorkflowPortDescriptor {
  return Object.freeze({ name, primitive: 'control' as const, required, multiple });
}

/** The ordering-edge input every node accepts (`core.start` excepted — nothing precedes it). */
const AFTER = control('after', false, true);
/** The ordering-edge output every node offers (`core.end` excepted — nothing follows it). */
const NEXT = control('next', false, true);

function ports(inputs: readonly WorkflowPortDescriptor[], outputs: readonly WorkflowPortDescriptor[]): WorkflowNodePorts {
  return Object.freeze({ inputs: Object.freeze(inputs), outputs: Object.freeze(outputs) });
}

/**
 * Node type -> its declared ports. Every key in `WORKFLOW_NODE_REGISTRY` appears here; a key
 * missing from this table is a failing test (`node-contract.test.ts`), never a silent
 * `inputs: []`, because a node with no declared ports is exactly the D-4 state this closes.
 */
export const NODE_PORTS: Readonly<Record<string, WorkflowNodePorts>> = Object.freeze({
  // -------------------------------------------------------------------------------------------
  // Palette-agnostic utility + boundary markers. These execute nothing (`core.start`/`core.end`)
  // or nothing meaningful (`noop`/`passthrough`), so they carry ORDERING ports only. Giving
  // `passthrough` a data port would be a false constraint for the same reason it deliberately
  // has no config schema: it round-trips arbitrary config verbatim, and no fixed data type
  // describes that honestly.
  // -------------------------------------------------------------------------------------------
  noop: ports([AFTER], [NEXT]),
  passthrough: ports([AFTER], [NEXT]),
  'core.start': ports([], [NEXT]),
  'core.end': ports([AFTER], []),

  // -------------------------------------------------------------------------------------------
  // Summarization palette (TASK-720). `generate.text` is the one node with two distinct data
  // inputs — the bound context and the resolved prompt — which is the clearest demonstration of
  // why a single untyped `in` could never be type-checked.
  //
  // OD-15: `input.context_binding`'s activity used to return the bound kinds AS its whole output
  // dict (`{kindKey: value, …}`), which offered no key for a socket to name. It now publishes
  // them under `context` (`nodes/context_binding.py`) — see `port-model.ts` on why a nameless
  // whole-object port was rejected.
  // -------------------------------------------------------------------------------------------
  'input.context_binding': ports([AFTER], [port('out', 'context<schemaRef>', true, true, { outputKey: 'context' }), NEXT]),
  'prompt.template_ref': ports([AFTER], [port('out', 'text', true, true, { outputKey: 'content' }), NEXT]),
  'generate.text': ports(
    [port('context', 'context<schemaRef>', true, false), port('prompt', 'text', false, false), AFTER],
    [port('out', 'document', true, true, { outputKey: 'text' }), NEXT],
  ),
  // `in: text` and not `in: document`: a guardrail legitimately reads ANY textual product — a
  // generated document, a transcript, an assembled prompt — and `document`/`transcript` both
  // widen to `text`. This is the widening direction being useful; the reverse never is.
  'guardrail.check': ports([port('in', 'text', true, false), AFTER], [port('out', 'verdict', true, true, { outputKey: 'verdict' }), NEXT]),
  'output.deliver': ports([port('in', 'document', true, false), port('verdict', 'verdict', false, true), AFTER], [NEXT]),

  // -------------------------------------------------------------------------------------------
  // STT palette (TASK-724) — DESIGN INTENT (see this module's docstring). Audio flows through
  // the pre-processors unchanged in type; `stt.asrEngine` is the ONLY node that turns
  // `stream<audio>` into `transcript`, which is what makes it the palette's mandatory,
  // non-bypassable step in type terms as well as in rule terms.
  //
  // Their `outputKey`s are design intent too, and honestly so: every `stt.*` activity is a
  // registry-parity placeholder that returns DEGRADED with no `output` at all, so no binding off
  // one ever resolves a key. Declaring the keys the real pipeline would publish keeps the table
  // total (the OD-15 invariant is "every data output port names a key", with no palette carve-out)
  // and states the shape the compiled `AsrPipeline` path already implies.
  // -------------------------------------------------------------------------------------------
  'stt.audioInput': ports(
    [AFTER],
    [port('out', 'stream<audio>', true, true, { outputKey: 'audio' }), port('bypass', 'stream<audio>', false, true, { outputKey: 'audio' }), NEXT],
  ),
  'stt.vad': ports([port('in', 'stream<audio>', true, false), AFTER], [port('out', 'stream<audio>', true, true, { outputKey: 'audio' }), NEXT]),
  'stt.noiseFilter': ports([port('in', 'stream<audio>', true, false), AFTER], [port('out', 'stream<audio>', true, true, { outputKey: 'audio' }), NEXT]),
  'stt.diarization': ports([port('in', 'stream<audio>', true, false), AFTER], [port('out', 'stream<audio>', true, true, { outputKey: 'audio' }), NEXT]),
  'stt.languageDetection': ports(
    [port('in', 'stream<audio>', true, false), AFTER],
    [port('out', 'stream<audio>', true, true, { outputKey: 'audio' }), NEXT],
  ),
  'stt.asrEngine': ports(
    [port('in', 'stream<audio>', true, false), AFTER],
    [port('out', 'transcript', true, true, { outputKey: 'transcript' }), control('loop', false, true), NEXT],
  ),
  'stt.transcriptOutput': ports([port('in', 'transcript', true, false), AFTER], [control('loop', false, true), NEXT]),
  // Redaction preserves the type: a redacted transcript is still a transcript, never model
  // prose. That is what lets `asrEngine -> phiHop -> ner` stay legal while `synthesize -> ner`
  // cannot be expressed at all.
  'stt.phiHop': ports([port('in', 'transcript', true, false), AFTER], [port('out', 'transcript', true, true, { outputKey: 'transcript' }), NEXT]),

  // -------------------------------------------------------------------------------------------
  // Consultation palette (TASK-731 + TASK-791). The type assignments here carry the palette's
  // safety semantics:
  //
  //   - `captureBinding` and `phiHop` are the only consultation-side producers of `transcript`
  //     — the verbatim record of what was actually said.
  //   - `extractEntities` (the NER node) consumes `transcript` and NOTHING else. See
  //     `__tests__/anti-laundering.test.ts`.
  //   - every generation node (`synthesize`, `realtimeSummary`) produces `document`, and the two
  //     PROPOSAL surfaces (`suggestions`, `proposeCorrections`) produce `edits` — a set of
  //     model-proposed changes a clinician accepts or rejects, never applied silently
  //     (`node-registry.ts` records exactly that reasoning for `externalWrite: false` on them).
  // -------------------------------------------------------------------------------------------
  // A gate authorizes; it emits a control signal, not data.
  'consultation.consentGate': ports([AFTER], [control('out', true, true), NEXT]),
  // ⚠ OPEN OWNER ITEM (OD-15, recorded rather than resolved). `out: transcript` is DESIGN INTENT,
  // exactly like the `stt.*` tables above: `interpreter_consultation_capture_binding` starts or
  // stops the live-documentation SESSION and emits `{action, consultationId}` — it publishes no
  // transcript, so `outputKey: 'transcript'` names a key the activity does not yet produce today.
  // That is a THIRD descriptor-vs-activity divergence alongside the two OD-15 fixed below, and
  // the honest options are not equivalent: retyping this port `control` would leave the whole
  // consultation palette with NO producer of `transcript` at all, making `extractEntities`'
  // required input unsatisfiable in every graph. Left as design intent, and the interpreter's
  // "declared key absent from this run's output contributes nothing" rule keeps a graph that
  // wires it DEGRADING exactly as it does today rather than raising.
  'consultation.captureBinding': ports([AFTER], [port('out', 'transcript', true, true, { outputKey: 'transcript' }), NEXT]),
  'consultation.extractEntities': ports(
    [port('in', 'transcript', true, false), AFTER],
    [port('out', 'entities', true, true, { outputKey: 'entities' }), NEXT],
  ),
  'consultation.bindTerminology': ports(
    [port('in', 'entities', true, false), AFTER],
    [port('out', 'entities', true, true, { outputKey: 'entities' }), NEXT],
  ),
  'consultation.phiHop': ports([port('in', 'transcript', true, false), AFTER], [port('out', 'transcript', true, true, { outputKey: 'text' }), NEXT]),
  // OD-15: the activity now publishes the retrieved evidence as a context OBJECT under `context`
  // (`nodes/consultation_compose.py`) — same reasoning as `input.context_binding` above.
  'consultation.retrieveEvidence': ports(
    [port('in', 'entities', false, true), AFTER],
    [port('out', 'context<schemaRef>', true, true, { outputKey: 'context' }), NEXT],
  ),
  // ⚠ DOC-vs-CODE DIVERGENCE, recorded rather than resolved. `node-types.md:117` documents this
  // node's input as `TEXT + STRUCTURED`, but the ACTIVITY reads no `bound_inputs` at all — it
  // resolves everything server-side from `consultationId` (`consultation_compose.py:90-118`,
  // which reads only `config.template` / `dnaStyleId` / `conversationLanguage`).
  //
  // Both data inputs are therefore declared OPTIONAL (`required: false`): that is consistent with
  // the code (nothing must be wired for the node to run) while still permitting the wiring the
  // doc describes and the golden fixtures author. Typing them `required: true` off the doc alone
  // would make the activity's own behaviour unpublishable.
  // OWNER CALL NEEDED on which of the two is authoritative — do not silently "fix" either side.
  'consultation.assemblePrompt': ports(
    [port('in', 'context<schemaRef>', false, true), port('transcript', 'transcript', false, false), AFTER],
    [port('out', 'text', true, true, { outputKey: 'text' }), NEXT],
  ),
  // `in: text` (multiple) accepts BOTH the assembled prompt and a transcript widened to text —
  // the two things a clinical note is actually synthesized from.
  'consultation.synthesize': ports([port('in', 'text', true, true), AFTER], [port('out', 'document', true, true, { outputKey: 'text' }), NEXT]),
  // OD-15 — the two verifier nodes gained a `document` PASSTHROUGH output, and their activities
  // now publish their verdict as an object under `verdict`.
  //
  // Both changes are forced by the same thing: a verifier sits BETWEEN synthesis and persistence
  // on every path (WF-CONS-011 makes `sensors` non-bypassable), so with a verdict-only output
  // there was no legal edge by which the note itself could reach `persistDraft` — `synthesize ->
  // persistDraft` skips `sensors` and fails the rule. The verdict object exists for the same
  // reason: `persistDraft`/`finalizeAssurance` read `scores`, `citationsMap`,
  // `guardrailDecisions`, `ragTriadScore` and `reducedAssurance` off the bound verifier value, and
  // a single flat key would have carried exactly one of them and silently dropped the rest.
  'consultation.sensors': ports(
    [port('in', 'document', true, false), port('entities', 'entities', false, true), AFTER],
    [
      port('out', 'verdict', true, true, { outputKey: 'verdict' }),
      port('document', 'document', true, true, { outputKey: 'text' }),
      NEXT,
    ],
  ),
  'consultation.inferentialSensors': ports(
    [port('in', 'document', true, false), port('verdict', 'verdict', false, true), AFTER],
    [
      port('out', 'verdict', true, true, { outputKey: 'verdict' }),
      port('document', 'document', true, true, { outputKey: 'text' }),
      NEXT,
    ],
  ),
  // OD-15 FIX 1 of 2. `persistDraft` declared `[NEXT]` only, yet its activity emits
  // `{contextItemId, text}` and `finalizeAssurance` genuinely consumes the former — so NO legal
  // edge could express the platform's own persist -> assure flow. `contextItemId` is typed `text`
  // because the vocabulary has no id primitive and an id IS a string; it is a SEPARATE socket
  // from `out` so that both can be wired without the interpreter's last-write-wins `toPort`
  // binding dropping one of them.
  //
  // `assurance` is the inferential verifier's own verdict, kept distinct from `verdict` (the
  // computational sensors') for exactly that reason: two verdicts on one socket would leave only
  // the last, and this is the clinical assurance record.
  'consultation.persistDraft': ports(
    [port('in', 'document', true, false), port('verdict', 'verdict', false, true), port('assurance', 'verdict', false, true), AFTER],
    [port('out', 'document', true, true, { outputKey: 'text' }), port('contextItemId', 'text', true, true, { outputKey: 'contextItemId' }), NEXT],
  ),
  // OD-15 FIX 2 of 2. Same defect, and `contextItemId` is an INPUT here — the id whose draft this
  // node backfills the assurance verdict onto. It republishes it so a downstream node (or a
  // second assurance pass) can chain off the same target.
  'consultation.finalizeAssurance': ports(
    [
      port('in', 'document', true, false),
      port('contextItemId', 'text', false, false),
      port('verdict', 'verdict', false, true),
      port('assurance', 'verdict', false, true),
      AFTER,
    ],
    [port('contextItemId', 'text', true, true, { outputKey: 'contextItemId' }), NEXT],
  ),
  // The draft under review is OPTIONAL on the gate: a graph may route the human wait purely as
  // an ordering step. What the gate emits is always a control signal.
  'consultation.hitlGate': ports([port('in', 'document', false, false), AFTER], [control('out', true, true), NEXT]),
  'consultation.realtimeSummary': ports(
    [port('in', 'transcript', true, false), port('entities', 'entities', false, true), AFTER],
    [port('out', 'document', true, true, { outputKey: 'text' }), NEXT],
  ),
  'consultation.suggestions': ports(
    [port('in', 'transcript', true, false), port('entities', 'entities', false, true), AFTER],
    [port('out', 'edits', true, true, { outputKey: 'suggestions' }), NEXT],
  ),
  // `in: text` rather than `transcript`: corrections are proposed over ANY clinical text,
  // including a generated note. Safe precisely because its product is `edits`, which no
  // extraction node consumes.
  'consultation.proposeCorrections': ports(
    [port('in', 'text', true, false), port('entities', 'entities', false, true), AFTER],
    [port('out', 'edits', true, true, { outputKey: 'proposals' }), NEXT],
  ),

  // -------------------------------------------------------------------------------------------
  // The ENDPOINT STAGE (TASK-812). Three `trigger: 'on-end'` nodes — the ordered sequence that
  // runs before a consultation session closes.
  //
  // All three declare CONTROL ports only on the output side, and that is a deliberate,
  // load-bearing choice rather than an unfinished table. Each one's product is a STATE CHANGE,
  // not a value: a stamped endpoint disposition, a set of LOCKED sections, a promoted
  // correction. `output.deliver` sets the precedent — the palette's other terminal writer also
  // declares `[NEXT]` and nothing else. Inventing a data output would mean picking a port type
  // for it, and every candidate in the closed vocabulary would be a lie: an endpoint disposition
  // is not a `verdict`, and "the documents I locked" is not a `document`.
  //
  // `feedback.capture.in: edits` is the exception, and it is the whole of DD-8. It is the ONLY
  // `edits`-consuming node in the registry that also declares `externalWrite`, which is what
  // makes "the only path that promotes an advisory transcript correction over the raw channel"
  // a structural property of the port table rather than a convention someone has to remember.
  // `consultation.proposeCorrections` produces `edits` and writes nothing; this node is where
  // those `edits` can become real, and there is nowhere else for them to go.
  // -------------------------------------------------------------------------------------------
  'session.timeout': ports([AFTER], [NEXT]),
  // `in: document` (optional, multiple): finalize legitimately runs after any number of document
  // producers, and DD-3 is that it locks EVERY document of the consultation — not merely the
  // ones wired into it. The port expresses ordering intent; the activity's scope is the
  // consultation, which is why the edge is optional.
  'summary.finalize': ports([port('in', 'document', false, true), AFTER], [NEXT]),
  'feedback.capture': ports([port('in', 'edits', false, true), AFTER], [NEXT]),
});

/** `{ inputs: [], outputs: [] }` for an unregistered type — callers detect that via the
 *  registry, not by probing this table. */
export const EMPTY_PORTS: WorkflowNodePorts = Object.freeze({ inputs: Object.freeze([]), outputs: Object.freeze([]) });
