import { SYSTEM_TENANT_ID } from '../00-constants';
import {
    AiModelFormat,
    AiModelSource,
    ModelCategory,
    ModelTaskType,
    ModelType,
    type AiModelSeed,
} from './shared';

/**
 * LLM (text generation / summarization) + guardrail model catalog
 * (TASK-506 consolidation, §4.3 — the owner-approved 10-model matrix).
 *
 * Replaces the previous 31 LLM/guardrail rows. `sourceUri` carries the
 * provider-native identifier actually sent to the runtime (Ollama tag,
 * LM Studio model name, Azure model id); `slug` stays the stable registry
 * key. New rows use the fresh `80000000-…-0007-…` id block (0001–0006 are
 * occupied by the legacy audio/LLM/browser blocks).
 */
export const LLM_AI_MODELS: AiModelSeed[] = [
    // =========================================================================
    // Guardrail / Safety (kept — slug continuity with HarnessPolicy.safetyModel)
    // =========================================================================
    {
        id: '80000000-0000-0000-0005-000000000060',
        tenantId: SYSTEM_TENANT_ID,
        name: 'Granite Guardian 4.1 8B',
        slug: 'granite-guardian-4.1-8b',
        description: 'IBM Granite Guardian 4.1 8B — safety/guardrail model. `format` is descriptive metadata (GGUF / llama.cpp); serving is provider-based (LM Studio). Platform default for guardrail.validate (AiTaskDefault).',
        category: ModelCategory.NLP,
        taskType: ModelTaskType.GUARDRAIL,
        modelType: ModelType.BASE_MODEL,
        source: AiModelSource.LOCAL,
        sourceUri: 'granite-guardian-4.1-8b',
        sourceRevision: 'main',
        format: AiModelFormat.GGUF,
        provider: 'lm-studio',
        architecture: 'granite',
        memorySizeMb: 4900,
        computeType: 'quantized',
        tags: ['guardrail', 'safety', 'granite'],
    },

    // =========================================================================
    // Ollama provider
    // =========================================================================
    {
        id: '80000000-0000-0000-0007-000000000001',
        tenantId: SYSTEM_TENANT_ID,
        name: 'Gemma 4 12B MLX (Ollama)',
        slug: 'ollama-gemma4-12b-mlx',
        description: 'Google Gemma 4 12B (MLX build) via Ollama — large local text-generation model for Apple-silicon hosts.',
        category: ModelCategory.NLP,
        taskType: ModelTaskType.TEXT_GENERATION,
        modelType: ModelType.QUANTIZED_MODEL,
        source: AiModelSource.LOCAL,
        sourceUri: 'gemma4:12b-mlx',
        sourceRevision: 'main',
        format: AiModelFormat.MLX,
        provider: 'ollama',
        architecture: 'gemma4',
        memorySizeMb: 8192,
        computeType: 'float16',
        tags: ['llm', 'ollama'],
    },
    {
        id: '80000000-0000-0000-0007-000000000002',
        tenantId: SYSTEM_TENANT_ID,
        name: 'Gemma 4 E2B IT QAT (Ollama)',
        slug: 'ollama-gemma4-e2b-it-qat',
        description: 'Google Gemma 4 E2B instruction-tuned QAT via Ollama — compact edge-class text-generation model.',
        category: ModelCategory.NLP,
        taskType: ModelTaskType.TEXT_GENERATION,
        modelType: ModelType.QUANTIZED_MODEL,
        source: AiModelSource.LOCAL,
        sourceUri: 'gemma4:e2b-it-qat',
        sourceRevision: 'main',
        format: AiModelFormat.GGUF,
        provider: 'ollama',
        architecture: 'gemma4',
        memorySizeMb: 2048,
        computeType: 'int8',
        tags: ['llm', 'ollama'],
    },
    {
        id: '80000000-0000-0000-0007-000000000003',
        tenantId: SYSTEM_TENANT_ID,
        name: 'Qwen 3.5 2B (Ollama)',
        slug: 'ollama-qwen3.5-2b',
        description: 'Qwen 3.5 2B via Ollama — smallest local text-generation model, ideal for testing.',
        category: ModelCategory.NLP,
        taskType: ModelTaskType.TEXT_GENERATION,
        modelType: ModelType.QUANTIZED_MODEL,
        source: AiModelSource.LOCAL,
        sourceUri: 'qwen3.5:2b',
        sourceRevision: 'main',
        format: AiModelFormat.GGUF,
        provider: 'ollama',
        architecture: 'qwen3.5',
        memorySizeMb: 1536,
        computeType: 'int8',
        tags: ['llm', 'ollama'],
    },

    // =========================================================================
    // LM Studio provider
    // =========================================================================
    {
        id: '80000000-0000-0000-0007-000000000004',
        tenantId: SYSTEM_TENANT_ID,
        name: 'Gemma 4 E2B IT QAT (LM Studio)',
        slug: 'lms-gemma-4-e2b-it-qat',
        description: 'Google Gemma 4 E2B instruction-tuned QAT via LM Studio — the platform default text/summarization model (HarnessPolicy SYSTEM smrModel).',
        category: ModelCategory.NLP,
        taskType: ModelTaskType.TEXT_GENERATION,
        modelType: ModelType.QUANTIZED_MODEL,
        source: AiModelSource.LOCAL,
        sourceUri: 'gemma-4-e2b-it-qat',
        sourceRevision: 'main',
        format: AiModelFormat.GGUF,
        provider: 'lm-studio',
        architecture: 'gemma4',
        memorySizeMb: 2048,
        computeType: 'int8',
        tags: ['llm', 'lm-studio', 'default', 'summarization'],
    },
    {
        id: '80000000-0000-0000-0007-000000000005',
        tenantId: SYSTEM_TENANT_ID,
        name: 'Gemma 4 E4B IT QAT (LM Studio)',
        slug: 'lms-gemma-4-e4b-it-qat',
        description: 'Google Gemma 4 E4B instruction-tuned QAT via LM Studio — balanced local text-generation model.',
        category: ModelCategory.NLP,
        taskType: ModelTaskType.TEXT_GENERATION,
        modelType: ModelType.QUANTIZED_MODEL,
        source: AiModelSource.LOCAL,
        sourceUri: 'gemma-4-e4b-it-qat',
        sourceRevision: 'main',
        format: AiModelFormat.GGUF,
        provider: 'lm-studio',
        architecture: 'gemma4',
        memorySizeMb: 3072,
        computeType: 'int8',
        tags: ['llm', 'lm-studio'],
    },
    {
        id: '80000000-0000-0000-0007-000000000006',
        tenantId: SYSTEM_TENANT_ID,
        name: 'Gemma 4 Medical ICD-10 (LM Studio)',
        slug: 'lms-gemma-4-medical-icd10',
        description: 'Gemma 4 medical ICD-10 fine-tune via LM Studio — medical-coding-aware text generation.',
        category: ModelCategory.NLP,
        taskType: ModelTaskType.TEXT_GENERATION,
        modelType: ModelType.QUANTIZED_MODEL,
        source: AiModelSource.LOCAL,
        sourceUri: 'gemma-4-medical-icd10',
        sourceRevision: 'main',
        format: AiModelFormat.GGUF,
        provider: 'lm-studio',
        architecture: 'gemma4',
        memorySizeMb: 3072,
        computeType: 'int8',
        tags: ['llm', 'lm-studio', 'medical'],
    },
    {
        id: '80000000-0000-0000-0007-000000000007',
        tenantId: SYSTEM_TENANT_ID,
        name: 'Gemma 4 12B QAT (LM Studio)',
        slug: 'lms-gemma-4-12b-qat',
        description: 'Google Gemma 4 12B QAT via LM Studio — large local text-generation model.',
        category: ModelCategory.NLP,
        taskType: ModelTaskType.TEXT_GENERATION,
        modelType: ModelType.QUANTIZED_MODEL,
        source: AiModelSource.LOCAL,
        sourceUri: 'google/gemma-4-12b-qat',
        sourceRevision: 'main',
        format: AiModelFormat.GGUF,
        provider: 'lm-studio',
        architecture: 'gemma4',
        memorySizeMb: 8192,
        computeType: 'int8',
        tags: ['llm', 'lm-studio'],
    },
    {
        id: '80000000-0000-0000-0007-000000000008',
        tenantId: SYSTEM_TENANT_ID,
        name: 'MedGemma 1.5 4B IT (LM Studio)',
        slug: 'lms-medgemma-1.5-4b-it',
        description: 'MedGemma 1.5 4B instruction-tuned via LM Studio — medical-domain text generation.',
        category: ModelCategory.NLP,
        taskType: ModelTaskType.TEXT_GENERATION,
        modelType: ModelType.QUANTIZED_MODEL,
        source: AiModelSource.LOCAL,
        sourceUri: 'medgemma-1.5-4b-it',
        sourceRevision: 'main',
        format: AiModelFormat.GGUF,
        provider: 'lm-studio',
        architecture: 'gemma3',
        memorySizeMb: 3072,
        computeType: 'int8',
        tags: ['llm', 'lm-studio', 'medical'],
    },

    // =========================================================================
    // Azure OpenAI provider (cloud — endpoint/key/deployment configured by
    // admins later; metaData.azureDeployment is the non-secret placeholder)
    // =========================================================================
    {
        id: '80000000-0000-0000-0007-000000000009',
        tenantId: SYSTEM_TENANT_ID,
        name: 'GPT-5.4 Mini (Azure OpenAI)',
        slug: 'azure-gpt-5.4-mini',
        description: 'OpenAI GPT-5.4 Mini via Azure OpenAI — cloud text generation. Endpoint/API key stay in env/Vault; admins set the deployment name (metaData.azureDeployment).',
        category: ModelCategory.NLP,
        taskType: ModelTaskType.TEXT_GENERATION,
        modelType: ModelType.BASE_MODEL,
        source: AiModelSource.LOCAL,
        sourceUri: 'gpt-5.4-mini',
        sourceRevision: 'main',
        format: AiModelFormat.CLOUD_API,
        provider: 'azure',
        architecture: null,
        memorySizeMb: 0,
        computeType: 'cloud',
        tags: ['llm', 'cloud', 'azure'],
        metaData: { azureDeployment: '' },
    },
];
