/**
 * @arcaai/vox - Prompt Template Types
 *
 * Types for prompt template management.
 * Matches WS-2 backend DTOs (PromptManagementService).
 */

// =============================================================================
// Prompt Template
// =============================================================================

/**
 * Prompt template from the backend.
 */
export interface PromptTemplate {
  id: string;
  name: string;
  description?: string;
  category: PromptTemplateCategory;
  /** Draft or Published. Defaults to DRAFT when absent. */
  status?: PromptTemplateStatus;
  departmentId?: string;
  /**
   * Prompt scope. `TENANT_DEFAULT` (tenant-wide),
   * `DEPARTMENT_DEFAULT` (department-assigned), or `USER_PERSONAL` (owned by
   * `ownerUserId`). Absent = treat as `TENANT_DEFAULT` for back-compat.
   */
  scope?: PromptScope;
  /** Owning user id when `scope === 'USER_PERSONAL'`. */
  ownerUserId?: string | null;
  content: string;
  variables?: PromptVariable[];
  tags: string[];
  currentVersionNumber: number;
  createdAt: string;
  updatedAt: string;
  /**
   * Row's optimistic-concurrency version —
   * `_version` in the database. Distinct from `currentVersionNumber`
   * which is the human-meaningful PromptVersion history counter. Echo
   * this back via the `If-Match` header (or the body's `expectedVersion`)
   * on the next `PATCH` so the server can run a Compare-And-Set.
   */
  version?: number;

  // ── Quality/score testing — last SMR-scored test run ──
  /** Last quality score in [0, 1] from a `test()` run; null until first tested. */
  lastTestScore?: number | null;
  /** Text generated by the SMR service on the last `test()` run. */
  lastTestOutput?: string | null;
  /** ISO timestamp of the last `test()` run. */
  lastTestAt?: string | null;
}

/**
 * Prompt template categories.
 * Matches the PromptTemplateCategory enum in the database.
 */
export type PromptTemplateCategory = 'SYSTEM' | 'SUMMARY' | 'DNA_ANALYSIS' | 'CUSTOM';

/**
 * Publication status for prompt templates.
 * Draft templates are not used in production workflows.
 */
export type PromptTemplateStatus = 'DRAFT' | 'PUBLISHED';

/**
 * Prompt scope. Mirrors the backend `PromptTemplateScope` enum.
 */
export type PromptScope = 'TENANT_DEFAULT' | 'DEPARTMENT_DEFAULT' | 'USER_PERSONAL';

/**
 * A variable definition within a prompt template.
 */
export interface PromptVariable {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'json';
  required: boolean;
  default?: unknown;
  description?: string;
}

// =============================================================================
// Prompt Version
// =============================================================================

/**
 * A version snapshot of a prompt template.
 */
export interface PromptVersion {
  id: string;
  promptTemplateId: string;
  versionNumber: number;
  content: string;
  variables?: PromptVariable[];
  changeReason?: string;
  changedBy?: string;
  createdAt: string;
}

// =============================================================================
// Input Types
// =============================================================================

/**
 * Input for creating a new prompt template.
 */
export interface CreatePromptInput {
  name: string;
  description?: string;
  category: PromptTemplateCategory;
  status?: PromptTemplateStatus;
  departmentId?: string;
  content: string;
  variables?: PromptVariable[];
  tags?: string[];
  /**
   * Admin per-user prompt scope. Defaults to `TENANT_DEFAULT`
   * server-side. Set `USER_PERSONAL` with `ownerUserId` to provision a personal
   * prompt for an in-tenant user (requires `manage:PromptTemplate`).
   */
  scope?: PromptScope;
  /** Owner user id; required/implied only when scope=USER_PERSONAL. */
  ownerUserId?: string;
}

/**
 * Input for updating an existing prompt template.
 */
export interface UpdatePromptInput {
  description?: string;
  content?: string;
  status?: PromptTemplateStatus;
  variables?: PromptVariable[];
  tags?: string[];
  changeReason?: string;
  /**
   * Optimistic-concurrency token — should
   * match the `version` the SDK read from the prior `get()`. The server
   * fails with `412 Precondition Failed` when the row drifted. When the
   * caller uses `If-Match` instead, the header wins.
   */
  expectedVersion?: number;
}

/**
 * Filters for listing prompt templates.
 */
export interface PromptListFilters {
  category?: PromptTemplateCategory;
  departmentId?: string;
  tags?: string[];
  search?: string;
  /** Admin scope filter (e.g. `USER_PERSONAL`). */
  scope?: PromptScope;
  /** Admin owner filter; narrows personal prompts to one user. */
  ownerUserId?: string;
  page?: number;
  limit?: number;
}

// =============================================================================
// Prompt quality/score testing + usage analytics
// =============================================================================

/**
 * Input for `POST /admin/prompt-templates/:id/test`. The server runs the
 * template against the SMR/text-generation service and persists the score via
 * an optimistic-concurrency write, so `expectedVersion` should match the
 * `version` the SDK read from the prior `get()`.
 */
export interface TestPromptInput {
  /** Sample values to interpolate into the template `{{variables}}`. */
  variables?: Record<string, unknown>;
  /** Optional extra sample input appended to the prompt. */
  sampleInput?: string;
  /** OCC token — the row `version` from the prior read. */
  expectedVersion?: number;
}

/**
 * Per-dimension breakdown behind the composite score.
 * Mirrors the backend `PromptTestMetrics` (raw, mixed-type). Dimensions that
 * don't apply to a template are `null`.
 */
export interface PromptTestMetrics {
  wordCount: number;
  nonEmpty: boolean;
  lengthScore: number;
  jsonExpected: boolean;
  jsonValid: boolean | null;
  variablesDeclared: number;
  variableCoverage: number | null;
}

/**
 * Result of a prompt quality/score test run.
 */
export interface PromptTestResult {
  id: string;
  /** Quality score in [0, 1]. */
  score: number;
  /** Text generated by the SMR/text-generation service. */
  output: string;
  /** ISO timestamp of the test run. */
  testedAt: string;
  /** Row version after persisting the test result (OCC token). */
  version: number;
  /**
   * Per-dimension **display** map (each value in
   * `[0, 1]`), derived from `metricDetail`. Ready for the admin Test Playground
   * meter bars (`normalizeMetrics`). Only the genuinely `[0,1]` dimensions are
   * included; absent when the backend returned no breakdown.
   */
  metrics?: Record<string, number>;
  /**
   * The raw, typed backend breakdown (word count, declared
   * variable count, booleans) preserved without loss, behind the `metrics`
   * display map. Absent when the backend returned no breakdown.
   */
  metricDetail?: PromptTestMetrics;
}

/** Usage count grouped by department (null = unassigned). */
export interface PromptUsageByDepartment {
  departmentId: string | null;
  count: number;
}

/** Usage count grouped by doctor (null = unattributed). */
export interface PromptUsageByDoctor {
  doctorId: string | null;
  count: number;
}

/** Usage count grouped by UTC day (YYYY-MM-DD). */
export interface PromptUsageByDay {
  day: string;
  count: number;
}

/**
 * Usage-analytics aggregates from `GET /admin/prompt-templates/analytics/usage`.
 */
export interface PromptUsageAnalytics {
  totalUsages: number;
  byDepartment: PromptUsageByDepartment[];
  byDoctor: PromptUsageByDoctor[];
  byDay: PromptUsageByDay[];
}

/**
 * Valid department prompt field names for assignment.
 */
export type DepartmentPromptField = 'newPatientPromptId' | 'revisitPromptId' | 'summaryPromptId' | 'preSummaryPromptId';

/**
 * Input for assigning a prompt template to a department field.
 */
export interface AssignDepartmentPromptInput {
  departmentId: string;
  promptTemplateId: string;
  field: DepartmentPromptField;
  /**
   * OCC token — the target Department row's current `version` (from a prior
   * GET). The backend `assign-department` write CAS-checks against it and
   * returns 412 on version drift. Required: the endpoint rejects a body without
   * it under the strict (`forbidNonWhitelisted`) validation pipe.
   */
  expectedVersion: number;
}
