/**
 * @arcaai/vox - Prompt Template Types
 *
 * Types for prompt template management.
 * Matches WS-2 backend DTOs (PromptManagementService).
 */

// =============================================================================
// Prompt Template
// =============================================================================

/**
 * Prompt template from the backend.
 */
export interface PromptTemplate {
  id: string;
  name: string;
  description?: string;
  category: PromptTemplateCategory;
  /** Draft or Published. Defaults to DRAFT when absent. */
  status?: PromptTemplateStatus;
  departmentId?: string;
  content: string;
  variables?: PromptVariable[];
  tags: string[];
  currentVersionNumber: number;
  createdAt: string;
  updatedAt: string;
  /**
   * Row's optimistic-concurrency version (TASK-302 Stream D Phase E.3) —
   * `_version` in the database. Distinct from `currentVersionNumber`
   * which is the human-meaningful PromptVersion history counter. Echo
   * this back via the `If-Match` header (or the body's `expectedVersion`)
   * on the next `PATCH` so the server can run a Compare-And-Set.
   */
  version?: number;

  // ── Quality/score testing (TASK-328 A4) — last SMR-scored test run ──
  /** Last quality score in [0, 1] from a `test()` run; null until first tested. */
  lastTestScore?: number | null;
  /** Text generated by the SMR service on the last `test()` run. */
  lastTestOutput?: string | null;
  /** ISO timestamp of the last `test()` run. */
  lastTestAt?: string | null;
}

/**
 * Prompt template categories.
 * Matches the PromptTemplateCategory enum in the database.
 */
export type PromptTemplateCategory = 'SYSTEM' | 'SUMMARY' | 'DNA_ANALYSIS' | 'CUSTOM';

/**
 * Publication status for prompt templates.
 * Draft templates are not used in production workflows.
 */
export type PromptTemplateStatus = 'DRAFT' | 'PUBLISHED';

/**
 * A variable definition within a prompt template.
 */
export interface PromptVariable {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'json';
  required: boolean;
  default?: unknown;
  description?: string;
}

// =============================================================================
// Prompt Version
// =============================================================================

/**
 * A version snapshot of a prompt template.
 */
export interface PromptVersion {
  id: string;
  promptTemplateId: string;
  versionNumber: number;
  content: string;
  variables?: PromptVariable[];
  changeReason?: string;
  changedBy?: string;
  createdAt: string;
}

// =============================================================================
// Input Types
// =============================================================================

/**
 * Input for creating a new prompt template.
 */
export interface CreatePromptInput {
  name: string;
  description?: string;
  category: PromptTemplateCategory;
  status?: PromptTemplateStatus;
  departmentId?: string;
  content: string;
  variables?: PromptVariable[];
  tags?: string[];
}

/**
 * Input for updating an existing prompt template.
 */
export interface UpdatePromptInput {
  description?: string;
  content?: string;
  status?: PromptTemplateStatus;
  variables?: PromptVariable[];
  tags?: string[];
  changeReason?: string;
  /**
   * Optimistic-concurrency token (TASK-302 Stream D Phase E.3) — should
   * match the `version` the SDK read from the prior `get()`. The server
   * fails with `412 Precondition Failed` when the row drifted. When the
   * caller uses `If-Match` instead, the header wins.
   */
  expectedVersion?: number;
}

/**
 * Filters for listing prompt templates.
 */
export interface PromptListFilters {
  category?: PromptTemplateCategory;
  departmentId?: string;
  tags?: string[];
  search?: string;
  page?: number;
  limit?: number;
}

// =============================================================================
// Prompt quality/score testing + usage analytics (TASK-328 A4)
// =============================================================================

/**
 * Input for `POST /admin/prompt-templates/:id/test`. The server runs the
 * template against the SMR/text-generation service and persists the score via
 * an optimistic-concurrency write, so `expectedVersion` should match the
 * `version` the SDK read from the prior `get()`.
 */
export interface TestPromptInput {
  /** Sample values to interpolate into the template `{{variables}}`. */
  variables?: Record<string, unknown>;
  /** Optional extra sample input appended to the prompt. */
  sampleInput?: string;
  /** OCC token — the row `version` from the prior read. */
  expectedVersion?: number;
}

/**
 * Result of a prompt quality/score test run.
 */
export interface PromptTestResult {
  id: string;
  /** Quality score in [0, 1]. */
  score: number;
  /** Text generated by the SMR/text-generation service. */
  output: string;
  /** ISO timestamp of the test run. */
  testedAt: string;
  /** Row version after persisting the test result (OCC token). */
  version: number;
}

/** Usage count grouped by department (null = unassigned). */
export interface PromptUsageByDepartment {
  departmentId: string | null;
  count: number;
}

/** Usage count grouped by doctor (null = unattributed). */
export interface PromptUsageByDoctor {
  doctorId: string | null;
  count: number;
}

/** Usage count grouped by UTC day (YYYY-MM-DD). */
export interface PromptUsageByDay {
  day: string;
  count: number;
}

/**
 * Usage-analytics aggregates from `GET /admin/prompt-templates/analytics/usage`.
 */
export interface PromptUsageAnalytics {
  totalUsages: number;
  byDepartment: PromptUsageByDepartment[];
  byDoctor: PromptUsageByDoctor[];
  byDay: PromptUsageByDay[];
}

/**
 * Valid department prompt field names for assignment.
 */
export type DepartmentPromptField = 'newPatientPromptId' | 'revisitPromptId' | 'summaryPromptId' | 'preSummaryPromptId';

/**
 * Input for assigning a prompt template to a department field.
 */
export interface AssignDepartmentPromptInput {
  departmentId: string;
  promptTemplateId: string;
  field: DepartmentPromptField;
}
