#!/bin/bash
# ============================================================================
# Docker infra wrapper (profile tiers)
# ============================================================================
# Brings up/down the full local-dev Docker stack in one command.
#
# Default tier (core + vault + temporal + rag):
#   postgres, redis, minio, qdrant, vault (+init), temporal (+ui), hope-reranker
#
# USAGE:
#   pnpm infra:dev:up # base tier (vault+temporal+rag)
#   pnpm infra:dev:up -- -o # base + Prometheus/Grafana
#   pnpm infra:dev:up -- -e # base + inference (vLLM, llama.cpp, TEI embed)
#   pnpm infra:dev:up -- -o -e # combine flags
#   pnpm infra:dev:down # tear down ALL known profiles (nothing lingers)
#   pnpm infra:dev:restart # down then up, keeping volumes
#   pnpm infra:dev:status # compose ps (all profiles)
#   pnpm infra:dev:logs # compose logs -f
#   pnpm infra:dev:validate # container + health probe
#   ./scripts/dev-infra.sh up --print
#
# Flags:
#   -o / --observability add prometheus profile
#   -e / --inference add inference profile
# m / --mlflow add mlflow profile (model registry)
#   --rag no-op (rag is default; kept for compat)
#   --print print the compose command only
#
# This script is now the ONLY dev-infra entrypoint. The former
# start-infra.sh (pnpm docker:dev:*) started core services only — no Temporal,
# Vault or rag — which silently produced a half-working stack. It was removed;
# `down` still tears down its legacy `hope-infra` compose project so containers
# created before the removal do not linger.
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

COMPOSE_CORE="infrastructure/docker/docker-compose.yml"
COMPOSE_DEV="infrastructure/docker/docker-compose.dev.yml"

# ---------------------------------------------------------------------------
# Infra interpolation is NOT application configuration.
#
# This script used to `cp .env.example .env`, which turned a 905-line
# application-config template into docker compose's substitution file AND into
# the file every Python service read. Compose now gets its own generated,
# gitignored file containing ONLY the `${VAR}` references that the compose
# files actually interpolate; application config stays in .env.dev.
#
# The variable set is derived from the compose files on every run, so it can
# never drift from what compose needs. Values come from .env.dev; a variable
# absent there is omitted, letting the compose file's own `${VAR:-default}`
# apply. Shell exports still win over this file (compose precedence), which is
# what keeps the Apple-Silicon image overrides below working.
# ---------------------------------------------------------------------------
ENV_FILE="$REPO_ROOT/infrastructure/docker/.env"
SOURCE_ENV_FILE="$REPO_ROOT/.env.dev"

compose_interpolated_vars() {
    grep -ohE '\$\{[A-Za-z_][A-Za-z0-9_]*' "$COMPOSE_CORE" "$COMPOSE_DEV" \
        | sed 's/^\${//' \
        | sort -u \
        || true
}

generate_compose_env_file() {
    local tmp var line found=0 total=0
    tmp="$(mktemp)"

    {
        echo "# GENERATED by scripts/dev-infra.sh — DO NOT EDIT, DO NOT COMMIT."
        echo "#"
        echo "# Docker Compose variable-substitution input ONLY. This is not"
        echo "# application configuration — the API and the Python services read"
        echo "# .env.dev. Every key below is a \${VAR} that"
        echo "# infrastructure/docker/docker-compose{,.dev}.yml actually interpolates."
        echo "#"
        echo "# Source:  $SOURCE_ENV_FILE"
        echo "# Missing keys are omitted on purpose so the compose file's own"
        echo "# \${VAR:-default} applies. Shell exports override this file."
        echo ""
    } >"$tmp"

    while IFS= read -r var; do
        [ -n "$var" ] || continue
        total=$((total + 1))
        [ -f "$SOURCE_ENV_FILE" ] || continue
        line="$(grep -E "^[[:space:]]*${var}=" "$SOURCE_ENV_FILE" | tail -n1 || true)"
        [ -n "$line" ] || continue
        # Strip leading whitespace and a trailing CR (CRLF-edited env files).
        line="${line#"${line%%[![:space:]]*}"}"
        printf '%s\n' "${line%$'\r'}" >>"$tmp"
        found=$((found + 1))
    done < <(compose_interpolated_vars)

    mkdir -p "$(dirname "$ENV_FILE")"
    mv "$tmp" "$ENV_FILE"

    if [ ! -f "$SOURCE_ENV_FILE" ]; then
        echo "WARNING: $SOURCE_ENV_FILE not found — compose will use its built-in defaults." >&2
        echo "         Run 'pnpm setup:dev' (creates it from .env.sample) before running the app services." >&2
    fi
    echo "Compose env: $ENV_FILE ($found/$total interpolated vars sourced from .env.dev)"
}

generate_compose_env_file

# Apple Silicon: TEI default images are x86_64-only. Prefer the published arm64
# tag when unset. HF docs advertise cpu-arm64-1.9, but GHCR currently publishes
# cpu-arm64-latest (linux/arm64) — override via HOPE_RERANKER_IMAGE /
# HOPE_TEI_EMBED_IMAGE when a pinned arm64 tag appears.
arch="$(uname -m)"
case "$arch" in
    arm64|aarch64)
        if [ -z "${HOPE_RERANKER_IMAGE:-}" ]; then
            export HOPE_RERANKER_IMAGE=ghcr.io/huggingface/text-embeddings-inference:cpu-arm64-latest
        fi
        if [ -z "${HOPE_TEI_EMBED_IMAGE:-}" ]; then
            export HOPE_TEI_EMBED_IMAGE=ghcr.io/huggingface/text-embeddings-inference:cpu-arm64-latest
        fi
        ;;
esac

ACTION="${1:-}"
shift || true

WANT_OBS=0
WANT_INF=0
WANT_MLFLOW=0
PRINT=0
for arg in "$@"; do
    # pnpm may forward a literal `--` separator (pnpm infra:dev:up -- -o)
    [ "$arg" = "--" ] && continue
    case "$arg" in
        --rag) ;; # no-op: rag is default
        -o|--observability) WANT_OBS=1 ;;
        -e|--inference) WANT_INF=1 ;;
        -m|--mlflow) WANT_MLFLOW=1 ;;
        --print) PRINT=1 ;;
        *)
            echo "Unknown flag: $arg (known: -o/--observability, -e/--inference, -m/--mlflow, --rag, --print)" >&2
            exit 2
            ;;
    esac
done

# Base tier for `up`. down/status/logs always use the full known set.
UP_PROFILES=(--profile vault --profile temporal --profile rag)
if [ "$WANT_OBS" = "1" ]; then
    UP_PROFILES+=(--profile prometheus)
fi
if [ "$WANT_INF" = "1" ]; then
    UP_PROFILES+=(--profile inference)
fi
if [ "$WANT_MLFLOW" = "1" ]; then
    UP_PROFILES+=(--profile mlflow)
fi

# Include both prometheus and observability aliases so neither path leaves
# Grafana/Prometheus behind. inference covers vllm/llama-cpp/tei-embed.
ALL_PROFILES=(
    --profile vault
    --profile temporal
    --profile rag
    --profile prometheus
    --profile observability
    --profile inference
    # Opt-in on `up` (-m), but ALWAYS in the down/status/logs set
    # omit it here and `infra:dev:down` silently leaves hope-mlflow and its
    # migrate one-shot running, which is exactly the orphan class this array exists to prevent.
    --profile mlflow
)

warn_inference_preflight() {
    echo ""
    echo "NOTE: inference profile requested."
    echo "  - hope-vllm requires an NVIDIA GPU + NVIDIA Container Toolkit."
    echo "  - llama.cpp needs a pre-staged GGUF under LLAMA_CPP_MODELS_DIR (see docs/operations/inference/README.md)."
    echo "  - TEI embed serves BAAI/bge-m3 on :8871 (CPU arm64 image auto-selected on Apple Silicon)."
    if ! docker info 2>/dev/null | grep -qiE 'Runtimes:.*nvidia|nvidia'; then
        echo "WARNING: NVIDIA container runtime not detected — hope-vllm will likely fail to start."
        echo "  llama-cpp + tei-embed may still come up on CPU."
    fi
    echo ""
}

# ---------------------------------------------------------------------------
# Reconcile Vault with .env.dev after the containers are up.
#
# The dev Vault runs in dev mode: its storage is IN-MEMORY, so every recreation
# of `hope-vault` (infra:dev:down/up, a Docker restart, a reboot) wipes kv-v2
# back to the placeholder values dev-init.sh seeds by hand, and mints a fresh
# AppRole role_id. Nothing in the app layer can detect that: the gateway happily
# reads `dev-harness-service-token-change-me` from Vault while apps/harness reads
# the real token from .env.dev, and every internal hop 401s at REQUEST time, far
# from the cause.
#
# So the reconcile belongs HERE — on the one path every entry point goes through
# (`setup:dev`, `stack:dev`, `infra:dev:up`) — not only in dev-setup.sh's step 6.
# Both scripts are idempotent; dev-setup.sh sets SKIP_VAULT_RECONCILE=1 because
# it runs them itself after the DB work.
reconcile_vault() {
    [ "${SKIP_VAULT_RECONCILE:-0}" = "1" ] && return 0
    [ -f "$SOURCE_ENV_FILE" ] || return 0

    local root_token="${VAULT_DEV_ROOT_TOKEN:-root}"
    local ready=0
    for _ in $(seq 1 60); do
        if docker exec "${VAULT_CONTAINER:-hope-vault}" sh -lc \
            "export VAULT_ADDR=http://127.0.0.1:8200 VAULT_TOKEN=${root_token}; vault read -field=role_id auth/approle/role/hope-app/role-id" \
            >/dev/null 2>&1; then
            ready=1
            break
        fi
        sleep 2
    done
    if [ "$ready" != "1" ]; then
        echo "WARNING: Vault did not become ready — skipping credential reconcile." >&2
        echo "         Re-run 'pnpm setup:dev' once Vault is up." >&2
        return 0
    fi

    echo ""
    echo "Reconciling Vault with .env.dev (AppRole creds + kv-v2 secrets)..."
    "$SCRIPT_DIR/refresh-vault-creds.sh"
    # The seed script derives its key list from the BUILT settings registry and
    # fails rather than falling back to a stale hardcoded list, so build on miss.
    if [ ! -f "$REPO_ROOT/packages/applications/dist/services/settings-registry/descriptors/platform-secrets.descriptors.js" ]; then
        pnpm --filter @arcaai/applications build
    fi
    "$SCRIPT_DIR/vault-seed-secrets.sh" --env-file "$SOURCE_ENV_FILE"
}

print_cmd() {
    local mode="$1"
    shift
    if [ "$mode" = "up" ]; then
        echo "docker compose --env-file $ENV_FILE ${UP_PROFILES[*]} -f $COMPOSE_CORE -f $COMPOSE_DEV $*"
    else
        echo "docker compose --env-file $ENV_FILE ${ALL_PROFILES[*]} -f $COMPOSE_CORE -f $COMPOSE_DEV $*"
    fi
}

case "$ACTION" in
    up)
        if [ "$PRINT" = "1" ]; then
            print_cmd up up -d
            exit 0
        fi
        if [ "$WANT_INF" = "1" ]; then
            warn_inference_preflight
        fi
        docker compose --env-file "$ENV_FILE" "${UP_PROFILES[@]}" -f "$COMPOSE_CORE" -f "$COMPOSE_DEV" up -d
        echo ""
        docker compose --env-file "$ENV_FILE" "${ALL_PROFILES[@]}" -f "$COMPOSE_CORE" -f "$COMPOSE_DEV" ps
        reconcile_vault
        echo ""
        echo "Temporal UI:  http://localhost:${TEMPORAL_UI_PORT:-8233}   gRPC: localhost:${TEMPORAL_PORT:-7233}"
        echo "Vault UI:     http://localhost:8200"
        echo "Reranker:     http://localhost:${HOPE_RERANKER_PORT:-8870}"
        if [ "$WANT_OBS" = "1" ]; then
            echo "Prometheus:   http://localhost:${PROMETHEUS_PORT:-9090}"
            echo "Grafana:      http://localhost:${GRAFANA_PORT:-3001}  (admin/admin; anonymous Viewer)"
        fi
        if [ "$WANT_INF" = "1" ]; then
            echo "vLLM:         http://localhost:${TEXT_VLLM_PORT:-8000}"
            echo "llama.cpp:    http://localhost:${TEXT_LLAMA_CPP_PORT:-8080}"
            echo "TEI embed:    http://localhost:${HOPE_TEI_EMBED_PORT:-8871}"
        fi
        ;;
    down)
        # Tear down EVERY declared local-dev service.
        # Two compose project names exist:
        #   hope-infra-dev — combined core+dev files (this script; setup:dev, stack:dev)
        #   hope-infra — core file alone, created by the removed start-infra.sh
        # Both must be stopped or containers linger under the other project.
        if [ "$PRINT" = "1" ]; then
            echo "docker compose --env-file $ENV_FILE ${ALL_PROFILES[*]} -f $COMPOSE_CORE -f $COMPOSE_DEV down --remove-orphans"
            echo "docker compose --env-file $ENV_FILE -f $COMPOSE_CORE down --remove-orphans"
            exit 0
        fi
        echo "Stopping hope-infra-dev (core + all profiles)..."
        docker compose --env-file "$ENV_FILE" "${ALL_PROFILES[@]}" \
            -f "$COMPOSE_CORE" -f "$COMPOSE_DEV" down --remove-orphans
        echo "Stopping hope-infra (core-only project, if any)..."
        docker compose --env-file "$ENV_FILE" -f "$COMPOSE_CORE" down --remove-orphans
        leftover="$(
            docker ps -a --format '{{.Names}}\t{{.Label "com.docker.compose.project"}}' 2>/dev/null \
                | awk -F'\t' '$2 == "hope-infra" || $2 == "hope-infra-dev" { print $1 }' || true
        )"
        if [ -n "$leftover" ]; then
            echo "WARNING: containers still present in hope-infra / hope-infra-dev:" >&2
            echo "$leftover" | sed 's/^/  /' >&2
            echo "Remove manually if orphaned: docker rm -f <name>" >&2
            exit 1
        fi
        echo "All local-dev infra containers stopped (volumes kept)."
        ;;
    status)
        if [ "$PRINT" = "1" ]; then
            print_cmd all ps
            exit 0
        fi
        docker compose --env-file "$ENV_FILE" "${ALL_PROFILES[@]}" -f "$COMPOSE_CORE" -f "$COMPOSE_DEV" ps
        ;;
    logs)
        if [ "$PRINT" = "1" ]; then
            print_cmd all logs -f
            exit 0
        fi
        docker compose --env-file "$ENV_FILE" "${ALL_PROFILES[@]}" -f "$COMPOSE_CORE" -f "$COMPOSE_DEV" logs -f
        ;;
    restart)
        # down then up, preserving the requested tier flags. Volumes are kept
        # (down never passes -v), so data survives a restart.
        if [ "$PRINT" = "1" ]; then
            echo "$0 down --print && $0 up --print"
            exit 0
        fi
        echo "Restarting dev infrastructure..."
        "$0" down
        RESTART_FLAGS=()
        [ "$WANT_OBS" = "1" ] && RESTART_FLAGS+=(--observability)
        [ "$WANT_INF" = "1" ] && RESTART_FLAGS+=(--inference)
        exec "$0" up "${RESTART_FLAGS[@]+"${RESTART_FLAGS[@]}"}"
        ;;
    validate)
        # Focused health probe of the DEV infra containers only. For the full
        # picture including app services and LLM engines, use `pnpm stack:dev:doctor`.
        ok=true
        printf '%s\n' "Validating dev infrastructure..."

        check_container() {
            local req="$1" name="$2" state
            state="$(docker inspect -f '{{.State.Status}}' "$name" 2>/dev/null)" || state="absent"
            if [ "$state" = "running" ]; then
                printf '  \033[0;32m✓\033[0m %-22s running\n' "$name"
            elif [ "$req" = "required" ]; then
                printf '  \033[0;31m✗\033[0m %-22s %s\n' "$name" "$state"
                ok=false
            else
                printf '  \033[1;33m!\033[0m %-22s %s (optional)\n' "$name" "$state"
            fi
        }

        check_container required hope-postgres
        check_container required hope-redis
        check_container required hope-minio
        check_container optional hope-qdrant
        check_container optional hope-vault
        check_container optional hope-temporal
        check_container optional hope-reranker

        if docker exec hope-postgres pg_isready -U "${POSTGRES_USER:-hope}" >/dev/null 2>&1; then
            printf '  \033[0;32m✓\033[0m %-22s accepting connections\n' "postgres:${POSTGRES_PORT:-5432}"
        else
            printf '  \033[0;31m✗\033[0m %-22s not accepting connections\n' "postgres:${POSTGRES_PORT:-5432}"
            ok=false
        fi

        if docker exec hope-redis redis-cli ping 2>/dev/null | grep -q PONG; then
            printf '  \033[0;32m✓\033[0m %-22s PONG\n' "redis:${REDIS_PORT:-6379}"
        else
            printf '  \033[0;31m✗\033[0m %-22s no PONG\n' "redis:${REDIS_PORT:-6379}"
            ok=false
        fi

        echo ""
        if $ok; then
            echo "Dev infrastructure is healthy."
        else
            echo "Dev infrastructure has problems. Start it with: pnpm infra:dev:up" >&2
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 <up|down|restart|status|logs|validate> [-o|--observability] [-e|--inference] [--rag] [--print]" >&2
        exit 2
        ;;
esac
