"""Shared model-lifecycle contract for the HOPE Python services.

See the package README for the contract and its conformance clauses.
"""

from .cache import (
    EVICTION_REASONS,
    CacheStats,
    EvictionCount,
    MetricsSink,
    ModelCache,
    ModelUnavailableError,
    SyncModelCache,
    clamp_cache_ttl_seconds,
)
from .metrics import (
    EVICTIONS_TOTAL,
    LOADS_TOTAL,
    RESIDENT_BYTES_ESTIMATE,
    RESIDENT_MODELS,
    VRAM_FREE_BYTES,
    NullMetricsSink,
    PrometheusMetricsSink,
)
from .resolvable import (
    CACHE_TTL_SECONDS,
    DEFAULT_BUDGET_SECONDS,
    MAX_PROBE_THREADS,
    PACKAGE_PROVIDED_LIBRARIES,
    SLOW_OP_SECONDS,
    WARMUP_BUDGET_SECONDS,
    ResolvableQuery,
    ResolvableResult,
    cache_roots,
    check_resolvable,
    check_resolvable_many,
    clear_resolvable_cache,
    probe_state,
    reset_probe_state,
    reset_warmup_state,
    warm_cache_roots,
    warmup_state,
)
from .vram import make_vram_probe, reset_nvml_detection

__all__ = [
    "CACHE_TTL_SECONDS",
    "DEFAULT_BUDGET_SECONDS",
    "EVICTIONS_TOTAL",
    "EVICTION_REASONS",
    "LOADS_TOTAL",
    "MAX_PROBE_THREADS",
    "PACKAGE_PROVIDED_LIBRARIES",
    "RESIDENT_BYTES_ESTIMATE",
    "RESIDENT_MODELS",
    "SLOW_OP_SECONDS",
    "VRAM_FREE_BYTES",
    "WARMUP_BUDGET_SECONDS",
    "CacheStats",
    "EvictionCount",
    "MetricsSink",
    "ModelCache",
    "ModelUnavailableError",
    "NullMetricsSink",
    "PrometheusMetricsSink",
    "ResolvableQuery",
    "ResolvableResult",
    "SyncModelCache",
    "cache_roots",
    "check_resolvable",
    "check_resolvable_many",
    "clamp_cache_ttl_seconds",
    "clear_resolvable_cache",
    "make_vram_probe",
    "probe_state",
    "reset_nvml_detection",
    "reset_probe_state",
    "reset_warmup_state",
    "warm_cache_roots",
    "warmup_state",
]
