-- Restore the UserVoiceProfile partial unique index.
--
-- WHY THIS MIGRATION EXISTS
-- ==========================
-- 20260413000000_add_user_voice_profile creates a PARTIAL unique index:
--
--   CREATE UNIQUE INDEX "UserVoiceProfile_userId_active_unique"
--       ON "core"."UserVoiceProfile"("userId")
--       WHERE "isActive" = true AND "resourceStatus" = 'ENABLED';
--
-- Prisma's schema language CANNOT express a partial index (there is no
-- `@@unique(..., where: ...)` construct), so `user.prisma` only ever declared
-- the plain, non-unique `@@index([userId, isActive])`. `hope-v2-dev` was
-- built by `prisma db push` (see baseline), which
-- reads only `.prisma` files, so the partial unique index was NEVER created
-- there — a catalog-wide scan confirmed zero partial indexes anywhere in the
-- `core` schema. The invariant "at most one active, enabled voice profile per
-- user" has therefore never been enforced at the database level on this
-- database, even though the migration that is supposed to create it has
-- existed in the repo since 2026-04-13.
--
-- The baseline resolved 20260413000000_add_user_voice_profile as
-- already-applied, which is correct for its other four effects (the table,
-- its two plain indexes, and the FK) but permanently strands the partial
-- index: `migrate deploy` only replays UNAPPLIED migrations from history, it
-- never introspects the live catalog, so a migration marked applied will
-- never run again to backfill an effect `db push` skipped. This migration is
-- the roll-forward that closes that gap. Per the project rule (never edit a
-- committed migration — .claude/rules/02-database-prisma.md §Migration
-- Workflow), the fix must be a NEW migration, not an edit to
-- 20260413000000_add_user_voice_profile.
--
-- REPO-WIDE TRAP THIS DOCUMENTS
-- ==============================
-- Any environment bootstrapped via `db push` (dev policy)
-- will silently be missing EVERY partial index expressed only in a
-- migration's raw SQL, because there is no schema-level representation for
-- Prisma to push. If a future migration adds another partial index, the same
-- silent gap will reappear the moment that database is ever baselined with
-- `migrate resolve --applied` instead of actually replayed. There is no
-- generic guard against this today — the CI drift checks in
-- `.gitlab/ci/validate.yml` compare `.prisma` files against generated
-- TypeScript, not live index definitions against the migration SQL, so this
-- class of gap will not be caught automatically. Anyone authoring a partial
-- index should flag it for manual verification against the live catalog
-- after any baselining exercise.
--
-- PRE-CHECK (2026-08-09, read-only, `hope-v2-dev`/`vox-dev`)
-- ============================================================
-- Re-verified the baseline README's data-state claim immediately
-- before authoring this file, via a throwaway read-only pod:
--   total UserVoiceProfile rows                                    : 5
--   rows matching isActive=true AND resourceStatus='ENABLED'       : 3
--   userIds with >1 matching row (would violate the unique index)  : 0
-- Zero conflicts — the index can be created directly, with no
-- deterministic de-duplication step needed first.
--
-- CONCURRENTLY vs. plain CREATE
-- ================================
-- `CREATE UNIQUE INDEX CONCURRENTLY` avoids taking a write-blocking lock on
-- the table for the duration of the build, which matters on a large,
-- actively-written table. It cannot run inside a transaction, and Prisma
-- wraps every migration file in one by default, so using CONCURRENTLY here
-- would require opting the whole migration out of that transaction (a
-- non-transactional migration is a bigger deviation from house convention
-- than this fix warrants). Given the table holds 5 rows in the only
-- environment this applies to today, and this is a `core`-schema table with
-- no evidence of high-frequency concurrent writes, a plain
-- `CREATE UNIQUE INDEX` inside Prisma's normal transactional migration is
-- the right trade-off: it is simpler, keeps the standard rollback-on-failure
-- behavior, and the brief exclusive lock it takes is not observable at this
-- data volume.
--
-- `IF NOT EXISTS` makes this a no-op on any database where
-- 20260413000000_add_user_voice_profile actually ran via `migrate deploy`
-- (shadow databases, CI, any future environment built from migration
-- history rather than `db push`) — there the partial index already exists
-- and this migration only needs to be a formality in the history.

-- Restore the partial unique index dropped by `db push` baselining.
CREATE UNIQUE INDEX IF NOT EXISTS "UserVoiceProfile_userId_active_unique"
    ON "core"."UserVoiceProfile"("userId")
    WHERE "isActive" = true AND "resourceStatus" = 'ENABLED';
