'use client';

import { useId, useState } from 'react';
import { IconPlus, IconSparkles, IconTrash } from '@tabler/icons-react';
import { toast } from 'sonner';
import { Badge } from '@arcaai/ui/components/shadcn/badge';
import { Button } from '@arcaai/ui/components/shadcn/button';
import { Input } from '@arcaai/ui/components/shadcn/input';
import { Label } from '@arcaai/ui/components/shadcn/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@arcaai/ui/components/shadcn/select';
import { Spinner } from '@arcaai/ui/components/shadcn/spinner';
import { useDeclareConnectionModels } from '../api/hooks';
import { MODEL_TASK_TYPES_BY_SERVICE, type ConnectionModel, type DeclaredConnectionModel, type ProviderService } from '../api/types';

/** A row being edited. `slug` is present only on a row the server already named. */
interface DraftModel extends DeclaredConnectionModel {
  slug?: string;
}

function toDraft(model: ConnectionModel): DraftModel {
  return { wireModelId: model.wireModelId, name: model.name, taskType: model.taskType };
}

/**
 * TASK-890 §3.7a (OD-A) — the models a tenant's connection serves, edited beside
 * the credential that reaches them.
 *
 * This is the second half of "provider and model together": the card above says
 * WHERE the vendor account is, this says WHICH models it serves, and each row
 * becomes a registry model an agent can bind. Three things make it safe to use:
 *
 *  - **the list is the fact.** Save sends the WHOLE list, and the server
 *     withdraws whatever left it. The button says so.
 *  - **names are the server's.** The slug an agent binds is generated from the
 *     provider and the wire id; nothing here invents one. A save refused with
 *     `BYO_SLUG_SHADOWS_PLATFORM` is surfaced verbatim, because the fix (use the
 *     suggested `byo-…` name) is a decision for the admin, not for this form.
 *  - **"Derive from provider" needs no typing.** It fills from the ids the last
 *     "Test connection" listed — the same call that proved the credential.
 */
export function ConnectionModelsEditor({
  service,
  provider,
  label,
  tenantId,
  models,
  discoveredModels,
}: {
  service: ProviderService;
  provider: string;
  label: string;
  tenantId?: string;
  models: ConnectionModel[];
  discoveredModels?: string[];
}) {
  const uid = useId();
  const taskTypes = MODEL_TASK_TYPES_BY_SERVICE[service] ?? [];
  const declare = useDeclareConnectionModels();
  const [draft, setDraft] = useState<DraftModel[] | null>(null);

  const rows = draft ?? models.map(toDraft);
  const defaultTaskType = taskTypes[0]?.value ?? '';
  const dirty = draft !== null;
  const incomplete = rows.some((row) => !row.wireModelId.trim() || !row.name.trim() || !row.taskType);

  function edit(next: DraftModel[]) {
    setDraft(next);
  }

  function derive() {
    const known = new Set(rows.map((row) => row.wireModelId.trim()));
    const added = (discoveredModels ?? [])
      .filter((id) => !known.has(id))
      .map((id) => ({ wireModelId: id, name: id, taskType: defaultTaskType }) satisfies DraftModel);
    if (added.length === 0) {
      toast.info(`No new models to add — the provider listed nothing this connection does not already declare.`);
      return;
    }
    edit([...rows, ...added]);
    toast.success(`${added.length} model${added.length === 1 ? '' : 's'} added from ${label}. Review the names, then save.`);
  }

  function save() {
    declare.mutate(
      {
        service,
        provider,
        tenantId,
        body: { models: rows.map(({ wireModelId, name, taskType, slug }) => ({ wireModelId: wireModelId.trim(), name: name.trim(), taskType, ...(slug ? { slug } : {}) })) },
      },
      {
        onSuccess: () => {
          toast.success(`${label} models saved`);
          setDraft(null);
        },
        // A shadow conflict carries the platform row and a suggested name; the
        // admin decides, so the message is shown rather than auto-applied.
        onError: (error) => toast.error(error.message),
      },
    );
  }

  return (
    <fieldset className="flex flex-col gap-2" aria-describedby={`${uid}-help`}>
      <legend className="text-muted-foreground text-xs font-medium">Models this connection serves</legend>
      <p id={`${uid}-help`} className="text-muted-foreground text-xs">
        Each model becomes a registry entry your agents can bind. Saving replaces the whole list — a model you remove here is withdrawn, and an
        agent still bound to it fails its next publish. Names are generated by the server and stay stable.
      </p>

      {rows.length === 0 ? (
        <p className="text-muted-foreground text-xs italic">No models declared yet. Add one, or derive them from the provider after testing the connection.</p>
      ) : null}

      {rows.map((row, index) => (
        <div key={`${uid}-row-${index}`} className="grid grid-cols-[1fr_1fr_auto] items-end gap-2">
          <div className="flex flex-col gap-1">
            <Label htmlFor={`${uid}-wire-${index}`} className="text-muted-foreground text-xs">
              Model / deployment id
            </Label>
            <Input
              id={`${uid}-wire-${index}`}
              value={row.wireModelId}
              onChange={(event) => edit(rows.map((r, i) => (i === index ? { ...r, wireModelId: event.target.value } : r)))}
              placeholder="gpt-4o-mini"
              className="h-8 font-mono text-xs"
            />
          </div>
          <div className="flex flex-col gap-1">
            <Label htmlFor={`${uid}-name-${index}`} className="text-muted-foreground text-xs">
              Display name
            </Label>
            <Input
              id={`${uid}-name-${index}`}
              value={row.name}
              onChange={(event) => edit(rows.map((r, i) => (i === index ? { ...r, name: event.target.value } : r)))}
              placeholder="GPT-4o mini (production)"
              className="h-8 text-xs"
            />
          </div>
          <div className="flex items-center gap-1">
            <Select value={row.taskType} onValueChange={(value) => edit(rows.map((r, i) => (i === index ? { ...r, taskType: value } : r)))}>
              <SelectTrigger id={`${uid}-task-${index}`} aria-label={`Task for ${row.wireModelId || 'this model'}`} className="h-8 w-44 text-xs">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {taskTypes.map((option) => (
                  <SelectItem key={option.value} value={option.value}>
                    {option.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => edit(rows.filter((_, i) => i !== index))}
              aria-label={`Remove ${row.wireModelId || 'this model'}`}
            >
              <IconTrash aria-hidden />
            </Button>
          </div>
        </div>
      ))}

      <div className="flex flex-wrap items-center gap-2">
        <Button variant="outline" size="sm" onClick={() => edit([...rows, { wireModelId: '', name: '', taskType: defaultTaskType }])}>
          <IconPlus aria-hidden />
          Add model
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={derive}
          disabled={!discoveredModels || discoveredModels.length === 0}
          title={discoveredModels?.length ? undefined : 'Run "Test connection" first — the provider lists its models during the probe.'}
        >
          <IconSparkles aria-hidden />
          Derive from provider
        </Button>
        {discoveredModels?.length ? <Badge variant="secondary">{discoveredModels.length} listed by provider</Badge> : null}
        <div className="ml-auto flex items-center gap-2">
          {dirty ? (
            <Button variant="ghost" size="sm" onClick={() => setDraft(null)} disabled={declare.isPending}>
              Discard changes
            </Button>
          ) : null}
          <Button size="sm" onClick={save} disabled={!dirty || incomplete || declare.isPending} aria-label={`Save the ${label} model list`}>
            {declare.isPending ? <Spinner /> : null}
            Save model list
          </Button>
        </div>
      </div>
      {incomplete ? (
        <p className="text-destructive text-xs" role="alert">
          Every model needs an id, a display name and a task.
        </p>
      ) : null}
    </fieldset>
  );
}
