-- TASK-527 — Model source & path resolution: add `S3` to `AiModelSource`.
--
-- Purely ADDITIVE: one new enum value. No table, column, or row is touched.
--
--   S3 — S3/MinIO-compatible object storage. Admins declare weights as
--   `sourceUri = 's3://bucket/prefix'`; every HOPE deployment already ships a
--   MinIO-compatible endpoint, so this gives an in-deployment, PHI-posture
--   compatible weight store with no cloud dependency.
--
-- Owner decision OD-4: `s3://` ONLY this program. `azure-blob://` is
-- explicitly out of scope; the scheme-dispatch resolver leaves room for it.
--
-- Rollback note: Postgres enum values are effectively irreversible. Rolling
-- back means ceasing to write `source = 'S3'` rows (check the count first);
-- the value itself stays dormant and harmless. This matches the additive-only
-- migration posture in `.claude/rules/02-database-prisma.md`.
--
-- `ADD VALUE IF NOT EXISTS` is idempotent and safe to re-apply against dev/test
-- databases that were patched by hand ahead of the migration history.

ALTER TYPE "core"."AiModelSource" ADD VALUE IF NOT EXISTS 'S3';
